### ISSUE TITLE
Crash report: `NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.`

### ISSUE THREAD

**Issue by Eomhyunjun** [Uniswap/interface#2235]
## URL
  
https://app.uniswap.org/#/vote

## Error

```
NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
```

## Stacktrace

```
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at Ou (https://app.uniswap.org/static/js/3.c141d451.chunk.js:2:1699103)
    at js (https://app.uniswap.org/static/js/3.c141d451.chunk.js:2:1710915)
    at t.unstable_runWithPriority (https://app.uniswap.org/static/js/3.c141d451.chunk.js:2:1731532)
    at qi (https://app.uniswap.org/static/js/3.c141d451.chunk.js:2:1653890)
    at Ps (https://app.uniswap.org/static/js/3.c141d451.chunk.js:2:1708873)
    at bs (https://app.uniswap.org/static/js/3.c141d451.chunk.js:2:1704959)
    at https://app.uniswap.org/static/js/3.c141d451.chunk.js:2:1654113
    at t.unstable_runWithPriority (https://app.uniswap.org/static/js/3.c141d451.chunk.js:2:1731532)
    at qi (https://app.uniswap.org/static/js/3.c141d451.chunk.js:2:1653890)
    at Xi (https://app.uniswap.org/static/js/3.c141d451.chunk.js:2:1654058)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.229 Whale/2.10.123.42 Safari/537.36",
  "browser": {
    "name": "Whale",
    "version": "2.10.123.42",
    "major": "2"
  },
  "engine": {
    "name": "Blink",
    "version": "90.0.4430.229"
  },
  "os": {
    "name": "Mac OS",
    "version": "10.15.7"
  },
  "device": {},
  "cpu": {}
}
```

**Comment by moodysalem** [comment]
Usually this is related to the browser trying to translate manipulating the DOM when it tries to translate something, maybe we should add lang="en" to proposal descriptions and handle them differently so they don't error. Whatever is rendering the markdown perhaps.
