### ISSUE TITLE
Crash report: `Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.`

### ISSUE THREAD

**Issue by zefihh** [Uniswap/interface#2358]
## URL
  
https://app.uniswap.org/#/add/ETH/0xFe2e637202056d30016725477c5da089Ab0A043A/3000

## `mintV3` state
    
```json
{
  "independentField": "CURRENCY_B",
  "typedValue": "0.42",
  "startPriceTypedValue": "",
  "leftRangeTypedValue": "0.504612",
  "rightRangeTypedValue": "2.017710"
}
```

## Error

```
Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
```

## Stacktrace

```
Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at ls (https://app.uniswap.org/static/js/3.3076481c.chunk.js:2:1696006)
    at xo (https://app.uniswap.org/static/js/3.3076481c.chunk.js:2:1667734)
    at https://app.uniswap.org/static/js/main.35453b80.chunk.js:1:420740
    at Ns (https://app.uniswap.org/static/js/3.3076481c.chunk.js:2:1707783)
    at t.unstable_runWithPriority (https://app.uniswap.org/static/js/3.3076481c.chunk.js:2:1725596)
    at Ji (https://app.uniswap.org/static/js/3.3076481c.chunk.js:2:1647954)
    at Ms (https://app.uniswap.org/static/js/3.3076481c.chunk.js:2:1707244)
    at bs (https://app.uniswap.org/static/js/3.3076481c.chunk.js:2:1698701)
    at https://app.uniswap.org/static/js/3.3076481c.chunk.js:2:1648177
    at t.unstable_runWithPriority (https://app.uniswap.org/static/js/3.3076481c.chunk.js:2:1725596)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "93.0.4577.82",
    "major": "93"
  },
  "engine": {
    "name": "Blink",
    "version": "93.0.4577.82"
  },
  "os": {
    "name": "Mac OS",
    "version": "10.13.6"
  },
  "device": {},
  "cpu": {}
}
```

**Comment by moodysalem** [comment]
Also typing anything into the sETH2 input causes it to freeze and crash

**Comment by moodysalem** [comment]
Should be fixed in tomorrow's release and on the preview https://interface-uniswap.vercel.app/
