### ISSUE TITLE
Crash report: `Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.`

### ISSUE THREAD

**Issue by lenbach** [Uniswap/interface#2392]
## URL
  
https://app.uniswap.org/#/add/0xbb0e17ef65f82ab018d8edd776e8dd940327b28b/ETH/3000

## `mintV3` state
    
```json
{
  "independentField": "CURRENCY_A",
  "typedValue": "",
  "startPriceTypedValue": "",
  "leftRangeTypedValue": "0.009621",
  "rightRangeTypedValue": "0.038471"
}
```

## Error

```
Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
```

## Stacktrace

```
Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at df (https://app.uniswap.org/static/js/4.ab98f63c.chunk.js:2:1793740)
    at Sa (https://app.uniswap.org/static/js/4.ab98f63c.chunk.js:2:1765468)
    at https://app.uniswap.org/static/js/main.44a3bb87.chunk.js:1:431317
    at Lf (https://app.uniswap.org/static/js/4.ab98f63c.chunk.js:2:1805517)
    at t.unstable_runWithPriority (https://app.uniswap.org/static/js/4.ab98f63c.chunk.js:2:1823330)
    at qi (https://app.uniswap.org/static/js/4.ab98f63c.chunk.js:2:1745688)
    at Rf (https://app.uniswap.org/static/js/4.ab98f63c.chunk.js:2:1804978)
    at vf (https://app.uniswap.org/static/js/4.ab98f63c.chunk.js:2:1796435)
    at https://app.uniswap.org/static/js/4.ab98f63c.chunk.js:2:1745911
    at t.unstable_runWithPriority (https://app.uniswap.org/static/js/4.ab98f63c.chunk.js:2:1823330)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "92.0.4515.131",
    "major": "92"
  },
  "engine": {
    "name": "Blink",
    "version": "92.0.4515.131"
  },
  "os": {
    "name": "Mac OS",
    "version": "10.15.7"
  },
  "device": {},
  "cpu": {}
}
```

**Comment by willhennessy** [comment]
thanks, closing in favor of https://github.com/Uniswap/interface/issues/2358
