### ISSUE TITLE
Crash report: `Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.`

### ISSUE THREAD

**Issue by Rachel-Eichenberger** [Uniswap/interface#2430]
## URL
  
https://app.uniswap.org/#/add/0x92d6c1e31e14520e676a687f0a93788b716beff5/0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2/10000

## `mintV3` state
    
```json
{
  "independentField": "CURRENCY_A",
  "typedValue": "",
  "startPriceTypedValue": "",
  "leftRangeTypedValue": "0.002199",
  "rightRangeTypedValue": "0.008741"
}
```

## Error

```
Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
```

## Stacktrace

```
Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at df (https://app.uniswap.org/static/js/4.ab98f63c.chunk.js:2:1793740)
    at Sa (https://app.uniswap.org/static/js/4.ab98f63c.chunk.js:2:1765468)
    at https://app.uniswap.org/static/js/main.44a3bb87.chunk.js:1:431317
    at Lf (https://app.uniswap.org/static/js/4.ab98f63c.chunk.js:2:1805517)
    at https://app.uniswap.org/static/js/4.ab98f63c.chunk.js:2:1823330
    at qi (https://app.uniswap.org/static/js/4.ab98f63c.chunk.js:2:1745688)
    at Rf (https://app.uniswap.org/static/js/4.ab98f63c.chunk.js:2:1804978)
    at vf (https://app.uniswap.org/static/js/4.ab98f63c.chunk.js:2:1796435)
    at https://app.uniswap.org/static/js/4.ab98f63c.chunk.js:2:1745911
    at https://app.uniswap.org/static/js/4.ab98f63c.chunk.js:2:1823330
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "93.0.4577.82",
    "major": "93"
  },
  "engine": {
    "name": "Blink",
    "version": "93.0.4577.82"
  },
  "os": {
    "name": "Windows",
    "version": "10"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

Same with Firefox

**Comment by justindomingue** [comment]
@Rachel-Eichenberger will be fixed in today's deployment. See https://interface-uniswap.vercel.app/#/add/0x92d6c1e31e14520e676a687f0a93788b716beff5/0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2/10000

**Comment by justindomingue** [comment]
#2420
