### ISSUE TITLE
Crash report: `Error: Invariant failed`

### ISSUE THREAD

**Issue by dare912** [Uniswap/interface#2431]
## URL
  
https://app.uniswap.org/#/swap

## `swap` state
    
```json
{
  "INPUT": {
    "currencyId": "ETH"
  },
  "OUTPUT": {
    "currencyId": "0xBbff34E47E559ef680067a6B1c980639EEb64D24"
  },
  "independentField": "OUTPUT",
  "typedValue": "9000",
  "recipient": null
}
```

## Error

```
Error: Invariant failed
```

## Stacktrace

```
Error: Invariant failed
    at t.default (https://app.uniswap.org/static/js/35.a4ea1615.chunk.js:2:87003)
    at t.n.sortsBefore (https://app.uniswap.org/static/js/35.a4ea1615.chunk.js:2:74198)
    at https://app.uniswap.org/static/js/main.cb61304d.chunk.js:1:225025
    at Array.map (<anonymous>)
    at https://app.uniswap.org/static/js/main.cb61304d.chunk.js:1:224807
    at Object.Aa [as useMemo] (https://app.uniswap.org/static/js/35.a4ea1615.chunk.js:2:1661714)
    at t.useMemo (https://app.uniswap.org/static/js/35.a4ea1615.chunk.js:2:1581186)
    at Kl (https://app.uniswap.org/static/js/main.cb61304d.chunk.js:1:224785)
    at https://app.uniswap.org/static/js/main.cb61304d.chunk.js:1:226947
    at Zl (https://app.uniswap.org/static/js/main.cb61304d.chunk.js:1:227368)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "93.0.4577.82",
    "major": "93"
  },
  "engine": {
    "name": "Blink",
    "version": "93.0.4577.82"
  },
  "os": {
    "name": "Windows",
    "version": "10"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

**Comment by justindomingue** [comment]
@dare912 do you have more repro steps for this?
