### ISSUE TITLE
Crash report: `Error: invalid BigNumber string (argument="value", value="-123", code=INVALID_ARGUMENT, version=bignumber/5.4.1)`

### ISSUE THREAD

**Issue by abdulsamijay** [Uniswap/interface#2432]
## URL
  
https://app.uniswap.org/#/pool/-123

## Error

```
Error: invalid BigNumber string (argument="value", value="+123", code=INVALID_ARGUMENT, version=bignumber/5.4.1)
```

## Stacktrace

```
Error: invalid BigNumber string (argument="value", value="+123", code=INVALID_ARGUMENT, version=bignumber/5.4.1)
    at e.value (https://app.uniswap.org/static/js/4.98825a2c.chunk.js:2:90460)
    at e.value (https://app.uniswap.org/static/js/4.98825a2c.chunk.js:2:90604)
    at e.value (https://app.uniswap.org/static/js/4.98825a2c.chunk.js:2:90683)
    at Function.value (https://app.uniswap.org/static/js/4.98825a2c.chunk.js:2:204001)
    at eA (https://app.uniswap.org/static/js/main.2b20d3db.chunk.js:1:614599)
    at ia (https://app.uniswap.org/static/js/4.98825a2c.chunk.js:2:1760143)
    at za (https://app.uniswap.org/static/js/4.98825a2c.chunk.js:2:1769710)
    at Vu (https://app.uniswap.org/static/js/4.98825a2c.chunk.js:2:1813592)
    at Sf (https://app.uniswap.org/static/js/4.98825a2c.chunk.js:2:1799775)
    at Tf (https://app.uniswap.org/static/js/4.98825a2c.chunk.js:2:1799703)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "90.0.4430.93",
    "major": "90"
  },
  "engine": {
    "name": "Blink",
    "version": "90.0.4430.93"
  },
  "os": {
    "name": "Linux",
    "version": "x86_64"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

**Comment by abdulsamijay** [comment]
Seems like app crashes if negative numbers or special characters are passed in as parameters.
