### ISSUE TITLE
Crash report: `Error: Invariant failed`

### ISSUE THREAD

**Issue by vaybabayin** [Uniswap/interface#2434]
## URL
  
https://app.uniswap.org/#/swap?outputCurrency=0x1f8a626883d7724dbd59ef51cbd4bf1cf2016d13

## `swap` state
    
```json
{
  "INPUT": {
    "currencyId": "0x1F8A626883d7724DBd59eF51CBD4BF1Cf2016D13"
  },
  "OUTPUT": {
    "currencyId": "ETH"
  },
  "independentField": "INPUT",
  "typedValue": "51172.660236285583729419",
  "recipient": null
}
```

## Error

```
Error: Invariant failed
```

## Stacktrace

```
Error: Invariant failed
    at https://app.uniswap.org/static/js/4.98825a2c.chunk.js:2:94799
    at t.sortsBefore (https://app.uniswap.org/static/js/4.98825a2c.chunk.js:2:81669)
    at https://app.uniswap.org/static/js/main.2b20d3db.chunk.js:1:185598
    at Array.map (<anonymous>)
    at https://app.uniswap.org/static/js/main.2b20d3db.chunk.js:1:185380
    at Object.Ta [as useMemo] (https://app.uniswap.org/static/js/4.98825a2c.chunk.js:2:1764876)
    at https://app.uniswap.org/static/js/4.98825a2c.chunk.js:2:1684348
    at Yd (https://app.uniswap.org/static/js/main.2b20d3db.chunk.js:1:185358)
    at https://app.uniswap.org/static/js/main.2b20d3db.chunk.js:1:187520
    at Kd (https://app.uniswap.org/static/js/main.2b20d3db.chunk.js:1:187941)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "93.0.4577.82",
    "major": "93"
  },
  "engine": {
    "name": "Blink",
    "version": "93.0.4577.82"
  },
  "os": {
    "name": "Windows",
    "version": "10"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

**Comment by willhennessy** [comment]
https://github.com/Uniswap/interface/issues/2103
