### ISSUE TITLE
Crash report: `TypeError: Cannot read properties of undefined (reading 'infoLink')`

### ISSUE THREAD

**Issue by codyo11** [Uniswap/interface#2480]
## URL
  
https://app.uniswap.org/#/swap

## `swap` state
    
```json
{
  "INPUT": {
    "currencyId": "ETH"
  },
  "OUTPUT": {
    "currencyId": null
  },
  "independentField": "INPUT",
  "typedValue": "",
  "recipient": null
}
```

## Error

```
TypeError: Cannot read properties of undefined (reading 'infoLink')
```

## Stacktrace

```
TypeError: Cannot read properties of undefined (reading 'infoLink')
    at vf (https://app.uniswap.org/static/js/main.f97146cb.chunk.js:1:338179)
    at ia (https://app.uniswap.org/static/js/35.ec3e0318.chunk.js:2:1189283)
    at za (https://app.uniswap.org/static/js/35.ec3e0318.chunk.js:2:1198850)
    at Wu (https://app.uniswap.org/static/js/35.ec3e0318.chunk.js:2:1242732)
    at Ss (https://app.uniswap.org/static/js/35.ec3e0318.chunk.js:2:1228915)
    at Es (https://app.uniswap.org/static/js/35.ec3e0318.chunk.js:2:1228843)
    at xs (https://app.uniswap.org/static/js/35.ec3e0318.chunk.js:2:1228706)
    at ys (https://app.uniswap.org/static/js/35.ec3e0318.chunk.js:2:1225672)
    at https://app.uniswap.org/static/js/35.ec3e0318.chunk.js:2:1175051
    at https://app.uniswap.org/static/js/35.ec3e0318.chunk.js:2:1252470
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "94.0.4606.61",
    "major": "94"
  },
  "engine": {
    "name": "Blink",
    "version": "94.0.4606.61"
  },
  "os": {
    "name": "Windows",
    "version": "10"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

**Comment by codyo11** [comment]
I lost $112 trying to send eth from my coinbase wallet to uniswap. please help.

**Comment by codyo11** [comment]
I lost $112 trying to send eth from my coinbase wallet to uniswap. please help.

**Comment by willhennessy** [comment]
Hello cody, how does the crash report relate to you sending eth from coinbase wallet?
