### ISSUE TITLE
Crash report: `NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.`

### ISSUE THREAD

**Issue by ddagsan** [Uniswap/interface#2481]
## URL
  
https://app.uniswap.org/#/add/v2/0xfbc9d9c558dfd69fcd0e2f4d0cd8baba0e9f0b33/0xe3563c3453ccb6b08ac02573827128c65c667864

## `mint` state
    
```json
{
  "independentField": "CURRENCY_A",
  "typedValue": "35",
  "otherTypedValue": "",
  "startPriceTypedValue": "",
  "leftRangeTypedValue": "",
  "rightRangeTypedValue": ""
}
```

## Error

```
NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
```

## Stacktrace

```
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at Ou (https://app.uniswap.org/static/js/35.ec3e0318.chunk.js:2:1220041)
    at Ps (https://app.uniswap.org/static/js/35.ec3e0318.chunk.js:2:1231853)
    at https://app.uniswap.org/static/js/35.ec3e0318.chunk.js:2:1252470
    at Vi (https://app.uniswap.org/static/js/35.ec3e0318.chunk.js:2:1174828)
    at As (https://app.uniswap.org/static/js/35.ec3e0318.chunk.js:2:1229811)
    at ys (https://app.uniswap.org/static/js/35.ec3e0318.chunk.js:2:1225897)
    at https://app.uniswap.org/static/js/35.ec3e0318.chunk.js:2:1175051
    at https://app.uniswap.org/static/js/35.ec3e0318.chunk.js:2:1252470
    at Vi (https://app.uniswap.org/static/js/35.ec3e0318.chunk.js:2:1174828)
    at Gi (https://app.uniswap.org/static/js/35.ec3e0318.chunk.js:2:1174996)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "94.0.4606.61",
    "major": "94"
  },
  "engine": {
    "name": "Blink",
    "version": "94.0.4606.61"
  },
  "os": {
    "name": "Windows",
    "version": "10"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

**Comment by willhennessy** [comment]
#2997 says "I was trying to convert eth to weth and received this message"
