### ISSUE TITLE
Crash report: `Error: Invariant failed`

### ISSUE THREAD

**Issue by playseeds** [Uniswap/interface#2482]
## URL
  
https://app.uniswap.org/#/swap

## `swap` state
    
```json
{
  "INPUT": {
    "currencyId": "0x61404D2D3f2100b124D6827D3F2DDf6233cd71C0"
  },
  "OUTPUT": {
    "currencyId": "ETH"
  },
  "independentField": "INPUT",
  "typedValue": "17000",
  "recipient": null
}
```

## Error

```
Error: Invariant failed
```

## Stacktrace

```
Error: Invariant failed
    at t.a (https://app.uniswap.org/static/js/35.ec3e0318.chunk.js:2:135533)
    at t.n.sortsBefore (https://app.uniswap.org/static/js/35.ec3e0318.chunk.js:2:68828)
    at https://app.uniswap.org/static/js/main.f97146cb.chunk.js:1:165752
    at Array.map (<anonymous>)
    at https://app.uniswap.org/static/js/main.f97146cb.chunk.js:1:165534
    at Object.Ta [as useMemo] (https://app.uniswap.org/static/js/35.ec3e0318.chunk.js:2:1194016)
    at t.useMemo (https://app.uniswap.org/static/js/35.ec3e0318.chunk.js:2:1129745)
    at ca (https://app.uniswap.org/static/js/main.f97146cb.chunk.js:1:165512)
    at https://app.uniswap.org/static/js/main.f97146cb.chunk.js:1:167674
    at ua (https://app.uniswap.org/static/js/main.f97146cb.chunk.js:1:168095)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "94.0.4606.61",
    "major": "94"
  },
  "engine": {
    "name": "Blink",
    "version": "94.0.4606.61"
  },
  "os": {
    "name": "Mac OS",
    "version": "10.15.7"
  },
  "device": {},
  "cpu": {}
}
```

**Comment by willhennessy** [comment]
Did this occur when you tried to switch networks?

I suspect this is the cause #2489

Please let me know, and re-open if that was not the case!

**Comment by playseeds** [comment]
Yes, it was when switching from Optimism back to mainnet I believe.
