### ISSUE TITLE
Crash report: `Error: Invariant failed`

### ISSUE THREAD

**Issue by fyang1024** [Uniswap/interface#2486]
## URL
  
https://app.uniswap.org/#/swap

## `swap` state
    
```json
{
  "INPUT": {
    "currencyId": "0x6DEA81C8171D0bA574754EF6F8b412F2Ed88c54D"
  },
  "OUTPUT": {
    "currencyId": "ETH"
  },
  "independentField": "INPUT",
  "typedValue": "27.809566924250993691",
  "recipient": null
}
```

## Error

```
Error: Invariant failed
```

## Stacktrace

```
Error: Invariant failed
    at t.a (https://app.uniswap.org/static/js/35.32b0dec8.chunk.js:2:135533)
    at t.n.sortsBefore (https://app.uniswap.org/static/js/35.32b0dec8.chunk.js:2:68828)
    at https://app.uniswap.org/static/js/main.eb487ab2.chunk.js:1:165752
    at Array.map (<anonymous>)
    at https://app.uniswap.org/static/js/main.eb487ab2.chunk.js:1:165534
    at Object.Ta [as useMemo] (https://app.uniswap.org/static/js/35.32b0dec8.chunk.js:2:1195265)
    at t.useMemo (https://app.uniswap.org/static/js/35.32b0dec8.chunk.js:2:1130994)
    at ca (https://app.uniswap.org/static/js/main.eb487ab2.chunk.js:1:165512)
    at https://app.uniswap.org/static/js/main.eb487ab2.chunk.js:1:167674
    at ua (https://app.uniswap.org/static/js/main.eb487ab2.chunk.js:1:168095)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "94.0.4606.61",
    "major": "94"
  },
  "engine": {
    "name": "Blink",
    "version": "94.0.4606.61"
  },
  "os": {
    "name": "Mac OS",
    "version": "10.15.7"
  },
  "device": {},
  "cpu": {}
}
```

**Comment by willhennessy** [comment]
Did this occur when you tried to switch networks?

I suspect this is the cause #2489

Please let me know, and re-open if that was not the case!
