### ISSUE TITLE
Crash report: `Error: Invariant failed`

### ISSUE THREAD

**Issue by old40404** [Uniswap/interface#2488]
## URL
  
https://app.uniswap.org/#/swap

## `swap` state
    
```json
{
  "INPUT": {
    "currencyId": "0xFd086bC7CD5C481DCC9C85ebE478A1C0b69FCbb9"
  },
  "OUTPUT": {
    "currencyId": "ETH"
  },
  "independentField": "INPUT",
  "typedValue": "20",
  "recipient": null
}
```

## Error

```
Error: Invariant failed
```

## Stacktrace

```
Error: Invariant failed
    at https://app.uniswap.org/static/js/35.ec3e0318.chunk.js:2:135533
    at t.sortsBefore (https://app.uniswap.org/static/js/35.ec3e0318.chunk.js:2:68828)
    at N (https://app.uniswap.org/static/js/35.ec3e0318.chunk.js:2:95506)
    at https://app.uniswap.org/static/js/main.f97146cb.chunk.js:1:165930
    at Array.map (<anonymous>)
    at https://app.uniswap.org/static/js/main.f97146cb.chunk.js:1:165886
    at Object.Ta [as useMemo] (https://app.uniswap.org/static/js/35.ec3e0318.chunk.js:2:1194016)
    at https://app.uniswap.org/static/js/35.ec3e0318.chunk.js:2:1129745
    at ca (https://app.uniswap.org/static/js/main.f97146cb.chunk.js:1:165849)
    at https://app.uniswap.org/static/js/main.f97146cb.chunk.js:1:167674
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "94.0.4606.61",
    "major": "94"
  },
  "engine": {
    "name": "Blink",
    "version": "94.0.4606.61"
  },
  "os": {
    "name": "Windows",
    "version": "10"
  },
  "device": {},
  "cpu": {}
}
```

**Comment by willhennessy** [comment]
Did this occur when you tried to switch networks?

I suspect this is the cause https://github.com/Uniswap/interface/issues/2489
