### ISSUE TITLE
Crash report: `Error: Invariant failed`

### ISSUE THREAD

**Issue by Rishabh-malhotraa** [Uniswap/interface#2493]
## URL
  
https://app.uniswap.org/#/swap?outputCurrency=0xc778417e063141139fce010982780140aa0cd5ab&theme=light&exactAmount=0.01&exactField=output

## `swap` state
    
```json
{
  "INPUT": {
    "currencyId": "ETH"
  },
  "OUTPUT": {
    "currencyId": "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
  },
  "independentField": "OUTPUT",
  "typedValue": "0.01",
  "recipient": null
}
```

## Error

```
Error: Invariant failed
```

## Stacktrace

```
Error: Invariant failed
    at t.a (https://app.uniswap.org/static/js/35.ec3e0318.chunk.js:2:135533)
    at t.n.sortsBefore (https://app.uniswap.org/static/js/35.ec3e0318.chunk.js:2:68828)
    at https://app.uniswap.org/static/js/main.f97146cb.chunk.js:1:165752
    at Array.map (<anonymous>)
    at https://app.uniswap.org/static/js/main.f97146cb.chunk.js:1:165534
    at Object.Ta [as useMemo] (https://app.uniswap.org/static/js/35.ec3e0318.chunk.js:2:1194016)
    at t.useMemo (https://app.uniswap.org/static/js/35.ec3e0318.chunk.js:2:1129745)
    at ca (https://app.uniswap.org/static/js/main.f97146cb.chunk.js:1:165512)
    at https://app.uniswap.org/static/js/main.f97146cb.chunk.js:1:167674
    at ua (https://app.uniswap.org/static/js/main.f97146cb.chunk.js:1:168095)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "94.0.4606.61",
    "major": "94"
  },
  "engine": {
    "name": "Blink",
    "version": "94.0.4606.61"
  },
  "os": {
    "name": "Windows",
    "version": "10"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

**Comment by willhennessy** [comment]
https://github.com/Uniswap/interface/issues/2677
