### ISSUE TITLE
Crash report: `Error: Invariant failed`

### ISSUE THREAD

**Issue by swene-dev** [Uniswap/interface#2505]
## URL
  
https://app.uniswap.org/#/swap

## `swap` state
    
```json
{
  "INPUT": {
    "currencyId": "ETH"
  },
  "OUTPUT": {
    "currencyId": "0x25a1DE1C3eE658FE034B8914a1D8d34110423AF8"
  },
  "independentField": "OUTPUT",
  "typedValue": "0.000000000000000001",
  "recipient": null
}
```

## Error

```
Error: Invariant failed
```

## Stacktrace

```
Error: Invariant failed
    at https://app.uniswap.org/static/js/35.ec3e0318.chunk.js:2:135533
    at t.sortsBefore (https://app.uniswap.org/static/js/35.ec3e0318.chunk.js:2:68828)
    at https://app.uniswap.org/static/js/main.f97146cb.chunk.js:1:165752
    at Array.map (<anonymous>)
    at https://app.uniswap.org/static/js/main.f97146cb.chunk.js:1:165534
    at Object.Ta [as useMemo] (https://app.uniswap.org/static/js/35.ec3e0318.chunk.js:2:1194016)
    at https://app.uniswap.org/static/js/35.ec3e0318.chunk.js:2:1129745
    at ca (https://app.uniswap.org/static/js/main.f97146cb.chunk.js:1:165512)
    at https://app.uniswap.org/static/js/main.f97146cb.chunk.js:1:167674
    at ua (https://app.uniswap.org/static/js/main.f97146cb.chunk.js:1:168095)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "94.0.4606.61",
    "major": "94"
  },
  "engine": {
    "name": "Blink",
    "version": "94.0.4606.61"
  },
  "os": {
    "name": "Mac OS",
    "version": "10.15.7"
  },
  "device": {},
  "cpu": {}
}
```

**Comment by willhennessy** [comment]
https://github.com/Uniswap/interface/issues/2677
