### ISSUE TITLE
Crash report: `Error: No V2 factory address on this chain`

### ISSUE THREAD

**Issue by MrKamalRizal** [Uniswap/interface#2522]
## URL
  
https://app.uniswap.org/#/pool/v2

## Error

```
Error: No V2 factory address on this chain
```

## Stacktrace

```
Error: No V2 factory address on this chain
    at na (https://app.uniswap.org/static/js/main.f15af8e2.chunk.js:1:164537)
    at https://app.uniswap.org/static/js/main.f15af8e2.chunk.js:1:665381
    at Array.map (<anonymous>)
    at https://app.uniswap.org/static/js/main.f15af8e2.chunk.js:1:665342
    at Object.Aa [as useMemo] (https://app.uniswap.org/static/js/35.038aa360.chunk.js:2:1194683)
    at t.useMemo (https://app.uniswap.org/static/js/35.038aa360.chunk.js:2:1129703)
    at yA (https://app.uniswap.org/static/js/main.f15af8e2.chunk.js:1:665320)
    at ua (https://app.uniswap.org/static/js/35.038aa360.chunk.js:2:1189950)
    at Ha (https://app.uniswap.org/static/js/35.038aa360.chunk.js:2:1199517)
    at Ku (https://app.uniswap.org/static/js/35.038aa360.chunk.js:2:1243241)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "94.0.4606.71",
    "major": "94"
  },
  "engine": {
    "name": "Blink",
    "version": "94.0.4606.71"
  },
  "os": {
    "name": "Windows",
    "version": "10"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

**Comment by willhennessy** [comment]
+1 thanks uniyj!
