### ISSUE TITLE
Crash report: `Error: Invariant failed`

### ISSUE THREAD

**Issue by saxis** [Uniswap/interface#2534]
## URL
  
https://uni.zksync.io/#/swap

## `swap` state
    
```json
{
  "INPUT": {
    "currencyId": "0x4da8d0795830f75BE471F072a034d42c369B5d0A"
  },
  "OUTPUT": {
    "currencyId": "0x7457fc3f89ac99837d44f60B7860691fb2f09Bf5"
  },
  "independentField": "INPUT",
  "typedValue": "30",
  "recipient": null
}
```

## Error

```
Error: Invariant failed
```

## Stacktrace

```
Error: Invariant failed
    at t.a (https://uni.zksync.io/static/js/2.b4d56b63.chunk.js:2:119575)
    at t.r.add (https://uni.zksync.io/static/js/2.b4d56b63.chunk.js:2:111782)
    at ib (https://uni.zksync.io/static/js/main.0382a84d.chunk.js:1:339315)
    at ia (https://uni.zksync.io/static/js/2.b4d56b63.chunk.js:2:1287874)
    at za (https://uni.zksync.io/static/js/2.b4d56b63.chunk.js:2:1297441)
    at Vu (https://uni.zksync.io/static/js/2.b4d56b63.chunk.js:2:1341323)
    at xs (https://uni.zksync.io/static/js/2.b4d56b63.chunk.js:2:1327506)
    at Ss (https://uni.zksync.io/static/js/2.b4d56b63.chunk.js:2:1327434)
    at As (https://uni.zksync.io/static/js/2.b4d56b63.chunk.js:2:1327297)
    at vs (https://uni.zksync.io/static/js/2.b4d56b63.chunk.js:2:1324263)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "94.0.4606.71",
    "major": "94"
  },
  "engine": {
    "name": "Blink",
    "version": "94.0.4606.71"
  },
  "os": {
    "name": "Mac OS",
    "version": "10.15.7"
  },
  "device": {},
  "cpu": {}
}
```

**Comment by justindomingue** [comment]
#2529
