### ISSUE TITLE
Crash report: `SecurityError: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.`

### ISSUE THREAD

**Issue by vectorbased1** [Uniswap/interface#2645]
Simply reporting the issue I'm facing on Opensea - converting ETH to WETH to 'Make an Offer'.
Thank you.

## URL
  
https://app.uniswap.org/#/swap?outputCurrency=0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2&theme=light&exactAmount=454.9548&exactField=output

## `swap` state
    
```json
{
  "INPUT": {
    "currencyId": null
  },
  "OUTPUT": {
    "currencyId": "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
  },
  "independentField": "OUTPUT",
  "typedValue": "454.9548",
  "recipient": null
}
```

## Error

```
SecurityError: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
```

## Stacktrace

```
Error: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at t.getCachedUrl (https://app.uniswap.org/static/js/35.5505b0d5.chunk.js:2:826379)
    at https://app.uniswap.org/static/js/35.5505b0d5.chunk.js:2:827308
    at Fs (https://app.uniswap.org/static/js/35.5505b0d5.chunk.js:2:1237126)
    at t.unstable_runWithPriority (https://app.uniswap.org/static/js/35.5505b0d5.chunk.js:2:1254905)
    at Gi (https://app.uniswap.org/static/js/35.5505b0d5.chunk.js:2:1177445)
    at Rs (https://app.uniswap.org/static/js/35.5505b0d5.chunk.js:2:1236587)
    at https://app.uniswap.org/static/js/35.5505b0d5.chunk.js:2:1236498
    at L (https://app.uniswap.org/static/js/35.5505b0d5.chunk.js:2:1253964)
    at MessagePort.k.port1.onmessage (https://app.uniswap.org/static/js/35.5505b0d5.chunk.js:2:1252686)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "94.0.4606.81",
    "major": "94"
  },
  "engine": {
    "name": "Blink",
    "version": "94.0.4606.81"
  },
  "os": {
    "name": "Mac OS",
    "version": "10.15.7"
  },
  "device": {},
  "cpu": {}
}
```

**Comment by vectorbased1** [comment]
Thanks for checking this issue.

I'm still attempting to 'make an offer', yet the system reports
insufficient funds.
*I'm offering 0.13ETH and have .2194ETH available.*

Re:
https://opensea.io/assets/0x335eeef8e93a7a757d9e7912044d9cd264e2b2d8/2757

Am I doing something wrong?
Please see attached screenshots.

Thanks for your help.
Rob

[image: offer_1.png][image: offer_2.png][image: offer_3.png][image:
offer_4.png]

**Comment by zzmp** [comment]
Cannot reproduce.
We only access localstorage using redux-localstorage-simple, which reports the error as a warning, and should not cause a crash.
