### ISSUE TITLE
Crash report: `Error: Invariant failed`

### ISSUE THREAD

**Issue by platocrat** [Uniswap/interface#2668]
## URL
  
https://app.uniswap.org/#/swap

## `swap` state
    
```json
{
  "INPUT": {
    "currencyId": "ETH"
  },
  "OUTPUT": {
    "currencyId": "0xDA10009cBd5D07dd0CeCc66161FC93D7c9000da1"
  },
  "independentField": "INPUT",
  "typedValue": "0.01",
  "recipient": null
}
```

## Error

```
Error: Invariant failed
```

## Stacktrace

```
Error: Invariant failed
    at t.a (https://app.uniswap.org/static/js/35.d44dca6f.chunk.js:2:135542)
    at t.n.sortsBefore (https://app.uniswap.org/static/js/35.d44dca6f.chunk.js:2:68832)
    at https://app.uniswap.org/static/js/main.fd25a520.chunk.js:1:166474
    at Array.map (<anonymous>)
    at https://app.uniswap.org/static/js/main.fd25a520.chunk.js:1:166256
    at Object.Aa [as useMemo] (https://app.uniswap.org/static/js/35.d44dca6f.chunk.js:2:1196614)
    at t.useMemo (https://app.uniswap.org/static/js/35.d44dca6f.chunk.js:2:1131634)
    at ua (https://app.uniswap.org/static/js/main.fd25a520.chunk.js:1:166234)
    at https://app.uniswap.org/static/js/main.fd25a520.chunk.js:1:168397
    at ha (https://app.uniswap.org/static/js/main.fd25a520.chunk.js:1:168818)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "94.0.4606.81",
    "major": "94"
  },
  "engine": {
    "name": "Blink",
    "version": "94.0.4606.81"
  },
  "os": {
    "name": "Mac OS",
    "version": "10.15.7"
  },
  "device": {},
  "cpu": {}
}
```

**Comment by willhennessy** [comment]
thanks platocrat, duped with https://github.com/Uniswap/interface/issues/2668
