### ISSUE TITLE
Crash report: `SecurityError: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.`

### ISSUE THREAD

**Issue by DaveBRB** [Uniswap/interface#2698]
## URL
  
https://app.uniswap.org/#/swap?outputCurrency=0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2&theme=light&exactAmount=918.35163&exactField=output

## `swap` state
    
```json
{
  "INPUT": {
    "currencyId": null
  },
  "OUTPUT": {
    "currencyId": "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
  },
  "independentField": "OUTPUT",
  "typedValue": "918.35163",
  "recipient": null
}
```

## Error

```
SecurityError: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
```

## Stacktrace

```
Error: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at t.getCachedUrl (https://app.uniswap.org/static/js/35.7425d7b7.chunk.js:2:984273)
    at https://app.uniswap.org/static/js/35.7425d7b7.chunk.js:2:985202
    at Fs (https://app.uniswap.org/static/js/35.7425d7b7.chunk.js:2:1393435)
    at t.unstable_runWithPriority (https://app.uniswap.org/static/js/35.7425d7b7.chunk.js:2:1411214)
    at Gi (https://app.uniswap.org/static/js/35.7425d7b7.chunk.js:2:1333754)
    at Rs (https://app.uniswap.org/static/js/35.7425d7b7.chunk.js:2:1392896)
    at https://app.uniswap.org/static/js/35.7425d7b7.chunk.js:2:1392807
    at L (https://app.uniswap.org/static/js/35.7425d7b7.chunk.js:2:1410273)
    at MessagePort.k.port1.onmessage (https://app.uniswap.org/static/js/35.7425d7b7.chunk.js:2:1408995)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "95.0.4638.54",
    "major": "95"
  },
  "engine": {
    "name": "Blink",
    "version": "95.0.4638.54"
  },
  "os": {
    "name": "Windows",
    "version": "10"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

**Comment by willhennessy** [comment]
thanks dupe of https://github.com/Uniswap/interface/issues/2698
