### ISSUE TITLE
Crash report: `TypeError: Cannot read properties of undefined (reading 'infoLink')`

### ISSUE THREAD

**Issue by alexkolk** [Uniswap/interface#2715]
## URL
  
https://app.uniswap.org/#/swap

## `swap` state
    
```json
{
  "INPUT": {
    "currencyId": "ETH"
  },
  "OUTPUT": {
    "currencyId": null
  },
  "independentField": "INPUT",
  "typedValue": "",
  "recipient": null
}
```

## Error

```
TypeError: Cannot read properties of undefined (reading 'infoLink')
```

## Stacktrace

```
TypeError: Cannot read properties of undefined (reading 'infoLink')
    at Af (https://app.uniswap.org/static/js/main.8a72fbb9.chunk.js:1:338415)
    at ua (https://app.uniswap.org/static/js/35.d35d34a0.chunk.js:2:1348185)
    at Va (https://app.uniswap.org/static/js/35.d35d34a0.chunk.js:2:1357752)
    at $u (https://app.uniswap.org/static/js/35.d35d34a0.chunk.js:2:1401476)
    at Cs (https://app.uniswap.org/static/js/35.d35d34a0.chunk.js:2:1387726)
    at js (https://app.uniswap.org/static/js/35.d35d34a0.chunk.js:2:1387654)
    at Ss (https://app.uniswap.org/static/js/35.d35d34a0.chunk.js:2:1387517)
    at bs (https://app.uniswap.org/static/js/35.d35d34a0.chunk.js:2:1384483)
    at https://app.uniswap.org/static/js/35.d35d34a0.chunk.js:2:1333977
    at https://app.uniswap.org/static/js/35.d35d34a0.chunk.js:2:1411214
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "95.0.4638.54",
    "major": "95"
  },
  "engine": {
    "name": "Blink",
    "version": "95.0.4638.54"
  },
  "os": {
    "name": "Mac OS",
    "version": "10.15.7"
  },
  "device": {},
  "cpu": {}
}
```

**Comment by willhennessy** [comment]
https://github.com/Uniswap/interface/issues/2477
