### ISSUE TITLE
Crash report: `Error: No V2 factory address on this chain`

### ISSUE THREAD

**Issue by hamakago** [Uniswap/interface#2718]
## URL
  
https://app.uniswap.org/#/pool/v2

## Error

```
Error: No V2 factory address on this chain
```

## Stacktrace

```
Error: No V2 factory address on this chain
    at ra (https://app.uniswap.org/static/js/main.8a72fbb9.chunk.js:1:166494)
    at https://app.uniswap.org/static/js/main.8a72fbb9.chunk.js:1:678142
    at Array.map (<anonymous>)
    at https://app.uniswap.org/static/js/main.8a72fbb9.chunk.js:1:678103
    at Object.Aa [as useMemo] (https://app.uniswap.org/static/js/35.d35d34a0.chunk.js:2:1352918)
    at https://app.uniswap.org/static/js/35.d35d34a0.chunk.js:2:1287938
    at $A (https://app.uniswap.org/static/js/main.8a72fbb9.chunk.js:1:678081)
    at ua (https://app.uniswap.org/static/js/35.d35d34a0.chunk.js:2:1348185)
    at Va (https://app.uniswap.org/static/js/35.d35d34a0.chunk.js:2:1357752)
    at $u (https://app.uniswap.org/static/js/35.d35d34a0.chunk.js:2:1401476)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "95.0.4638.54",
    "major": "95"
  },
  "engine": {
    "name": "Blink",
    "version": "95.0.4638.54"
  },
  "os": {
    "name": "Windows",
    "version": "10"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

**Comment by willhennessy** [comment]
Hi hamakago, uniswap v2 is only available on L1 ethereum and not on optimism, arbitrum, or other chains
