### ISSUE TITLE
Crash report: `Error: invalid BigNumber string (argument="value", value="v1", code=INVALID_ARGUMENT, version=bignumber/5.4.1)`

### ISSUE THREAD

**Issue by mhairimca** [Uniswap/interface#2729]
## URL
  
https://app.uniswap.org/#/pool/v1

## Error

```
Error: invalid BigNumber string (argument="value", value="v1", code=INVALID_ARGUMENT, version=bignumber/5.4.1)
```

## Stacktrace

```
Error: invalid BigNumber string (argument="value", value="v1", code=INVALID_ARGUMENT, version=bignumber/5.4.1)
    at e.value (https://app.uniswap.org/static/js/35.d35d34a0.chunk.js:2:83309)
    at e.value (https://app.uniswap.org/static/js/35.d35d34a0.chunk.js:2:83453)
    at e.value (https://app.uniswap.org/static/js/35.d35d34a0.chunk.js:2:83532)
    at Function.value (https://app.uniswap.org/static/js/35.d35d34a0.chunk.js:2:265518)
    at VA (https://app.uniswap.org/static/js/main.8a72fbb9.chunk.js:1:662834)
    at ua (https://app.uniswap.org/static/js/35.d35d34a0.chunk.js:2:1348185)
    at $u (https://app.uniswap.org/static/js/35.d35d34a0.chunk.js:2:1400485)
    at Cs (https://app.uniswap.org/static/js/35.d35d34a0.chunk.js:2:1387726)
    at js (https://app.uniswap.org/static/js/35.d35d34a0.chunk.js:2:1387654)
    at Ss (https://app.uniswap.org/static/js/35.d35d34a0.chunk.js:2:1387517)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "95.0.4638.54",
    "major": "95"
  },
  "engine": {
    "name": "Blink",
    "version": "95.0.4638.54"
  },
  "os": {
    "name": "Windows",
    "version": "10"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}

**Comment by willhennessy** [comment]
https://github.com/Uniswap/interface/issues/3171
