### ISSUE TITLE
Crash report: `SecurityError: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.`

### ISSUE THREAD

**Issue by bep20** [Uniswap/interface#2733]
## URL
  
https://app.uniswap.org/#/swap

## `swap` state
    
```json
{
  "INPUT": {
    "currencyId": "ETH"
  },
  "OUTPUT": {
    "currencyId": null
  },
  "independentField": "INPUT",
  "typedValue": "",
  "recipient": null
}
```

## Error

```
SecurityError: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
```

## Stacktrace

```
Error: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at t.getCachedUrl (https://app.uniswap.org/static/js/35.d35d34a0.chunk.js:2:984273)
    at https://app.uniswap.org/static/js/35.d35d34a0.chunk.js:2:985202
    at Fs (https://app.uniswap.org/static/js/35.d35d34a0.chunk.js:2:1393435)
    at t.unstable_runWithPriority (https://app.uniswap.org/static/js/35.d35d34a0.chunk.js:2:1411214)
    at Gi (https://app.uniswap.org/static/js/35.d35d34a0.chunk.js:2:1333754)
    at Rs (https://app.uniswap.org/static/js/35.d35d34a0.chunk.js:2:1392896)
    at https://app.uniswap.org/static/js/35.d35d34a0.chunk.js:2:1392807
    at L (https://app.uniswap.org/static/js/35.d35d34a0.chunk.js:2:1410273)
    at MessagePort.k.port1.onmessage (https://app.uniswap.org/static/js/35.d35d34a0.chunk.js:2:1408995)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "95.0.4638.69",
    "major": "95"
  },
  "engine": {
    "name": "Blink",
    "version": "95.0.4638.69"
  },
  "os": {
    "name": "Windows",
    "version": "8.1"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

**Comment by willhennessy** [comment]
https://github.com/Uniswap/interface/issues/2801
