### ISSUE TITLE
Crash report: `Error: Unsupported chain ID`

### ISSUE THREAD

**Issue by bellsinclair** [Uniswap/interface#2749]
## URL
  
https://app.uniswap.org/#/swap?theme=dark&use=v2&slippage=4.00&inputCurrency=ETH&outputCurrency=0x239dc02a28a0774738463e06245544a72745d5c5

## `swap` state
    
```json
{
  "INPUT": {
    "currencyId": "ETH"
  },
  "OUTPUT": {
    "currencyId": "0x239Dc02A28a0774738463E06245544a72745d5c5"
  },
  "independentField": "INPUT",
  "typedValue": "0.000821",
  "recipient": null
}
```

## Error

```
Error: Unsupported chain ID
```

## Stacktrace

```
Error: Unsupported chain ID
    at n.get (https://app.uniswap.org/static/js/main.da1bd560.chunk.js:1:145646)
    at Wi (https://app.uniswap.org/static/js/main.da1bd560.chunk.js:1:147696)
    at mo (https://app.uniswap.org/static/js/main.da1bd560.chunk.js:1:154006)
    at Oo (https://app.uniswap.org/static/js/main.da1bd560.chunk.js:1:154634)
    at Oc (https://app.uniswap.org/static/js/main.da1bd560.chunk.js:1:186914)
    at vS (https://app.uniswap.org/static/js/main.da1bd560.chunk.js:1:747529)
    at ua (https://app.uniswap.org/static/js/35.8cc8582a.chunk.js:2:1348185)
    at Va (https://app.uniswap.org/static/js/35.8cc8582a.chunk.js:2:1357752)
    at $u (https://app.uniswap.org/static/js/35.8cc8582a.chunk.js:2:1401476)
    at Cs (https://app.uniswap.org/static/js/35.8cc8582a.chunk.js:2:1387726)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "95.0.4638.69",
    "major": "95"
  },
  "engine": {
    "name": "Blink",
    "version": "95.0.4638.69"
  },
  "os": {
    "name": "Windows",
    "version": "10"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

**Comment by willhennessy** [comment]
https://github.com/Uniswap/interface/issues/2772

**Comment by willhennessy** [comment]
Interesting we received a new error report on Jan 2 https://github.com/Uniswap/interface/issues/3063. I thought this was fixed by @tinaszheng 's PR https://github.com/Uniswap/interface/pull/3024.
