### ISSUE TITLE
Crash report: `TypeError: Cannot read properties of undefined (reading 'infoLink')`

### ISSUE THREAD

**Issue by WETH1** [Uniswap/interface#2755]
## URL
  
https://app.uniswap.org/#/swap

## `swap` state
    
```json
{
  "INPUT": {
    "currencyId": "ETH"
  },
  "OUTPUT": {
    "currencyId": null
  },
  "independentField": "INPUT",
  "typedValue": "",
  "recipient": null
}
```

## Error

```
TypeError: Cannot read properties of undefined (reading 'infoLink')
```

## Stacktrace

```
TypeError: Cannot read properties of undefined (reading 'infoLink')
    at Af (https://app.uniswap.org/static/js/main.c1ec46c4.chunk.js:1:338810)
    at ua (https://app.uniswap.org/static/js/35.8cc8582a.chunk.js:2:1348185)
    at Va (https://app.uniswap.org/static/js/35.8cc8582a.chunk.js:2:1357752)
    at $u (https://app.uniswap.org/static/js/35.8cc8582a.chunk.js:2:1401476)
    at Cs (https://app.uniswap.org/static/js/35.8cc8582a.chunk.js:2:1387726)
    at js (https://app.uniswap.org/static/js/35.8cc8582a.chunk.js:2:1387654)
    at Ss (https://app.uniswap.org/static/js/35.8cc8582a.chunk.js:2:1387517)
    at bs (https://app.uniswap.org/static/js/35.8cc8582a.chunk.js:2:1384483)
    at https://app.uniswap.org/static/js/35.8cc8582a.chunk.js:2:1333977
    at https://app.uniswap.org/static/js/35.8cc8582a.chunk.js:2:1411214
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "95.0.4638.54",
    "major": "95"
  },
  "engine": {
    "name": "Blink",
    "version": "95.0.4638.54"
  },
  "os": {
    "name": "Windows",
    "version": "10"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

**Comment by willhennessy** [comment]
https://github.com/Uniswap/interface/issues/2755
