### ISSUE TITLE
Crash report: `Error: deferred error during ABI decoding triggered accessing index 8`

### ISSUE THREAD

**Issue by must479** [Uniswap/interface#2760]
## URL
  
https://bafybeifaefbircf2girgzqnoomm4zur6buhjszchgklrukt56lh4hrmedy.ipfs.cf-ipfs.com/#/vote

## Error

```
Error: deferred error during ABI decoding triggered accessing index 8
```

## Stacktrace

```
Error: deferred error during ABI decoding triggered accessing index 8
    at O (https://bafybeifaefbircf2girgzqnoomm4zur6buhjszchgklrukt56lh4hrmedy.ipfs.cf-ipfs.com/static/js/4.0d41cb94.chunk.js:2:603911)
    at Array.get (https://bafybeifaefbircf2girgzqnoomm4zur6buhjszchgklrukt56lh4hrmedy.ipfs.cf-ipfs.com/static/js/4.0d41cb94.chunk.js:2:611941)
    at m (https://bafybeifaefbircf2girgzqnoomm4zur6buhjszchgklrukt56lh4hrmedy.ipfs.cf-ipfs.com/static/js/4.0d41cb94.chunk.js:2:80160)
    at b (https://bafybeifaefbircf2girgzqnoomm4zur6buhjszchgklrukt56lh4hrmedy.ipfs.cf-ipfs.com/static/js/4.0d41cb94.chunk.js:2:80279)
    at v (https://bafybeifaefbircf2girgzqnoomm4zur6buhjszchgklrukt56lh4hrmedy.ipfs.cf-ipfs.com/static/js/4.0d41cb94.chunk.js:2:80559)
    at new e (https://bafybeifaefbircf2girgzqnoomm4zur6buhjszchgklrukt56lh4hrmedy.ipfs.cf-ipfs.com/static/js/4.0d41cb94.chunk.js:2:80627)
    at n.<anonymous> (https://bafybeifaefbircf2girgzqnoomm4zur6buhjszchgklrukt56lh4hrmedy.ipfs.cf-ipfs.com/static/js/4.0d41cb94.chunk.js:2:159425)
    at new n (https://bafybeifaefbircf2girgzqnoomm4zur6buhjszchgklrukt56lh4hrmedy.ipfs.cf-ipfs.com/static/js/4.0d41cb94.chunk.js:2:603314)
    at e.value (https://bafybeifaefbircf2girgzqnoomm4zur6buhjszchgklrukt56lh4hrmedy.ipfs.cf-ipfs.com/static/js/4.0d41cb94.chunk.js:2:612412)
    at https://bafybeifaefbircf2girgzqnoomm4zur6buhjszchgklrukt56lh4hrmedy.ipfs.cf-ipfs.com/static/js/main.e5e7a8b3.chunk.js:1:443293
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "95.0.4638.69",
    "major": "95"
  },
  "engine": {
    "name": "Blink",
    "version": "95.0.4638.69"
  },
  "os": {
    "name": "Windows",
    "version": "7"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

**Comment by NoahZinsmeister** [comment]
this is fixed
