### ISSUE TITLE
Crash report: `Error: Invariant failed`

### ISSUE THREAD

**Issue by amitesh03** [Uniswap/interface#2761]
## URL
  
https://app.uniswap.org/#/swap

## `swap` state
    
```json
{
  "INPUT": {
    "currencyId": "0x0644581154014DC453063730f059e9574C0F7401"
  },
  "OUTPUT": {
    "currencyId": "0x6e3D44BFEc5387BEedbd55386705b185e830925E"
  },
  "independentField": "INPUT",
  "typedValue": "900000000000000000000000",
  "recipient": null
}
```

## Error

```
Error: Invariant failed
```

## Stacktrace

```
Error: Invariant failed
    at https://app.uniswap.org/static/js/35.8cc8582a.chunk.js:2:147294
    at new t (https://app.uniswap.org/static/js/35.8cc8582a.chunk.js:2:65208)
    at Function.fromFractionalAmount (https://app.uniswap.org/static/js/35.8cc8582a.chunk.js:2:65401)
    at t.quote (https://app.uniswap.org/static/js/35.8cc8582a.chunk.js:2:68406)
    at e.get (https://app.uniswap.org/static/js/35.8cc8582a.chunk.js:2:139000)
    at https://app.uniswap.org/static/js/main.da1bd560.chunk.js:1:752463
    at Object.Aa [as useMemo] (https://app.uniswap.org/static/js/35.8cc8582a.chunk.js:2:1352918)
    at https://app.uniswap.org/static/js/35.8cc8582a.chunk.js:2:1287938
    at vS (https://app.uniswap.org/static/js/main.da1bd560.chunk.js:1:752414)
    at ua (https://app.uniswap.org/static/js/35.8cc8582a.chunk.js:2:1348185)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "95.0.4638.69",
    "major": "95"
  },
  "engine": {
    "name": "Blink",
    "version": "95.0.4638.69"
  },
  "os": {
    "name": "Windows",
    "version": "10"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

**Comment by willhennessy** [comment]
https://github.com/Uniswap/interface/issues/2677
