### ISSUE TITLE
Crash report: `TypeError: Cannot read properties of undefined (reading 'infoLink')`

### ISSUE THREAD

**Issue by cmuriel5710** [Uniswap/interface#2782]
## URL
  
https://app.uniswap.org/#/swap

## `swap` state
    
```json
{
  "INPUT": {
    "currencyId": "ETH"
  },
  "OUTPUT": {
    "currencyId": null
  },
  "independentField": "INPUT",
  "typedValue": "",
  "recipient": null
}
```

## Error

```
TypeError: Cannot read properties of undefined (reading 'infoLink')
```

## Stacktrace

```
TypeError: Cannot read properties of undefined (reading 'infoLink')
    at kf (https://app.uniswap.org/static/js/main.76ce51ac.chunk.js:1:338032)
    at ua (https://app.uniswap.org/static/js/35.fc333caa.chunk.js:2:1361099)
    at Va (https://app.uniswap.org/static/js/35.fc333caa.chunk.js:2:1370666)
    at $u (https://app.uniswap.org/static/js/35.fc333caa.chunk.js:2:1414390)
    at Cs (https://app.uniswap.org/static/js/35.fc333caa.chunk.js:2:1400640)
    at js (https://app.uniswap.org/static/js/35.fc333caa.chunk.js:2:1400568)
    at Ss (https://app.uniswap.org/static/js/35.fc333caa.chunk.js:2:1400431)
    at bs (https://app.uniswap.org/static/js/35.fc333caa.chunk.js:2:1397397)
    at https://app.uniswap.org/static/js/35.fc333caa.chunk.js:2:1346891
    at https://app.uniswap.org/static/js/35.fc333caa.chunk.js:2:1424128
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "95.0.4638.69",
    "major": "95"
  },
  "engine": {
    "name": "Blink",
    "version": "95.0.4638.69"
  },
  "os": {
    "name": "Windows",
    "version": "10"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

**Comment by cmuriel5710** [comment]
Not sure what the problem is

**Comment by CombatWombat15** [comment]
same just started today

**Comment by willhennessy** [comment]
there is a similar report from 7 days ago in #2758

**Comment by V3L0Z** [comment]
thanks for correcting this issue @willhennessy

**Comment by NoahZinsmeister** [comment]
related:
#2830
#2798
#2782
