### ISSUE TITLE
Crash report: `TypeError: Cannot read properties of undefined (reading 'infoLink')`

### ISSUE THREAD

**Issue by CombatWombat15** [Uniswap/interface#2788]
## URL
  
https://app.uniswap.org/#/swap

## `swap` state
    
```json
{
  "INPUT": {
    "currencyId": "ETH"
  },
  "OUTPUT": {
    "currencyId": null
  },
  "independentField": "INPUT",
  "typedValue": "",
  "recipient": null
}
```

## Error

```
TypeError: Cannot read properties of undefined (reading 'infoLink')
```

## Stacktrace

```
TypeError: Cannot read properties of undefined (reading 'infoLink')
    at Cf (https://app.uniswap.org/static/js/main.235752c4.chunk.js:1:337977)
    at ua (https://app.uniswap.org/static/js/35.b241a31f.chunk.js:2:1361138)
    at Va (https://app.uniswap.org/static/js/35.b241a31f.chunk.js:2:1370705)
    at $u (https://app.uniswap.org/static/js/35.b241a31f.chunk.js:2:1414429)
    at Cs (https://app.uniswap.org/static/js/35.b241a31f.chunk.js:2:1400679)
    at js (https://app.uniswap.org/static/js/35.b241a31f.chunk.js:2:1400607)
    at Ss (https://app.uniswap.org/static/js/35.b241a31f.chunk.js:2:1400470)
    at bs (https://app.uniswap.org/static/js/35.b241a31f.chunk.js:2:1397436)
    at https://app.uniswap.org/static/js/35.b241a31f.chunk.js:2:1346930
    at https://app.uniswap.org/static/js/35.b241a31f.chunk.js:2:1424167
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "95.0.4638.69",
    "major": "95"
  },
  "engine": {
    "name": "Blink",
    "version": "95.0.4638.69"
  },
  "os": {
    "name": "Mac OS",
    "version": "10.12.6"
  },
  "device": {},
  "cpu": {}
}
```

**Comment by CombatWombat15** [comment]
Any ideas why this is happening?

**Comment by willhennessy** [comment]
https://github.com/Uniswap/interface/issues/2782
