### ISSUE TITLE
Crash report: `Error: Invariant failed`  when entering the amount of swap tokens, this error occurs

### ISSUE THREAD

**Issue by smilby** [Uniswap/interface#2793]
## URL
  
https://uni.gearbox.fi/#/swap

## `swap` state
    
```json
{
  "INPUT": {
    "currencyId": "ETH"
  },
  "OUTPUT": {
    "currencyId": "0x1f9840a85d5aF5bf1D1762F925BDADdC4201F984"
  },
  "independentField": "OUTPUT",
  "typedValue": "1",
  "recipient": null
}
```

## Error

```
Error: Invariant failed
```

## Stacktrace

```
Error: Invariant failed
    at t.default (https://uni.gearbox.fi/static/js/3.a510ef99.chunk.js:2:100984)
    at t.r.sortsBefore (https://uni.gearbox.fi/static/js/3.a510ef99.chunk.js:2:88655)
    at https://uni.gearbox.fi/static/js/main.c5c82377.chunk.js:1:133710
    at Array.map (<anonymous>)
    at https://uni.gearbox.fi/static/js/main.c5c82377.chunk.js:1:133492
    at Object.To [as useMemo] (https://uni.gearbox.fi/static/js/3.a510ef99.chunk.js:2:1678638)
    at t.useMemo (https://uni.gearbox.fi/static/js/3.a510ef99.chunk.js:2:1598110)
    at ud (https://uni.gearbox.fi/static/js/main.c5c82377.chunk.js:1:133470)
    at https://uni.gearbox.fi/static/js/main.c5c82377.chunk.js:1:135632
    at fd (https://uni.gearbox.fi/static/js/main.c5c82377.chunk.js:1:136053)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "95.0.4638.69",
    "major": "95"
  },
  "engine": {
    "name": "Blink",
    "version": "95.0.4638.69"
  },
  "os": {
    "name": "Windows",
    "version": "10"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

**Comment by willhennessy** [comment]
hi, gearbox is built by a different team please follow up with them
