### ISSUE TITLE
Crash report: `SecurityError: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.`

### ISSUE THREAD

**Issue by Baronak** [Uniswap/interface#2794]
## URL
  
https://app.uniswap.org/#/swap?outputCurrency=0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2&theme=light&exactAmount=229.628&exactField=output

## `swap` state
    
```json
{
  "INPUT": {
    "currencyId": null
  },
  "OUTPUT": {
    "currencyId": "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
  },
  "independentField": "OUTPUT",
  "typedValue": "229.628",
  "recipient": null
}
```

## Error

```
SecurityError: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
```

## Stacktrace

```
Error: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at t.getCachedUrl (https://app.uniswap.org/static/js/35.b241a31f.chunk.js:2:986470)
    at https://app.uniswap.org/static/js/35.b241a31f.chunk.js:2:987399
    at Fs (https://app.uniswap.org/static/js/35.b241a31f.chunk.js:2:1406388)
    at t.unstable_runWithPriority (https://app.uniswap.org/static/js/35.b241a31f.chunk.js:2:1424167)
    at Gi (https://app.uniswap.org/static/js/35.b241a31f.chunk.js:2:1346707)
    at Rs (https://app.uniswap.org/static/js/35.b241a31f.chunk.js:2:1405849)
    at https://app.uniswap.org/static/js/35.b241a31f.chunk.js:2:1405760
    at L (https://app.uniswap.org/static/js/35.b241a31f.chunk.js:2:1423226)
    at MessagePort.k.port1.onmessage (https://app.uniswap.org/static/js/35.b241a31f.chunk.js:2:1421948)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "95.0.4638.69",
    "major": "95"
  },
  "engine": {
    "name": "Blink",
    "version": "95.0.4638.69"
  },
  "os": {
    "name": "Windows",
    "version": "10"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

**Comment by Baronak** [comment]
I can not place buy orders.

**Comment by Baronak** [comment]
I can not place buy orders.

**Comment by TNBCORPSGG** [comment]
{
  "INPUT": {
    "currencyId": null
  },
  "OUTPUT": {
    "currencyId": "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
  },
  "independentField": "OUTPUT",
  "typedValue": "229.628",
  "recipient": null
}
