### ISSUE TITLE
Crash report: `Error: Invariant failed`

### ISSUE THREAD

**Issue by ctjlewis** [Uniswap/interface#2797]
## URL
  
https://app.uniswap.org/#/swap

## `swap` state
    
```json
{
  "INPUT": {
    "currencyId": "0xC18360217D8F7Ab5e7c516566761Ea12Ce7F9D72"
  },
  "OUTPUT": {
    "currencyId": "ETH"
  },
  "independentField": "INPUT",
  "typedValue": "375",
  "recipient": null
}
```

## Error

```
Error: Invariant failed
```

## Stacktrace

```
Error: Invariant failed
    at t.a (https://app.uniswap.org/static/js/35.038aa360.chunk.js:2:135543)
    at t.n.sortsBefore (https://app.uniswap.org/static/js/35.038aa360.chunk.js:2:68832)
    at https://app.uniswap.org/static/js/main.f15af8e2.chunk.js:1:165994
    at Array.map (<anonymous>)
    at https://app.uniswap.org/static/js/main.f15af8e2.chunk.js:1:165776
    at Object.Aa [as useMemo] (https://app.uniswap.org/static/js/35.038aa360.chunk.js:2:1194683)
    at t.useMemo (https://app.uniswap.org/static/js/35.038aa360.chunk.js:2:1129703)
    at sa (https://app.uniswap.org/static/js/main.f15af8e2.chunk.js:1:165754)
    at https://app.uniswap.org/static/js/main.f15af8e2.chunk.js:1:167917
    at ba (https://app.uniswap.org/static/js/main.f15af8e2.chunk.js:1:168338)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "95.0.4638.69",
    "major": "95"
  },
  "engine": {
    "name": "Blink",
    "version": "95.0.4638.69"
  },
  "os": {
    "name": "Linux",
    "version": "x86_64"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

**Comment by willhennessy** [comment]
https://github.com/Uniswap/interface/issues/2677
