### ISSUE TITLE
Crash report: `TypeError: Cannot read properties of undefined (reading '0')`

### ISSUE THREAD

**Issue by slafebre** [Uniswap/interface#2798]
When trying to add liquidity for the USDC/USDT pair, the app returns an error.

## URL
  
https://app.uniswap.org/#/add/0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48/0xdAC17F958D2ee523a2206206994597C13D831ec7

## `mintV3` state
    
```json
{
  "independentField": "CURRENCY_A",
  "typedValue": "",
  "startPriceTypedValue": "",
  "leftRangeTypedValue": "",
  "rightRangeTypedValue": ""
}
```

## Error

```
TypeError: Cannot read properties of undefined (reading '0')
```

## Stacktrace

```
TypeError: Cannot read properties of undefined (reading '0')
    at https://app.uniswap.org/static/js/main.e9530db1.chunk.js:1:438547
    at Array.reduce (<anonymous>)
    at https://app.uniswap.org/static/js/main.e9530db1.chunk.js:1:438471
    at Object.Aa [as useMemo] (https://app.uniswap.org/static/js/35.49bb3185.chunk.js:2:1353145)
    at https://app.uniswap.org/static/js/35.49bb3185.chunk.js:2:1288165
    at https://app.uniswap.org/static/js/main.e9530db1.chunk.js:1:438108
    at uv (https://app.uniswap.org/static/js/main.e9530db1.chunk.js:1:439437)
    at Wv (https://app.uniswap.org/static/js/main.e9530db1.chunk.js:1:445347)
    at ua (https://app.uniswap.org/static/js/35.49bb3185.chunk.js:2:1348412)
    at Va (https://app.uniswap.org/static/js/35.49bb3185.chunk.js:2:1357979)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "96.0.4664.45",
    "major": "96"
  },
  "engine": {
    "name": "Blink",
    "version": "96.0.4664.45"
  },
  "os": {
    "name": "Mac OS",
    "version": "10.15.7"
  },
  "device": {},
  "cpu": {}
}
```

**Comment by NoahZinsmeister** [comment]
related:
#2830
#2798
#2782
