### ISSUE TITLE
Crash report: `Error: No V2 factory address on this chain`

### ISSUE THREAD

**Issue by Sowiedu** [Uniswap/interface#2813]
Was on the V2 Liquidity overview while connected with MM on Ethereum Mainnet. Upon switching to Arb1 via the Uniswap UI, I got presented with this error.

## URL
  
http://app.uniswap.org.ipns.localhost:48084/#/pool/v2

## Error

```
Error: No V2 factory address on this chain
```

## Stacktrace

```
Error: No V2 factory address on this chain
    at oa (http://app.uniswap.org.ipns.localhost:48084/static/js/main.235752c4.chunk.js:1:166335)
    at http://app.uniswap.org.ipns.localhost:48084/static/js/main.235752c4.chunk.js:1:676145
    at Array.map (<anonymous>)
    at http://app.uniswap.org.ipns.localhost:48084/static/js/main.235752c4.chunk.js:1:676106
    at Object.Aa [as useMemo] (http://app.uniswap.org.ipns.localhost:48084/static/js/35.b241a31f.chunk.js:2:1365871)
    at http://app.uniswap.org.ipns.localhost:48084/static/js/35.b241a31f.chunk.js:2:1300891
    at eE (http://app.uniswap.org.ipns.localhost:48084/static/js/main.235752c4.chunk.js:1:676084)
    at ua (http://app.uniswap.org.ipns.localhost:48084/static/js/35.b241a31f.chunk.js:2:1361138)
    at Va (http://app.uniswap.org.ipns.localhost:48084/static/js/35.b241a31f.chunk.js:2:1370705)
    at $u (http://app.uniswap.org.ipns.localhost:48084/static/js/35.b241a31f.chunk.js:2:1414429)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "95.0.4638.69",
    "major": "95"
  },
  "engine": {
    "name": "Blink",
    "version": "95.0.4638.69"
  },
  "os": {
    "name": "Mac OS",
    "version": "10.15.7"
  },
  "device": {},
  "cpu": {}
}
```

**Comment by NoahZinsmeister** [comment]
closing in favor of #2199
