### ISSUE TITLE
Crash report: `SecurityError: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.`

### ISSUE THREAD

**Issue by TipsyFingers** [Uniswap/interface#2823]
## URL
  
https://app.uniswap.org/#/swap?inputCurrency=ETH&outputCurrency=0xdfdd3459d4f87234751696840092ee20c970fb07&use=V2

## `swap` state
    
```json
{
  "INPUT": {
    "currencyId": "ETH"
  },
  "OUTPUT": {
    "currencyId": "0xDfDd3459D4F87234751696840092ee20C970Fb07"
  },
  "independentField": "INPUT",
  "typedValue": "",
  "recipient": null
}
```

## Error

```
SecurityError: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
```

## Stacktrace

```
Error: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at t.getCachedUrl (https://app.uniswap.org/static/js/35.5c687bd5.chunk.js:2:973010)
    at https://app.uniswap.org/static/js/35.5c687bd5.chunk.js:2:973939
    at Fs (https://app.uniswap.org/static/js/35.5c687bd5.chunk.js:2:1405498)
    at t.unstable_runWithPriority (https://app.uniswap.org/static/js/35.5c687bd5.chunk.js:2:1423277)
    at Gi (https://app.uniswap.org/static/js/35.5c687bd5.chunk.js:2:1345817)
    at Ns (https://app.uniswap.org/static/js/35.5c687bd5.chunk.js:2:1404959)
    at https://app.uniswap.org/static/js/35.5c687bd5.chunk.js:2:1404870
    at L (https://app.uniswap.org/static/js/35.5c687bd5.chunk.js:2:1422336)
    at MessagePort._.port1.onmessage (https://app.uniswap.org/static/js/35.5c687bd5.chunk.js:2:1421058)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "96.0.4664.45",
    "major": "96"
  },
  "engine": {
    "name": "Blink",
    "version": "96.0.4664.45"
  },
  "os": {
    "name": "Windows",
    "version": "10"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

**Comment by NoahZinsmeister** [comment]
closing in favor of #2727
