### ISSUE TITLE
Crash report: `TypeError: Cannot read properties of undefined (reading 'infoLink')`

### ISSUE THREAD

**Issue by jjshriver** [Uniswap/interface#2826]
## URL
  
https://app.uniswap.org/#/swap

## `swap` state
    
```json
{
  "INPUT": {
    "currencyId": "ETH"
  },
  "OUTPUT": {
    "currencyId": null
  },
  "independentField": "INPUT",
  "typedValue": "",
  "recipient": null
}
```

## Error

```
TypeError: Cannot read properties of undefined (reading 'infoLink')
```

## Stacktrace

```
TypeError: Cannot read properties of undefined (reading 'infoLink')
    at Ko (https://app.uniswap.org/static/js/main.236a2d7f.chunk.js:1:425905)
    at ua (https://app.uniswap.org/static/js/35.5c687bd5.chunk.js:2:1360248)
    at Ha (https://app.uniswap.org/static/js/35.5c687bd5.chunk.js:2:1369815)
    at $u (https://app.uniswap.org/static/js/35.5c687bd5.chunk.js:2:1413539)
    at Ps (https://app.uniswap.org/static/js/35.5c687bd5.chunk.js:2:1399789)
    at js (https://app.uniswap.org/static/js/35.5c687bd5.chunk.js:2:1399717)
    at Ss (https://app.uniswap.org/static/js/35.5c687bd5.chunk.js:2:1399580)
    at bs (https://app.uniswap.org/static/js/35.5c687bd5.chunk.js:2:1396546)
    at https://app.uniswap.org/static/js/35.5c687bd5.chunk.js:2:1346040
    at https://app.uniswap.org/static/js/35.5c687bd5.chunk.js:2:1423277
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "96.0.4664.45",
    "major": "96"
  },
  "engine": {
    "name": "Blink",
    "version": "96.0.4664.45"
  },
  "os": {
    "name": "Windows",
    "version": "10"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

**Comment by NoahZinsmeister** [comment]
closing in favor of #2782
