### ISSUE TITLE
Crash report: `SecurityError: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.`

### ISSUE THREAD

**Issue by jleemco** [Uniswap/interface#2829]
## URL
  
https://app.uniswap.org/#/swap?outputCurrency=0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2&theme=light&exactAmount=0.00315&exactField=output

## `swap` state
    
```json
{
  "INPUT": {
    "currencyId": null
  },
  "OUTPUT": {
    "currencyId": "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
  },
  "independentField": "OUTPUT",
  "typedValue": "0.00315",
  "recipient": null
}
```

## Error

```
SecurityError: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
```

## Stacktrace

```
Error: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at t.getCachedUrl (https://app.uniswap.org/static/js/35.5c687bd5.chunk.js:2:973010)
    at https://app.uniswap.org/static/js/35.5c687bd5.chunk.js:2:973939
    at Fs (https://app.uniswap.org/static/js/35.5c687bd5.chunk.js:2:1405498)
    at t.unstable_runWithPriority (https://app.uniswap.org/static/js/35.5c687bd5.chunk.js:2:1423277)
    at Gi (https://app.uniswap.org/static/js/35.5c687bd5.chunk.js:2:1345817)
    at Ns (https://app.uniswap.org/static/js/35.5c687bd5.chunk.js:2:1404959)
    at https://app.uniswap.org/static/js/35.5c687bd5.chunk.js:2:1404870
    at L (https://app.uniswap.org/static/js/35.5c687bd5.chunk.js:2:1422336)
    at MessagePort._.port1.onmessage (https://app.uniswap.org/static/js/35.5c687bd5.chunk.js:2:1421058)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "96.0.4664.45",
    "major": "96"
  },
  "engine": {
    "name": "Blink",
    "version": "96.0.4664.45"
  },
  "os": {
    "name": "Windows",
    "version": "10"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

**Comment by NoahZinsmeister** [comment]
closing in favor of #2727
