### ISSUE TITLE
Crash report: `TypeError: Cannot read properties of undefined (reading 'name')`

### ISSUE THREAD

**Issue by Guobaixi** [Uniswap/interface#2830]
## URL
  
https://app.herofi.io/#/marketplace

## Error

```
TypeError: Cannot read properties of undefined (reading 'name')
```

## Stacktrace

```
TypeError: Cannot read properties of undefined (reading 'name')
    at https://app.herofi.io/static/js/main.d2268c49.chunk.js:1:421049
    at Array.map (<anonymous>)
    at xA (https://app.herofi.io/static/js/main.d2268c49.chunk.js:1:420957)
    at ia (https://app.herofi.io/static/js/4.541c4e3d.chunk.js:2:1843460)
    at Ha (https://app.herofi.io/static/js/4.541c4e3d.chunk.js:2:1853027)
    at Vs (https://app.herofi.io/static/js/4.541c4e3d.chunk.js:2:1896909)
    at xu (https://app.herofi.io/static/js/4.541c4e3d.chunk.js:2:1883092)
    at Eu (https://app.herofi.io/static/js/4.541c4e3d.chunk.js:2:1883020)
    at Au (https://app.herofi.io/static/js/4.541c4e3d.chunk.js:2:1882883)
    at vu (https://app.herofi.io/static/js/4.541c4e3d.chunk.js:2:1879849)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "96.0.4664.45",
    "major": "96"
  },
  "engine": {
    "name": "Blink",
    "version": "96.0.4664.45"
  },
  "os": {
    "name": "Windows",
    "version": "10"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

**Comment by NoahZinsmeister** [comment]
related:
#2830
#2798
#2782
