### ISSUE TITLE
Crash report: `Error: No V2 factory address on this chain`

### ISSUE THREAD

**Issue by patrickworkman** [Uniswap/interface#2839]
## URL
  
https://app.uniswap.org/#/pool/v2

## Error

```
Error: No V2 factory address on this chain
```

## Stacktrace

```
Error: No V2 factory address on this chain
    at q (https://app.uniswap.org/static/js/main.236a2d7f.chunk.js:1:289457)
    at https://app.uniswap.org/static/js/main.236a2d7f.chunk.js:1:656851
    at Array.map (<anonymous>)
    at https://app.uniswap.org/static/js/main.236a2d7f.chunk.js:1:656801
    at Object.useMemo (https://app.uniswap.org/static/js/35.5c687bd5.chunk.js:2:1366213)
    at https://app.uniswap.org/static/js/35.5c687bd5.chunk.js:2:1300000
    at gj (https://app.uniswap.org/static/js/main.236a2d7f.chunk.js:1:656779)
    at ua (https://app.uniswap.org/static/js/35.5c687bd5.chunk.js:2:1360248)
    at $u (https://app.uniswap.org/static/js/35.5c687bd5.chunk.js:2:1412548)
    at Ps (https://app.uniswap.org/static/js/35.5c687bd5.chunk.js:2:1399789)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "96.0.4664.45",
    "major": "96"
  },
  "engine": {
    "name": "Blink",
    "version": "96.0.4664.45"
  },
  "os": {
    "name": "Mac OS",
    "version": "10.15.7"
  },
  "device": {},
  "cpu": {}
}
```

**Comment by NoahZinsmeister** [comment]
closing in favor of #2199
