### ISSUE TITLE
Crash report: `TypeError: Cannot read properties of undefined (reading '0')`

### ISSUE THREAD

**Issue by mslovy** [Uniswap/interface#2844]
## URL
  
https://app.uniswap.org/#/add/ETH/0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48

## `mintV3` state
    
```json
{
  "independentField": "CURRENCY_A",
  "typedValue": "",
  "startPriceTypedValue": "",
  "leftRangeTypedValue": "",
  "rightRangeTypedValue": ""
}
```

## Error

```
TypeError: Cannot read properties of undefined (reading '0')
```

## Stacktrace

```
TypeError: Cannot read properties of undefined (reading '0')
    at https://app.uniswap.org/static/js/main.da1bd560.chunk.js:1:438562
    at Array.reduce (<anonymous>)
    at https://app.uniswap.org/static/js/main.da1bd560.chunk.js:1:438486
    at Object.Aa [as useMemo] (https://app.uniswap.org/static/js/35.8cc8582a.chunk.js:2:1352918)
    at https://app.uniswap.org/static/js/35.8cc8582a.chunk.js:2:1287938
    at https://app.uniswap.org/static/js/main.da1bd560.chunk.js:1:438123
    at uv (https://app.uniswap.org/static/js/main.da1bd560.chunk.js:1:439452)
    at Wv (https://app.uniswap.org/static/js/main.da1bd560.chunk.js:1:445327)
    at ua (https://app.uniswap.org/static/js/35.8cc8582a.chunk.js:2:1348185)
    at Va (https://app.uniswap.org/static/js/35.8cc8582a.chunk.js:2:1357752)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "95.0.4638.69",
    "major": "95"
  },
  "engine": {
    "name": "Blink",
    "version": "95.0.4638.69"
  },
  "os": {
    "name": "Windows",
    "version": "10"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

**Comment by NoahZinsmeister** [comment]
closing in favor of #2798
