### ISSUE TITLE
Crash report: `TypeError: Cannot read properties of undefined (reading '0')`

### ISSUE THREAD

**Issue by aduca98** [Uniswap/interface#2854]
## URL
  
https://app.uniswap.org/#/add/0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48/0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2/3000

## `mintV3` state
    
```json
{
  "independentField": "CURRENCY_A",
  "typedValue": "",
  "startPriceTypedValue": "",
  "leftRangeTypedValue": "",
  "rightRangeTypedValue": ""
}
```

## Error

```
TypeError: Cannot read properties of undefined (reading '0')
```

## Stacktrace

```
TypeError: Cannot read properties of undefined (reading '0')
    at https://app.uniswap.org/static/js/main.8a72fbb9.chunk.js:1:438066
    at Array.reduce (<anonymous>)
    at https://app.uniswap.org/static/js/main.8a72fbb9.chunk.js:1:437990
    at Object.Aa [as useMemo] (https://app.uniswap.org/static/js/35.d35d34a0.chunk.js:2:1352918)
    at t.useMemo (https://app.uniswap.org/static/js/35.d35d34a0.chunk.js:2:1287938)
    at https://app.uniswap.org/static/js/main.8a72fbb9.chunk.js:1:437627
    at uv (https://app.uniswap.org/static/js/main.8a72fbb9.chunk.js:1:438956)
    at Wv (https://app.uniswap.org/static/js/main.8a72fbb9.chunk.js:1:444831)
    at ua (https://app.uniswap.org/static/js/35.d35d34a0.chunk.js:2:1348185)
    at Va (https://app.uniswap.org/static/js/35.d35d34a0.chunk.js:2:1357752)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "95.0.4638.69",
    "major": "95"
  },
  "engine": {
    "name": "Blink",
    "version": "95.0.4638.69"
  },
  "os": {
    "name": "Mac OS",
    "version": "10.15.7"
  },
  "device": {},
  "cpu": {}
}
```

**Comment by NoahZinsmeister** [comment]
closing in favor of #2798
