### ISSUE TITLE
Crash report: `NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.`

### ISSUE THREAD

**Issue by dineshpotla** [Uniswap/interface#2858]
## URL
  
https://app.uniswap.org/#/swap

## `swap` state
    
```json
{
  "INPUT": {
    "currencyId": null
  },
  "OUTPUT": {
    "currencyId": "ETH"
  },
  "independentField": "OUTPUT",
  "typedValue": "",
  "recipient": null
}
```

## Error

```
NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
```

## Stacktrace

```
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at https://app.uniswap.org/static/js/main.d40e0b88.chunk.js:1:378159
    at Fs (https://app.uniswap.org/static/js/34.d906cff3.chunk.js:2:1294624)
    at https://app.uniswap.org/static/js/34.d906cff3.chunk.js:2:1312538
    at Gi (https://app.uniswap.org/static/js/34.d906cff3.chunk.js:2:1235078)
    at Ns (https://app.uniswap.org/static/js/34.d906cff3.chunk.js:2:1294220)
    at https://app.uniswap.org/static/js/34.d906cff3.chunk.js:2:1294131
    at L (https://app.uniswap.org/static/js/34.d906cff3.chunk.js:2:1311597)
    at MessagePort.<anonymous> (https://app.uniswap.org/static/js/34.d906cff3.chunk.js:2:1310319)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "96.0.4664.55",
    "major": "96"
  },
  "engine": {
    "name": "Blink",
    "version": "96.0.4664.55"
  },
  "os": {
    "name": "Mac OS",
    "version": "10.15.7"
  },
  "device": {},
  "cpu": {}
}
```

**Comment by zzmp** [comment]
Hi @dineshpotla, can you give any more context as to what you were doing that caused the crash? If possible, can you walk us through how to reproduce this error?

**Comment by dineshpotla** [comment]
actually when i started using uniswap after I installed Mcafee ? or I don't know it appeared in my new MacBook pro m1 pro. trying first time in this new laptop

**Comment by dineshpotla** [comment]
btw only happening with chrome+metamask combination

**Comment by benscholler** [comment]
I'm also having this issue. I've closed and reopened my browser to no success. I'm loading up the main swap page without any tokens loaded. If I switch away to another network besides Ethereum in Metamask and refresh the page, no error happens. If I switch back to the Ethereum network, the error comes up again.
