### ISSUE TITLE
Crash report: `NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.`

### ISSUE THREAD

**Issue by 0xJonHoldsCrypto** [Uniswap/interface#2875]
## URL
  
https://app.uniswap.org/#/pool

## Error

```
NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
```

## Stacktrace

```
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at https://app.uniswap.org/static/js/main.d40e0b88.chunk.js:1:378159
    at Fs (https://app.uniswap.org/static/js/34.d906cff3.chunk.js:2:1294624)
    at t.unstable_runWithPriority (https://app.uniswap.org/static/js/34.d906cff3.chunk.js:2:1312538)
    at Gi (https://app.uniswap.org/static/js/34.d906cff3.chunk.js:2:1235078)
    at Ns (https://app.uniswap.org/static/js/34.d906cff3.chunk.js:2:1294220)
    at https://app.uniswap.org/static/js/34.d906cff3.chunk.js:2:1294131
    at L (https://app.uniswap.org/static/js/34.d906cff3.chunk.js:2:1311597)
    at MessagePort._.port1.onmessage (https://app.uniswap.org/static/js/34.d906cff3.chunk.js:2:1310319)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "96.0.4664.45",
    "major": "96"
  },
  "engine": {
    "name": "Blink",
    "version": "96.0.4664.45"
  },
  "os": {
    "name": "Windows",
    "version": "10"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

**Comment by moodysalem** [comment]
Please try a hard refresh and let us know if you can reproduce
