### ISSUE TITLE
Connecting Coinbase Wallet Problem 

### ISSUE THREAD

**Issue by NeptunePoke** [Uniswap/interface#2884]
**Bug Description**
A clear and concise description of the bug.

**Steps to Reproduce**

https://app.uniswap.org/#/swap?use=V2

Error: Unsupported chain ID
    at n.get (https://app.uniswap.org/static/js/main.df42f964.chunk.js:1:193458)
    at c (https://app.uniswap.org/static/js/main.df42f964.chunk.js:1:142885)
    at l (https://app.uniswap.org/static/js/main.df42f964.chunk.js:1:141026)
    at b (https://app.uniswap.org/static/js/main.df42f964.chunk.js:1:141529)
    at p (https://app.uniswap.org/static/js/main.df42f964.chunk.js:1:769913)
    at Y (https://app.uniswap.org/static/js/main.df42f964.chunk.js:1:776547)
    at ee (https://app.uniswap.org/static/js/main.df42f964.chunk.js:1:780266)
    at jh (https://app.uniswap.org/static/js/main.df42f964.chunk.js:1:729069)
    at ua (https://app.uniswap.org/static/js/34.d906cff3.chunk.js:2:1249509)
    at Ha (https://app.uniswap.org/static/js/34.d906cff3.chunk.js:2:1259076)
1. Go to ...
2. Click on ...
   ...

**Expected Behavior**

**Additional Context**
Add any other context about the problem here (screenshots, whether the bug only occurs only in certain mobile/desktop/browser environments, etc.)

**Comment by NoahZinsmeister** [comment]
closing in favor of #2749
