### ISSUE TITLE
Crash report: `Error: Unsupported chain ID`

### ISSUE THREAD

**Issue by adrianoresende** [Uniswap/interface#2885]
## URL
  
https://app.uniswap.org/#/swap

## `swap` state
    
```json
{
  "INPUT": {
    "currencyId": "ETH"
  },
  "OUTPUT": {
    "currencyId": null
  },
  "independentField": "INPUT",
  "typedValue": "",
  "recipient": null
}
```

## Error

```
Error: Unsupported chain ID
```

## Stacktrace

```
Error: Unsupported chain ID
    at n.get (https://app.uniswap.org/static/js/main.df42f964.chunk.js:1:193458)
    at c (https://app.uniswap.org/static/js/main.df42f964.chunk.js:1:142885)
    at l (https://app.uniswap.org/static/js/main.df42f964.chunk.js:1:141026)
    at b (https://app.uniswap.org/static/js/main.df42f964.chunk.js:1:141529)
    at p (https://app.uniswap.org/static/js/main.df42f964.chunk.js:1:769913)
    at Y (https://app.uniswap.org/static/js/main.df42f964.chunk.js:1:776547)
    at ee (https://app.uniswap.org/static/js/main.df42f964.chunk.js:1:780266)
    at jh (https://app.uniswap.org/static/js/main.df42f964.chunk.js:1:729069)
    at ua (https://app.uniswap.org/static/js/34.d906cff3.chunk.js:2:1249509)
    at Ha (https://app.uniswap.org/static/js/34.d906cff3.chunk.js:2:1259076)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "96.0.4664.45",
    "major": "96"
  },
  "engine": {
    "name": "Blink",
    "version": "96.0.4664.45"
  },
  "os": {
    "name": "Mac OS",
    "version": "10.15.7"
  },
  "device": {},
  "cpu": {}
}
```

**Comment by NoahZinsmeister** [comment]
closing in favor of #2749
