### ISSUE TITLE
Crash report: `TypeError: Cannot read properties of undefined (reading '0')`

### ISSUE THREAD

**Issue by moletiger1** [Uniswap/interface#2899]
## URL
  
https://app.uniswap.org/#/add/ETH/0x6B175474E89094C44Da98b954EedeAC495271XXX

## `mintV3` state
    
```json
{
  "independentField": "CURRENCY_A",
  "typedValue": "",
  "startPriceTypedValue": "",
  "leftRangeTypedValue": "",
  "rightRangeTypedValue": ""
}
```

## Error

```
TypeError: Cannot read properties of undefined (reading '0')
```

## Stacktrace

```
TypeError: Cannot read properties of undefined (reading '0')
    at https://app.uniswap.org/static/js/main.343a607d.chunk.js:1:428188
    at Array.reduce (<anonymous>)
    at https://app.uniswap.org/static/js/main.343a607d.chunk.js:1:428112
    at Object.Aa [as useMemo] (https://app.uniswap.org/static/js/35.d8826fff.chunk.js:2:1196614)
    at t.useMemo (https://app.uniswap.org/static/js/35.d8826fff.chunk.js:2:1131634)
    at https://app.uniswap.org/static/js/main.343a607d.chunk.js:1:427749
    at zg (https://app.uniswap.org/static/js/main.343a607d.chunk.js:1:429078)
    at xv (https://app.uniswap.org/static/js/main.343a607d.chunk.js:1:434953)
    at ua (https://app.uniswap.org/static/js/35.d8826fff.chunk.js:2:1191881)
    at Ha (https://app.uniswap.org/static/js/35.d8826fff.chunk.js:2:1201448)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "96.0.4664.45",
    "major": "96"
  },
  "engine": {
    "name": "Blink",
    "version": "96.0.4664.45"
  },
  "os": {
    "name": "Mac OS",
    "version": "10.15.7"
  },
  "device": {},
  "cpu": {}
}
```

**Comment by aramatev** [comment]
i got the same error

**Comment by NoahZinsmeister** [comment]
closing in favor of #2798
