### ISSUE TITLE
Crash report: `TypeError: Cannot read properties of undefined (reading '0')`

### ISSUE THREAD

**Issue by aramatev** [Uniswap/interface#2904]
## URL
  
https://app.uniswap.org/#/add/ETH/0x6B175474E89094C44Da98b954EedeAC495271d0F

## `mintV3` state
    
```json
{
  "independentField": "CURRENCY_A",
  "typedValue": "",
  "startPriceTypedValue": "",
  "leftRangeTypedValue": "",
  "rightRangeTypedValue": ""
}
```

## Error

```
TypeError: Cannot read properties of undefined (reading '0')
```

## Stacktrace

```
TypeError: Cannot read properties of undefined (reading '0')
    at https://app.uniswap.org/static/js/main.d86699df.chunk.js:1:438458
    at Array.reduce (<anonymous>)
    at https://app.uniswap.org/static/js/main.d86699df.chunk.js:1:438382
    at Object.Aa [as useMemo] (https://app.uniswap.org/static/js/35.d35d34a0.chunk.js:2:1352918)
    at t.useMemo (https://app.uniswap.org/static/js/35.d35d34a0.chunk.js:2:1287938)
    at https://app.uniswap.org/static/js/main.d86699df.chunk.js:1:438019
    at uv (https://app.uniswap.org/static/js/main.d86699df.chunk.js:1:439348)
    at Wv (https://app.uniswap.org/static/js/main.d86699df.chunk.js:1:445223)
    at ua (https://app.uniswap.org/static/js/35.d35d34a0.chunk.js:2:1348185)
    at Va (https://app.uniswap.org/static/js/35.d35d34a0.chunk.js:2:1357752)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "96.0.4664.55",
    "major": "96"
  },
  "engine": {
    "name": "Blink",
    "version": "96.0.4664.55"
  },
  "os": {
    "name": "Mac OS",
    "version": "10.15.7"
  },
  "device": {},
  "cpu": {}
}
```

**Comment by aramatev** [comment]
Trying to create a new position for a pool, using DAI + ETH pair

**Comment by NoahZinsmeister** [comment]
closing in favor of #2798
