### ISSUE TITLE
Crash report: `Error: Unsupported chain ID`

### ISSUE THREAD

**Issue by xlsuite** [Uniswap/interface#2907]
## URL
  
https://app.uniswap.org/#/swap

## `swap` state
    
```json
{
  "INPUT": {
    "currencyId": "ETH"
  },
  "OUTPUT": {
    "currencyId": null
  },
  "independentField": "INPUT",
  "typedValue": "",
  "recipient": null
}
```

## Error

```
Error: Unsupported chain ID
```

## Stacktrace

```
Error: Unsupported chain ID
    at n.get (https://app.uniswap.org/static/js/main.c975c0c3.chunk.js:1:190130)
    at c (https://app.uniswap.org/static/js/main.c975c0c3.chunk.js:1:139161)
    at l (https://app.uniswap.org/static/js/main.c975c0c3.chunk.js:1:137302)
    at b (https://app.uniswap.org/static/js/main.c975c0c3.chunk.js:1:137805)
    at p (https://app.uniswap.org/static/js/main.c975c0c3.chunk.js:1:766515)
    at Y (https://app.uniswap.org/static/js/main.c975c0c3.chunk.js:1:776863)
    at ee (https://app.uniswap.org/static/js/main.c975c0c3.chunk.js:1:780583)
    at uh (https://app.uniswap.org/static/js/main.c975c0c3.chunk.js:1:725671)
    at ua (https://app.uniswap.org/static/js/34.92d1da43.chunk.js:2:1249373)
    at Ha (https://app.uniswap.org/static/js/34.92d1da43.chunk.js:2:1258940)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "96.0.4664.45",
    "major": "96"
  },
  "engine": {
    "name": "Blink",
    "version": "96.0.4664.45"
  },
  "os": {
    "name": "Windows",
    "version": "10"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

**Comment by NoahZinsmeister** [comment]
closing in favor of #2749
