### ISSUE TITLE
Crash report: `NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.`

### ISSUE THREAD

**Issue by trevor-thompson** [Uniswap/interface#2927]
## URL
  
https://app.uniswap.org/#/swap?outputCurrency=0x7be647634a942e73f8492d15ae492d867ce5245c

## `swap` state
    
```json
{
  "INPUT": {
    "currencyId": null
  },
  "OUTPUT": {
    "currencyId": "0x7bE647634A942e73F8492d15Ae492D867Ce5245c"
  },
  "independentField": "INPUT",
  "typedValue": "",
  "recipient": null
}
```

## Error

```
NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
```

## Stacktrace

```
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at https://app.uniswap.org/static/js/main.d40e0b88.chunk.js:1:378159
    at Fs (https://app.uniswap.org/static/js/34.d906cff3.chunk.js:2:1294624)
    at https://app.uniswap.org/static/js/34.d906cff3.chunk.js:2:1312538
    at Gi (https://app.uniswap.org/static/js/34.d906cff3.chunk.js:2:1235078)
    at Ns (https://app.uniswap.org/static/js/34.d906cff3.chunk.js:2:1294220)
    at https://app.uniswap.org/static/js/34.d906cff3.chunk.js:2:1294131
    at L (https://app.uniswap.org/static/js/34.d906cff3.chunk.js:2:1311597)
    at MessagePort.<anonymous> (https://app.uniswap.org/static/js/34.d906cff3.chunk.js:2:1310319)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "96.0.4664.55",
    "major": "96"
  },
  "engine": {
    "name": "Blink",
    "version": "96.0.4664.55"
  },
  "os": {
    "name": "Mac OS",
    "version": "10.15.7"
  },
  "device": {},
  "cpu": {}
}
```

Been having this the last few days. I see that there were a couple of other reports and a fix that was merged but I'm still having the issue today.

**Comment by trevor-thompson** [comment]
I see on another ticket a hard refresh gets rid of the problem. It fixed it for me too.

Users still shouldn't hit the error page and then wind up here. I'd recommend either catching the error and purposing a recommendation or fixing the issue being caused by the cache altogether

**Comment by NoahZinsmeister** [comment]
closing in favor of #2481
