### ISSUE TITLE
Crash report: `TypeError: Cannot read properties of undefined (reading '0')`

### ISSUE THREAD

**Issue by longyangxi** [Uniswap/interface#2930]
## URL
  
https://app.uniswap.org/#/add/ETH/0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48

## `mintV3` state
    
```json
{
  "independentField": "CURRENCY_A",
  "typedValue": "",
  "startPriceTypedValue": "",
  "leftRangeTypedValue": "",
  "rightRangeTypedValue": ""
}
```

## Error

```
TypeError: Cannot read properties of undefined (reading '0')
```

## Stacktrace

```
TypeError: Cannot read properties of undefined (reading '0')
    at https://app.uniswap.org/static/js/main.eb295194.chunk.js:1:428550
    at Array.reduce (<anonymous>)
    at https://app.uniswap.org/static/js/main.eb295194.chunk.js:1:428474
    at Object.Aa [as useMemo] (https://app.uniswap.org/static/js/35.d44dca6f.chunk.js:2:1196614)
    at t.useMemo (https://app.uniswap.org/static/js/35.d44dca6f.chunk.js:2:1131634)
    at https://app.uniswap.org/static/js/main.eb295194.chunk.js:1:428111
    at zg (https://app.uniswap.org/static/js/main.eb295194.chunk.js:1:429440)
    at xv (https://app.uniswap.org/static/js/main.eb295194.chunk.js:1:435315)
    at ua (https://app.uniswap.org/static/js/35.d44dca6f.chunk.js:2:1191881)
    at Ha (https://app.uniswap.org/static/js/35.d44dca6f.chunk.js:2:1201448)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "96.0.4664.55",
    "major": "96"
  },
  "engine": {
    "name": "Blink",
    "version": "96.0.4664.55"
  },
  "os": {
    "name": "Mac OS",
    "version": "10.15.7"
  },
  "device": {},
  "cpu": {}
}
```

**Comment by willhennessy** [comment]
ty https://github.com/Uniswap/interface/issues/2798
