### ISSUE TITLE
Crash report: `Error: Unsupported chain ID`

### ISSUE THREAD

**Issue by pmf10** [Uniswap/interface#2942]
## URL
  
https://app.uniswap.org/#/swap?outputCurrency=0x15F0EEDF9Ce24fc4b6826E590A8292CE5524a1DA&use=V2

## `swap` state
    
```json
{
  "INPUT": {
    "currencyId": null
  },
  "OUTPUT": {
    "currencyId": "0x15F0EEDF9Ce24fc4b6826E590A8292CE5524a1DA"
  },
  "independentField": "INPUT",
  "typedValue": "",
  "recipient": null
}
```

## Error

```
Error: Unsupported chain ID
```

## Stacktrace

```
Error: Unsupported chain ID
    at n.get (https://app.uniswap.org/static/js/main.d0cccaa8.chunk.js:1:187499)
    at c (https://app.uniswap.org/static/js/main.d0cccaa8.chunk.js:1:136576)
    at l (https://app.uniswap.org/static/js/main.d0cccaa8.chunk.js:1:134717)
    at b (https://app.uniswap.org/static/js/main.d0cccaa8.chunk.js:1:135220)
    at p (https://app.uniswap.org/static/js/main.d0cccaa8.chunk.js:1:757374)
    at Y (https://app.uniswap.org/static/js/main.d0cccaa8.chunk.js:1:767722)
    at ee (https://app.uniswap.org/static/js/main.d0cccaa8.chunk.js:1:771442)
    at lh (https://app.uniswap.org/static/js/main.d0cccaa8.chunk.js:1:719875)
    at ua (https://app.uniswap.org/static/js/34.851e919d.chunk.js:2:1269331)
    at Ha (https://app.uniswap.org/static/js/34.851e919d.chunk.js:2:1278898)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "96.0.4664.93",
    "major": "96"
  },
  "engine": {
    "name": "Blink",
    "version": "96.0.4664.93"
  },
  "os": {
    "name": "Windows",
    "version": "10"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

**Comment by willhennessy** [comment]
ty https://github.com/Uniswap/interface/issues/2749
