### ISSUE TITLE
Crash report: `TypeError: Cannot read properties of undefined (reading 'divide')`

### ISSUE THREAD

**Issue by sNnickK** [Uniswap/interface#2947]
## URL
  
http://localhost:3000/#/swap

## `swap` state
    
```json
{
  "INPUT": {
    "currencyId": "ETH"
  },
  "OUTPUT": {
    "currencyId": null
  },
  "PRICE": {
    "currencyId": null
  },
  "independentField": "PRICE",
  "fixedField": "INPUT",
  "typedValue": "1",
  "inputValue": "",
  "recipient": null
}
```

## Error

```
TypeError: Cannot read properties of undefined (reading 'divide')
```

## Stacktrace

```
TypeError: Cannot read properties of undefined (reading 'divide')
    at new Price (http://localhost:3000/static/js/vendors~main.chunk.js:41948:40)
    at http://localhost:3000/static/js/main.chunk.js:64506:61
    at updateMemo (http://localhost:3000/static/js/vendors~main.chunk.js:115337:23)
    at Object.useMemo (http://localhost:3000/static/js/vendors~main.chunk.js:115877:20)
    at useMemo (http://localhost:3000/static/js/vendors~main.chunk.js:178438:25)
    at useDerivedSwapInfo (http://localhost:3000/static/js/main.chunk.js:64505:76)
    at Swap (http://localhost:3000/static/js/main.chunk.js:52965:84)
    at renderWithHooks (http://localhost:3000/static/js/vendors~main.chunk.js:114478:22)
    at updateFunctionComponent (http://localhost:3000/static/js/vendors~main.chunk.js:116800:24)
    at beginWork (http://localhost:3000/static/js/vendors~main.chunk.js:118453:20)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/vendors~main.chunk.js:103428:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/vendors~main.chunk.js:103477:20)
    at invokeGuardedCallback (http://localhost:3000/static/js/vendors~main.chunk.js:103537:35)
    at beginWork$1 (http://localhost:3000/static/js/vendors~main.chunk.js:123279:11)
    at performUnitOfWork (http://localhost:3000/static/js/vendors~main.chunk.js:122115:16)
    at workLoopSync (http://localhost:3000/static/js/vendors~main.chunk.js:122052:9)
    at renderRootSync (http://localhost:3000/static/js/vendors~main.chunk.js:122018:11)
    at performSyncWorkOnRoot (http://localhost:3000/static/js/vendors~main.chunk.js:121635:22)
    at http://localhost:3000/static/js/vendors~main.chunk.js:110888:30
    at unstable_runWithPriority (http://localhost:3000/static/js/vendors~main.chunk.js:187196:16)
    at runWithPriority$1 (http://localhost:3000/static/js/vendors~main.chunk.js:110834:14)
    at flushSyncCallbackQueueImpl (http://localhost:3000/static/js/vendors~main.chunk.js:110883:13)
    at flushSyncCallbackQueue (http://localhost:3000/static/js/vendors~main.chunk.js:110871:7)
    at flushPendingDiscreteUpdates (http://localhost:3000/static/js/vendors~main.chunk.js:121714:7)
    at flushDiscreteUpdates (http://localhost:3000/static/js/vendors~main.chunk.js:121695:7)
    at finishEventHandler (http://localhost:3000/static/js/vendors~main.chunk.js:103194:9)
    at batchedEventUpdates (http://localhost:3000/static/js/vendors~main.chunk.js:103229:9)
    at dispatchEventForPluginEventSystem (http://localhost:3000/static/js/vendors~main.chunk.js:108053:7)
    at attemptToDispatchEvent (http://localhost:3000/static/js/vendors~main.chunk.js:105536:7)
    at dispatchEvent (http://localhost:3000/static/js/vendors~main.chunk.js:105454:23)
    at unstable_runWithPriority (http://localhost:3000/static/js/vendors~main.chunk.js:187196:16)
    at runWithPriority$1 (http://localhost:3000/static/js/vendors~main.chunk.js:110834:14)
    at discreteUpdates$1 (http://localhost:3000/static/js/vendors~main.chunk.js:121756:18)
    at discreteUpdates (http://localhost:3000/static/js/vendors~main.chunk.js:103238:16)
    at dispatchDiscreteEvent (http://localhost:3000/static/js/vendors~main.chunk.js:105420:7)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "96.0.4664.93",
    "major": "96"
  },
  "engine": {
    "name": "Blink",
    "version": "96.0.4664.93"
  },
  "os": {
    "name": "Linux",
    "version": "x86_64"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

**Comment by moodysalem** [comment]
Looks like something caused by your edits to the code, since price isn't a possible independent field in swap
