### ISSUE TITLE
Crash report: `TypeError: Cannot read properties of undefined (reading '0')`

### ISSUE THREAD

**Issue by paul-harrison-jordan** [Uniswap/interface#2962]
## URL
  
https://app.uniswap.org/#/add/0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48/0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2/3000

## `mintV3` state
    
```json
{
  "independentField": "CURRENCY_A",
  "typedValue": "",
  "startPriceTypedValue": "",
  "leftRangeTypedValue": "",
  "rightRangeTypedValue": ""
}
```

## Error

```
TypeError: Cannot read properties of undefined (reading '0')
```

## Stacktrace

```
TypeError: Cannot read properties of undefined (reading '0')
    at https://app.uniswap.org/static/js/main.c1ec46c4.chunk.js:1:438562
    at Array.reduce (<anonymous>)
    at https://app.uniswap.org/static/js/main.c1ec46c4.chunk.js:1:438486
    at Object.Aa [as useMemo] (https://app.uniswap.org/static/js/35.4cd51aae.chunk.js:2:1353145)
    at t.useMemo (https://app.uniswap.org/static/js/35.4cd51aae.chunk.js:2:1288165)
    at https://app.uniswap.org/static/js/main.c1ec46c4.chunk.js:1:438123
    at uv (https://app.uniswap.org/static/js/main.c1ec46c4.chunk.js:1:439452)
    at Wv (https://app.uniswap.org/static/js/main.c1ec46c4.chunk.js:1:445362)
    at ua (https://app.uniswap.org/static/js/35.4cd51aae.chunk.js:2:1348412)
    at Va (https://app.uniswap.org/static/js/35.4cd51aae.chunk.js:2:1357979)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "96.0.4664.55",
    "major": "96"
  },
  "engine": {
    "name": "Blink",
    "version": "96.0.4664.55"
  },
  "os": {
    "name": "Mac OS",
    "version": "10.15.7"
  },
  "device": {},
  "cpu": {}
}
```

**Comment by willhennessy** [comment]
ty https://github.com/Uniswap/interface/issues/2798
