### ISSUE TITLE
Crash report: `TypeError: Cannot read properties of undefined (reading '0')`

### ISSUE THREAD

**Issue by tch1001** [Uniswap/interface#2966]
## URL
  
https://app.uniswap.org/#/add/ETH/0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599

## `mintV3` state
    
```json
{
  "independentField": "CURRENCY_A",
  "typedValue": "",
  "startPriceTypedValue": "",
  "leftRangeTypedValue": "",
  "rightRangeTypedValue": ""
}
```

## Error

```
TypeError: Cannot read properties of undefined (reading '0')
```

## Stacktrace

```
TypeError: Cannot read properties of undefined (reading '0')
    at https://app.uniswap.org/static/js/main.da1bd560.chunk.js:1:438562
    at Array.reduce (<anonymous>)
    at https://app.uniswap.org/static/js/main.da1bd560.chunk.js:1:438486
    at Object.Aa [as useMemo] (https://app.uniswap.org/static/js/35.8cc8582a.chunk.js:2:1352918)
    at t.useMemo (https://app.uniswap.org/static/js/35.8cc8582a.chunk.js:2:1287938)
    at https://app.uniswap.org/static/js/main.da1bd560.chunk.js:1:438123
    at uv (https://app.uniswap.org/static/js/main.da1bd560.chunk.js:1:439452)
    at Wv (https://app.uniswap.org/static/js/main.da1bd560.chunk.js:1:445327)
    at ua (https://app.uniswap.org/static/js/35.8cc8582a.chunk.js:2:1348185)
    at Va (https://app.uniswap.org/static/js/35.8cc8582a.chunk.js:2:1357752)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "96.0.4664.93",
    "major": "96"
  },
  "engine": {
    "name": "Blink",
    "version": "96.0.4664.93"
  },
  "os": {
    "name": "Mac OS",
    "version": "10.15.6"
  },
  "device": {},
  "cpu": {}
}
```

**Comment by willhennessy** [comment]
ty https://github.com/Uniswap/interface/issues/2798
