### ISSUE TITLE
Crash report: `Error: Unsupported chain ID`

### ISSUE THREAD

**Issue by iam-frankqiu** [Uniswap/interface#2970]
### Reproducing step

When I open my coinbase wallet scanning the code to connect with uniswap, My wallet showed success but the uniswap turned this err.

## URL
  
https://app.uniswap.org/#/swap

## `swap` state
    
```json
{
  "INPUT": {
    "currencyId": "ETH"
  },
  "OUTPUT": {
    "currencyId": null
  },
  "independentField": "INPUT",
  "typedValue": "",
  "recipient": null
}
```

## Error

```
Error: Unsupported chain ID
```

## Stacktrace

```
Error: Unsupported chain ID
    at n.get (https://app.uniswap.org/static/js/main.080f7b55.chunk.js:1:187499)
    at c (https://app.uniswap.org/static/js/main.080f7b55.chunk.js:1:136576)
    at l (https://app.uniswap.org/static/js/main.080f7b55.chunk.js:1:134717)
    at b (https://app.uniswap.org/static/js/main.080f7b55.chunk.js:1:135220)
    at p (https://app.uniswap.org/static/js/main.080f7b55.chunk.js:1:757559)
    at Y (https://app.uniswap.org/static/js/main.080f7b55.chunk.js:1:767907)
    at ee (https://app.uniswap.org/static/js/main.080f7b55.chunk.js:1:771627)
    at lh (https://app.uniswap.org/static/js/main.080f7b55.chunk.js:1:720060)
    at ua (https://app.uniswap.org/static/js/34.851e919d.chunk.js:2:1269331)
    at Ha (https://app.uniswap.org/static/js/34.851e919d.chunk.js:2:1278898)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "96.0.4664.45",
    "major": "96"
  },
  "engine": {
    "name": "Blink",
    "version": "96.0.4664.45"
  },
  "os": {
    "name": "Mac OS",
    "version": "10.15.6"
  },
  "device": {},
  "cpu": {}
}
```

**Comment by willhennessy** [comment]
ty! https://github.com/Uniswap/interface/issues/2749
