### ISSUE TITLE
Crash report: `TypeError: Cannot read properties of undefined (reading 'vZeyDRBdmKsbYroJsPkeydownt')`

### ISSUE THREAD

**Issue by huangshiqun** [Uniswap/interface#2977]
## URL
  
https://app.uniswap.org/#/swap

## `swap` state
    
```json
{
  "INPUT": {
    "currencyId": "ETH"
  },
  "OUTPUT": {
    "currencyId": null
  },
  "typedValue": "",
  "independentField": "INPUT",
  "recipient": null
}
```

## Error

```
TypeError: Cannot read properties of undefined (reading 'vZeyDRBdmKsbYroJsPkeydownt')
```

## Stacktrace

```
TypeError: Cannot read properties of undefined (reading 'vZeyDRBdmKsbYroJsPkeydownt')
    at addEventListener (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?name=%25E7%25BD%2591%25E9%25A1%25B5%25E9%2599%2590%25E5%2588%25B6%25E8%25A7%25A3%25E9%2599%25A4.user.js&id=405a2eb5-da29-43d6-98a7-529c1a076402:85:14)
    at https://app.uniswap.org/static/js/34.851e919d.chunk.js:2:600341
    at Array.forEach (<anonymous>)
    at j (https://app.uniswap.org/static/js/34.851e919d.chunk.js:2:600320)
    at https://app.uniswap.org/static/js/main.62d9d18a.chunk.js:1:318468
    at Fs (https://app.uniswap.org/static/js/34.851e919d.chunk.js:2:1314581)
    at https://app.uniswap.org/static/js/34.851e919d.chunk.js:2:1332360
    at Gi (https://app.uniswap.org/static/js/34.851e919d.chunk.js:2:1254900)
    at Ns (https://app.uniswap.org/static/js/34.851e919d.chunk.js:2:1314042)
    at bs (https://app.uniswap.org/static/js/34.851e919d.chunk.js:2:1305532)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "95.0.4638.69",
    "major": "95"
  },
  "engine": {
    "name": "Blink",
    "version": "95.0.4638.69"
  },
  "os": {
    "name": "Windows",
    "version": "7"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

**Comment by moodysalem** [comment]
this seems chrome extension related
