### ISSUE TITLE
Crash report: `NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.`

### ISSUE THREAD

**Issue by eabstract1** [Uniswap/interface#2997]
## URL
  
https://app.uniswap.org/#/swap?outputCurrency=0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2&theme=light&exactAmount=136.56202&exactField=output

## `swap` state
    
```json
{
  "INPUT": {
    "currencyId": "ETH"
  },
  "OUTPUT": {
    "currencyId": "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
  },
  "independentField": "OUTPUT",
  "typedValue": "136.56202",
  "recipient": null
}
```

## Error

```
NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
```

## Stacktrace

```
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at https://app.uniswap.org/static/js/main.d40e0b88.chunk.js:1:378159
    at Fs (https://app.uniswap.org/static/js/34.d906cff3.chunk.js:2:1294624)
    at t.unstable_runWithPriority (https://app.uniswap.org/static/js/34.d906cff3.chunk.js:2:1312538)
    at Gi (https://app.uniswap.org/static/js/34.d906cff3.chunk.js:2:1235078)
    at Ns (https://app.uniswap.org/static/js/34.d906cff3.chunk.js:2:1294220)
    at https://app.uniswap.org/static/js/34.d906cff3.chunk.js:2:1294131
    at L (https://app.uniswap.org/static/js/34.d906cff3.chunk.js:2:1311597)
    at MessagePort._.port1.onmessage (https://app.uniswap.org/static/js/34.d906cff3.chunk.js:2:1310319)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "96.0.4664.93",
    "major": "96"
  },
  "engine": {
    "name": "Blink",
    "version": "96.0.4664.93"
  },
  "os": {
    "name": "Mac OS",
    "version": "10.15.7"
  },
  "device": {},
  "cpu": {}
}
```

**Comment by eabstract1** [comment]
<img width="680" alt="metamask issue" src="https://user-images.githubusercontent.com/96269123/146462291-da0d4aae-aa64-477d-b3d1-888615ce3cf9.png">

**Comment by eabstract1** [comment]
I was trying to convert eth to weth and received this message

**Comment by willhennessy** [comment]
thanks! similar to https://github.com/Uniswap/interface/issues/2481
