### ISSUE TITLE
Crash report: `Error: Unsupported chain ID`

### ISSUE THREAD

**Issue by tonymade8** [Uniswap/interface#3011]
## URL
  
https://app.uniswap.org/#/swap?outputCurrency=0x426ca1ea2406c07d75db9585f22781c096e3d0e0

## `swap` state
    
```json
{
  "INPUT": {
    "currencyId": null
  },
  "OUTPUT": {
    "currencyId": "0x426CA1eA2406c07d75Db9585F22781c096e3d0E0"
  },
  "independentField": "INPUT",
  "typedValue": "",
  "recipient": null
}
```

## Error

```
Error: Unsupported chain ID
```

## Stacktrace

```
Error: Unsupported chain ID
    at n.get (https://app.uniswap.org/static/js/main.9f5a4488.chunk.js:1:172980)
    at c (https://app.uniswap.org/static/js/main.9f5a4488.chunk.js:1:165028)
    at f (https://app.uniswap.org/static/js/main.9f5a4488.chunk.js:1:2118)
    at a.maxHops (https://app.uniswap.org/static/js/main.9f5a4488.chunk.js:1:2986)
    at g (https://app.uniswap.org/static/js/main.9f5a4488.chunk.js:1:3623)
    at Q.u (https://app.uniswap.org/static/js/main.9f5a4488.chunk.js:1:11753)
    at Q (https://app.uniswap.org/static/js/main.9f5a4488.chunk.js:1:12245)
    at Yf (https://app.uniswap.org/static/js/main.9f5a4488.chunk.js:1:762158)
    at oi (https://app.uniswap.org/static/js/34.8c7c00d7.chunk.js:2:2449445)
    at Ji (https://app.uniswap.org/static/js/34.8c7c00d7.chunk.js:2:2459012)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (X11; CrOS x86_64 14150.87.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.124 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "94.0.4606.124",
    "major": "94"
  },
  "engine": {
    "name": "Blink",
    "version": "94.0.4606.124"
  },
  "os": {
    "name": "Chromium OS",
    "version": "14150.87.0"
  },
  "device": {},
  "cpu": {}
}
```

**Comment by tonymade8** [comment]
yea yuhh ya

**Comment by willhennessy** [comment]
https://github.com/Uniswap/interface/issues/2749
