### ISSUE TITLE
Crash report: `TypeError: Cannot read properties of undefined (reading '0')`

### ISSUE THREAD

**Issue by zgris** [Uniswap/interface#3033]
## URL
  
https://app.uniswap.org/#/add/0x2260fac5e5542a773aa44fbcfedf7c193bc2c599/0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2/3000

## `mintV3` state
    
```json
{
  "independentField": "CURRENCY_A",
  "typedValue": "",
  "startPriceTypedValue": "",
  "leftRangeTypedValue": "",
  "rightRangeTypedValue": ""
}
```

## Error

```
TypeError: Cannot read properties of undefined (reading '0')
```

## Stacktrace

```
TypeError: Cannot read properties of undefined (reading '0')
    at https://app.uniswap.org/static/js/main.d86699df.chunk.js:1:438458
    at Array.reduce (<anonymous>)
    at https://app.uniswap.org/static/js/main.d86699df.chunk.js:1:438382
    at Object.Aa [as useMemo] (https://app.uniswap.org/static/js/35.d35d34a0.chunk.js:2:1352918)
    at t.useMemo (https://app.uniswap.org/static/js/35.d35d34a0.chunk.js:2:1287938)
    at https://app.uniswap.org/static/js/main.d86699df.chunk.js:1:438019
    at uv (https://app.uniswap.org/static/js/main.d86699df.chunk.js:1:439348)
    at Wv (https://app.uniswap.org/static/js/main.d86699df.chunk.js:1:445223)
    at ua (https://app.uniswap.org/static/js/35.d35d34a0.chunk.js:2:1348185)
    at Va (https://app.uniswap.org/static/js/35.d35d34a0.chunk.js:2:1357752)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "96.0.4664.110",
    "major": "96"
  },
  "engine": {
    "name": "Blink",
    "version": "96.0.4664.110"
  },
  "os": {
    "name": "Windows",
    "version": "10"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

**Comment by willhennessy** [comment]
https://github.com/Uniswap/interface/issues/2798
