### ISSUE TITLE
Crash report: `TypeError: Cannot read properties of undefined (reading '0')`

### ISSUE THREAD

**Issue by akill317** [Uniswap/interface#3034]
## URL
  
https://app.uniswap.org/#/add/ETH/0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48

## `mintV3` state
    
```json
{
  "independentField": "CURRENCY_A",
  "typedValue": "",
  "startPriceTypedValue": "",
  "leftRangeTypedValue": "",
  "rightRangeTypedValue": ""
}
```

## Error

```
TypeError: Cannot read properties of undefined (reading '0')
```

## Stacktrace

```
TypeError: Cannot read properties of undefined (reading '0')
    at https://app.uniswap.org/static/js/main.8a72fbb9.chunk.js:1:438066
    at Array.reduce (<anonymous>)
    at https://app.uniswap.org/static/js/main.8a72fbb9.chunk.js:1:437990
    at Object.Aa [as useMemo] (https://app.uniswap.org/static/js/35.d35d34a0.chunk.js:2:1352918)
    at t.useMemo (https://app.uniswap.org/static/js/35.d35d34a0.chunk.js:2:1287938)
    at https://app.uniswap.org/static/js/main.8a72fbb9.chunk.js:1:437627
    at uv (https://app.uniswap.org/static/js/main.8a72fbb9.chunk.js:1:438956)
    at Wv (https://app.uniswap.org/static/js/main.8a72fbb9.chunk.js:1:444831)
    at ua (https://app.uniswap.org/static/js/35.d35d34a0.chunk.js:2:1348185)
    at Va (https://app.uniswap.org/static/js/35.d35d34a0.chunk.js:2:1357752)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "96.0.4664.110",
    "major": "96"
  },
  "engine": {
    "name": "Blink",
    "version": "96.0.4664.110"
  },
  "os": {
    "name": "Mac OS",
    "version": "10.15.7"
  },
  "device": {},
  "cpu": {}
}
```

**Comment by willhennessy** [comment]
https://github.com/Uniswap/interface/issues/2798
