### ISSUE TITLE
Crash report: `Error: No V2 factory address on this chain`

### ISSUE THREAD

**Issue by Juliansmulian** [Uniswap/interface#3039]
## URL
  
https://app.uniswap.org/#/pool/v2

## Error

```
Error: No V2 factory address on this chain
```

## Stacktrace

```
Error: No V2 factory address on this chain
    at D (https://app.uniswap.org/static/js/main.26903490.chunk.js:1:329946)
    at https://app.uniswap.org/static/js/main.26903490.chunk.js:1:695850
    at Array.map (<anonymous>)
    at https://app.uniswap.org/static/js/main.26903490.chunk.js:1:695800
    at Object.Ci [as useMemo] (https://app.uniswap.org/static/js/34.e082fabe.chunk.js:2:2458427)
    at https://app.uniswap.org/static/js/34.e082fabe.chunk.js:2:2393446
    at Yp (https://app.uniswap.org/static/js/main.26903490.chunk.js:1:695778)
    at oi (https://app.uniswap.org/static/js/34.e082fabe.chunk.js:2:2453694)
    at Ji (https://app.uniswap.org/static/js/34.e082fabe.chunk.js:2:2463261)
    at Ko (https://app.uniswap.org/static/js/34.e082fabe.chunk.js:2:2506985)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "96.0.4664.110",
    "major": "96"
  },
  "engine": {
    "name": "Blink",
    "version": "96.0.4664.110"
  },
  "os": {
    "name": "Windows",
    "version": "10"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

**Comment by willhennessy** [comment]
please switch you connected chain to Ethereum L1.  v2 is not launched on any other chain
