### ISSUE TITLE
Crash report: `TypeError: Cannot read properties of undefined (reading '0')`

### ISSUE THREAD

**Issue by Leftrin** [Uniswap/interface#3044]
## URL
  
https://app.uniswap.org/#/add/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2/0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599

## `mintV3` state
    
```json
{
  "independentField": "CURRENCY_A",
  "typedValue": "",
  "startPriceTypedValue": "",
  "leftRangeTypedValue": "2024.488350",
  "rightRangeTypedValue": "8097.953400"
}
```

## Error

```
TypeError: Cannot read properties of undefined (reading '0')
```

## Stacktrace

```
TypeError: Cannot read properties of undefined (reading '0')
    at https://app.uniswap.org/static/js/main.da1bd560.chunk.js:1:438562
    at Array.reduce (<anonymous>)
    at https://app.uniswap.org/static/js/main.da1bd560.chunk.js:1:438486
    at Object.Aa [as useMemo] (https://app.uniswap.org/static/js/35.8cc8582a.chunk.js:2:1352918)
    at t.useMemo (https://app.uniswap.org/static/js/35.8cc8582a.chunk.js:2:1287938)
    at https://app.uniswap.org/static/js/main.da1bd560.chunk.js:1:438123
    at uv (https://app.uniswap.org/static/js/main.da1bd560.chunk.js:1:439452)
    at Wv (https://app.uniswap.org/static/js/main.da1bd560.chunk.js:1:445327)
    at ua (https://app.uniswap.org/static/js/35.8cc8582a.chunk.js:2:1348185)
    at Va (https://app.uniswap.org/static/js/35.8cc8582a.chunk.js:2:1357752)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "96.0.4664.110",
    "major": "96"
  },
  "engine": {
    "name": "Blink",
    "version": "96.0.4664.110"
  },
  "os": {
    "name": "Windows",
    "version": "10"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

**Comment by willhennessy** [comment]
https://github.com/Uniswap/interface/issues/2798
