### ISSUE TITLE
Crash report: `Error: No V2 factory address on this chain`

### ISSUE THREAD

**Issue by TheJollyLaMa** [Uniswap/interface#3059]
## URL
  
https://app.uniswap.org/#/pool/v2

## Error

```
Error: No V2 factory address on this chain
```

## Stacktrace

```
Error: No V2 factory address on this chain
    at D (https://app.uniswap.org/static/js/main.26903490.chunk.js:1:329946)
    at https://app.uniswap.org/static/js/main.26903490.chunk.js:1:695850
    at Array.map (<anonymous>)
    at https://app.uniswap.org/static/js/main.26903490.chunk.js:1:695800
    at Object.Ci [as useMemo] (https://app.uniswap.org/static/js/34.e082fabe.chunk.js:2:2458427)
    at t.useMemo (https://app.uniswap.org/static/js/34.e082fabe.chunk.js:2:2393446)
    at Yp (https://app.uniswap.org/static/js/main.26903490.chunk.js:1:695778)
    at oi (https://app.uniswap.org/static/js/34.e082fabe.chunk.js:2:2453694)
    at Ji (https://app.uniswap.org/static/js/34.e082fabe.chunk.js:2:2463261)
    at Ko (https://app.uniswap.org/static/js/34.e082fabe.chunk.js:2:2506985)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "96.0.4664.110",
    "major": "96"
  },
  "engine": {
    "name": "Blink",
    "version": "96.0.4664.110"
  },
  "os": {
    "name": "Mac OS",
    "version": "10.15.7"
  },
  "device": {},
  "cpu": {}
}
```

**Comment by uniyj** [comment]
v2 is only on Ethereum Mainnet. It's not on Optimism, Arbitrum, and Polygon. That's why you will get this error if you had set your wallet network to anything other than Ethereum L1 Mainnet. Not really an issue, so I think you should close this. Thanks.

**Comment by willhennessy** [comment]
ty uniyj!
