### ISSUE TITLE
https://app.uniswap.org/#/pool/v2

### ISSUE THREAD

**Issue by dotcomxtreme1** [Uniswap/interface#3062]
## URL
  
https://app.uniswap.org/#/pool/v2

## Error

```
Error: No V2 factory address on this chain
```

## Stacktrace

```
Error: No V2 factory address on this chain
    at D (https://app.uniswap.org/static/js/main.26903490.chunk.js:1:329946)
    at https://app.uniswap.org/static/js/main.26903490.chunk.js:1:695850
    at Array.map (<anonymous>)
    at https://app.uniswap.org/static/js/main.26903490.chunk.js:1:695800
    at Object.useMemo (https://app.uniswap.org/static/js/34.e082fabe.chunk.js:2:2459659)
    at t.useMemo (https://app.uniswap.org/static/js/34.e082fabe.chunk.js:2:2393446)
    at Yp (https://app.uniswap.org/static/js/main.26903490.chunk.js:1:695778)
    at oi (https://app.uniswap.org/static/js/34.e082fabe.chunk.js:2:2453694)
    at Ko (https://app.uniswap.org/static/js/34.e082fabe.chunk.js:2:2505994)
    at Pu (https://app.uniswap.org/static/js/34.e082fabe.chunk.js:2:2493235)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Linux; Android 10; moto e) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Mobile Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "96.0.4664.45",
    "major": "96"
  },
  "engine": {
    "name": "Blink",
    "version": "96.0.4664.45"
  },
  "os": {
    "name": "Android",
    "version": "10"
  },
  "device": {
    "vendor": "Motorola",
    "model": "moto e",
    "type": "mobile"
  },
  "cpu": {}
}
```

**Comment by uniyj** [comment]
See: https://github.com/Uniswap/interface/issues/3059#issuecomment-1003244231

**Comment by willhennessy** [comment]
ty uniyj!
