### ISSUE TITLE
Crash report: `Error: Unsupported chain ID`

### ISSUE THREAD

**Issue by STZeed** [Uniswap/interface#3063]
## URL
  
https://app.uniswap.org/#/swap

## `swap` state
    
```json
{
  "INPUT": {
    "currencyId": "0x6B175474E89094C44Da98b954EedeAC495271d0F"
  },
  "OUTPUT": {
    "currencyId": "0xCae72A7A0Fd9046cf6b165CA54c9e3a3872109E0"
  },
  "independentField": "OUTPUT",
  "typedValue": "1",
  "recipient": null
}
```

## Error

```
Error: Unsupported chain ID
```

## Stacktrace

```
Error: Unsupported chain ID
    at n.get (https://app.uniswap.org/static/js/main.9f5a4488.chunk.js:1:172980)
    at c (https://app.uniswap.org/static/js/main.9f5a4488.chunk.js:1:165028)
    at f (https://app.uniswap.org/static/js/main.9f5a4488.chunk.js:1:2118)
    at a.maxHops (https://app.uniswap.org/static/js/main.9f5a4488.chunk.js:1:2986)
    at g (https://app.uniswap.org/static/js/main.9f5a4488.chunk.js:1:3623)
    at Q.u (https://app.uniswap.org/static/js/main.9f5a4488.chunk.js:1:11753)
    at Q (https://app.uniswap.org/static/js/main.9f5a4488.chunk.js:1:12245)
    at Yf (https://app.uniswap.org/static/js/main.9f5a4488.chunk.js:1:762158)
    at oi (https://app.uniswap.org/static/js/34.8c7c00d7.chunk.js:2:2449445)
    at Ji (https://app.uniswap.org/static/js/34.8c7c00d7.chunk.js:2:2459012)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (X11; CrOS x86_64 14388.8.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.14 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "98.0.4758.14",
    "major": "98"
  },
  "engine": {
    "name": "Blink",
    "version": "98.0.4758.14"
  },
  "os": {
    "name": "Chromium OS",
    "version": "14388.8.0"
  },
  "device": {},
  "cpu": {}
}
```

**Comment by willhennessy** [comment]
https://github.com/Uniswap/interface/issues/2749

**Comment by tinaszheng** [comment]
hey @STZeed - thanks for reporting this! do you remember which wallet you were using, and which network you were trying to switch to?
