### ISSUE TITLE
Crash report: `TypeError: Cannot read properties of undefined (reading '0')`

### ISSUE THREAD

**Issue by bozkurtdzgn** [Uniswap/interface#3064]
## URL
  
https://app.uniswap.org/#/add/0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48/0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2/3000

## `mintV3` state
    
```json
{
  "independentField": "CURRENCY_A",
  "typedValue": "",
  "startPriceTypedValue": "",
  "leftRangeTypedValue": "",
  "rightRangeTypedValue": ""
}
```

## Error

```
TypeError: Cannot read properties of undefined (reading '0')
```

## Stacktrace

```
TypeError: Cannot read properties of undefined (reading '0')
    at https://app.uniswap.org/static/js/main.8a72fbb9.chunk.js:1:438066
    at Array.reduce (<anonymous>)
    at https://app.uniswap.org/static/js/main.8a72fbb9.chunk.js:1:437990
    at Object.Aa [as useMemo] (https://app.uniswap.org/static/js/35.d35d34a0.chunk.js:2:1352918)
    at t.useMemo (https://app.uniswap.org/static/js/35.d35d34a0.chunk.js:2:1287938)
    at https://app.uniswap.org/static/js/main.8a72fbb9.chunk.js:1:437627
    at uv (https://app.uniswap.org/static/js/main.8a72fbb9.chunk.js:1:438956)
    at Wv (https://app.uniswap.org/static/js/main.8a72fbb9.chunk.js:1:444831)
    at ua (https://app.uniswap.org/static/js/35.d35d34a0.chunk.js:2:1348185)
    at Va (https://app.uniswap.org/static/js/35.d35d34a0.chunk.js:2:1357752)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36 OPR/82.0.4227.43",
  "browser": {
    "name": "Opera",
    "version": "82.0.4227.43",
    "major": "82"
  },
  "engine": {
    "name": "Blink",
    "version": "96.0.4664.110"
  },
  "os": {
    "name": "Windows",
    "version": "10"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

**Comment by willhennessy** [comment]
https://github.com/Uniswap/interface/issues/2798
