### ISSUE TITLE
Crash report: `TypeError: Cannot read properties of undefined (reading '0')`

### ISSUE THREAD

**Issue by mionet0304** [Uniswap/interface#3101]
## URL
  
https://exchange.uniswap-finance.org/#/add/ETH/0x6B175474E89094C44Da98b954EedeAC495271d0F

## `mintV3` state
    
```json
{
  "independentField": "CURRENCY_A",
  "typedValue": "",
  "startPriceTypedValue": "",
  "leftRangeTypedValue": "",
  "rightRangeTypedValue": ""
}
```

## Error

```
TypeError: Cannot read properties of undefined (reading '0')
```

## Stacktrace

```
TypeError: Cannot read properties of undefined (reading '0')
    at https://exchange.uniswap-finance.org/static/js/main.106f9307.chunk.js:1:340125
    at Array.reduce (<anonymous>)
    at https://exchange.uniswap-finance.org/static/js/main.106f9307.chunk.js:1:340049
    at Object.Ao [as useMemo] (https://exchange.uniswap-finance.org/static/js/4.fa5b14d6.chunk.js:2:1556178)
    at t.useMemo (https://exchange.uniswap-finance.org/static/js/4.fa5b14d6.chunk.js:2:1475650)
    at https://exchange.uniswap-finance.org/static/js/main.106f9307.chunk.js:1:339686
    at wv (https://exchange.uniswap-finance.org/static/js/main.106f9307.chunk.js:1:341007)
    at Av (https://exchange.uniswap-finance.org/static/js/main.106f9307.chunk.js:1:343145)
    at ro (https://exchange.uniswap-finance.org/static/js/4.fa5b14d6.chunk.js:2:1551445)
    at Uo (https://exchange.uniswap-finance.org/static/js/4.fa5b14d6.chunk.js:2:1561012)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "96.0.4664.110",
    "major": "96"
  },
  "engine": {
    "name": "Blink",
    "version": "96.0.4664.110"
  },
  "os": {
    "name": "Windows",
    "version": "10"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

**Comment by willhennessy** [comment]
hi, https://exchange.uniswap-finance.org is a fork/clone of our website so we can't help you here
