### ISSUE TITLE
Crash report: `NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.`

### ISSUE THREAD

**Issue by LAOWANG651407** [Uniswap/interface#3126]
## URL
  
https://uniswap.v2.testnet.pulsechain.com/#/swap

## `swap` state
    
```json
{
  "INPUT": {
    "currencyId": "ETH"
  },
  "OUTPUT": {
    "currencyId": "0xdAC17F958D2ee523a2206206994597C13D831ec7"
  },
  "independentField": "INPUT",
  "typedValue": "",
  "recipient": null
}
```

## Error

```
NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
```

## Stacktrace

```
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at Eu (https://uniswap.v2.testnet.pulsechain.com/static/js/35.292bdf8d.chunk.js:2:1246801)
    at Is (https://uniswap.v2.testnet.pulsechain.com/static/js/35.292bdf8d.chunk.js:2:1258591)
    at https://uniswap.v2.testnet.pulsechain.com/static/js/35.292bdf8d.chunk.js:2:1279141
    at Wi (https://uniswap.v2.testnet.pulsechain.com/static/js/35.292bdf8d.chunk.js:2:1201681)
    at Cs (https://uniswap.v2.testnet.pulsechain.com/static/js/35.292bdf8d.chunk.js:2:1256549)
    at bs (https://uniswap.v2.testnet.pulsechain.com/static/js/35.292bdf8d.chunk.js:2:1252635)
    at https://uniswap.v2.testnet.pulsechain.com/static/js/35.292bdf8d.chunk.js:2:1201904
    at https://uniswap.v2.testnet.pulsechain.com/static/js/35.292bdf8d.chunk.js:2:1279141
    at Wi (https://uniswap.v2.testnet.pulsechain.com/static/js/35.292bdf8d.chunk.js:2:1201681)
    at Xi (https://uniswap.v2.testnet.pulsechain.com/static/js/35.292bdf8d.chunk.js:2:1201849)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "96.0.4664.93",
    "major": "96"
  },
  "engine": {
    "name": "Blink",
    "version": "96.0.4664.93"
  },
  "os": {
    "name": "Windows",
    "version": "7"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

**Comment by willhennessy** [comment]
hi the URL in this report is a fork/clone of the uniswap app so we can't help here
