### ISSUE TITLE
Crash report: `Error: invalid BigNumber string (argument="value", value="[8476]", code=INVALID_ARGUMENT, version=bignumber/5.5.0)`

### ISSUE THREAD

**Issue by dowen11720** [Uniswap/interface#3128]
## URL
  
https://app.uniswap.org/#/swap?outputCurrency=0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2

## `swap` state
    
```json
{
  "INPUT": {
    "currencyId": null
  },
  "OUTPUT": {
    "currencyId": "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
  },
  "independentField": "INPUT",
  "typedValue": "",
  "recipient": null
}
```

## Error

```
Error: invalid BigNumber string (argument="value", value="[8476]", code=INVALID_ARGUMENT, version=bignumber/5.5.0)
```

## Stacktrace

```
Error: invalid BigNumber string (argument="value", value="[8476]", code=INVALID_ARGUMENT, version=bignumber/5.5.0)
    at e.value (https://app.uniswap.org/static/js/35.1187b454.chunk.js:2:194569)
    at e.value (https://app.uniswap.org/static/js/35.1187b454.chunk.js:2:194713)
    at e.value (https://app.uniswap.org/static/js/35.1187b454.chunk.js:2:194792)
    at Function.value (https://app.uniswap.org/static/js/35.1187b454.chunk.js:2:351238)
    at Nn (https://app.uniswap.org/static/js/main.933b5393.chunk.js:1:421069)
    at Rn (https://app.uniswap.org/static/js/main.933b5393.chunk.js:1:419899)
    at https://app.uniswap.org/static/js/main.933b5393.chunk.js:1:422064
    at Ln (https://app.uniswap.org/static/js/main.933b5393.chunk.js:1:422287)
    at oa (https://app.uniswap.org/static/js/35.1187b454.chunk.js:2:2918675)
    at Ha (https://app.uniswap.org/static/js/35.1187b454.chunk.js:2:2928242)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "96.0.4664.110",
    "major": "96"
  },
  "engine": {
    "name": "Blink",
    "version": "96.0.4664.110"
  },
  "os": {
    "name": "Windows",
    "version": "10"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

**Comment by willhennessy** [comment]
https://github.com/Uniswap/interface/issues/2729
