### ISSUE TITLE
Crash report: `TypeError: Cannot read properties of undefined (reading '0')`

### ISSUE THREAD

**Issue by mcsaygili** [Uniswap/interface#3131]
## URL
  
https://app.uniswap.org/#/add/0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48/0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2/3000

## `mintV3` state
    
```json
{
  "independentField": "CURRENCY_A",
  "typedValue": "",
  "startPriceTypedValue": "",
  "leftRangeTypedValue": "",
  "rightRangeTypedValue": ""
}
```

## Error

```
TypeError: Cannot read properties of undefined (reading '0')
```

## Stacktrace

```
TypeError: Cannot read properties of undefined (reading '0')
    at https://app.uniswap.org/static/js/main.acb943af.chunk.js:1:427840
    at Array.reduce (<anonymous>)
    at https://app.uniswap.org/static/js/main.acb943af.chunk.js:1:427764
    at Object.Aa [as useMemo] (https://app.uniswap.org/static/js/35.5505b0d5.chunk.js:2:1196609)
    at t.useMemo (https://app.uniswap.org/static/js/35.5505b0d5.chunk.js:2:1131629)
    at https://app.uniswap.org/static/js/main.acb943af.chunk.js:1:427401
    at Bg (https://app.uniswap.org/static/js/main.acb943af.chunk.js:1:428730)
    at hv (https://app.uniswap.org/static/js/main.acb943af.chunk.js:1:434587)
    at ua (https://app.uniswap.org/static/js/35.5505b0d5.chunk.js:2:1191876)
    at Ha (https://app.uniswap.org/static/js/35.5505b0d5.chunk.js:2:1201443)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "97.0.4692.71",
    "major": "97"
  },
  "engine": {
    "name": "Blink",
    "version": "97.0.4692.71"
  },
  "os": {
    "name": "Windows",
    "version": "10"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

**Comment by willhennessy** [comment]
https://github.com/Uniswap/interface/issues/2798
