### ISSUE TITLE
Crash report: `NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.`

### ISSUE THREAD

**Issue by kaka175** [Uniswap/interface#3140]
## URL
  
https://app.uniswap.org/#/swap

## `swap` state
    
```json
{
  "INPUT": {
    "currencyId": "ETH"
  },
  "OUTPUT": {
    "currencyId": "0xFd086bC7CD5C481DCC9C85ebE478A1C0b69FCbb9"
  },
  "independentField": "INPUT",
  "typedValue": "0.01",
  "recipient": null
}
```

## Error

```
NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
```

## Stacktrace

```
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at Ao (https://app.uniswap.org/static/js/35.812921a6.chunk.js:2:2984038)
    at Mu (https://app.uniswap.org/static/js/35.812921a6.chunk.js:2:2995828)
    at https://app.uniswap.org/static/js/35.812921a6.chunk.js:2:3016378
    at Vi (https://app.uniswap.org/static/js/35.812921a6.chunk.js:2:2938918)
    at Ru (https://app.uniswap.org/static/js/35.812921a6.chunk.js:2:2993786)
    at wu (https://app.uniswap.org/static/js/35.812921a6.chunk.js:2:2989872)
    at https://app.uniswap.org/static/js/35.812921a6.chunk.js:2:2939141
    at https://app.uniswap.org/static/js/35.812921a6.chunk.js:2:3016378
    at Vi (https://app.uniswap.org/static/js/35.812921a6.chunk.js:2:2938918)
    at Ki (https://app.uniswap.org/static/js/35.812921a6.chunk.js:2:2939086)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "96.0.4664.45",
    "major": "96"
  },
  "engine": {
    "name": "Blink",
    "version": "96.0.4664.45"
  },
  "os": {
    "name": "Windows",
    "version": "7"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

**Comment by willhennessy** [comment]
https://github.com/Uniswap/interface/issues/2481
