### ISSUE TITLE
Crash report: `Error: Unsupported chain ID`

### ISSUE THREAD

**Issue by Magerk3** [Uniswap/interface#3154]
## URL
  
https://kiba.app/#/swap

## `swap` state
    
```json
{
  "INPUT": {
    "currencyId": "ETH"
  },
  "OUTPUT": {
    "currencyId": ""
  },
  "independentField": "INPUT",
  "typedValue": "",
  "recipient": null,
  "useOtherAddress": false
}
```

## Error

```
Error: Unsupported chain ID
```

## Stacktrace

```
Error: Unsupported chain ID
    at n.get (https://kiba.app/static/js/main.53a60bcc.chunk.js:1:24437)
    at Wl (https://kiba.app/static/js/main.53a60bcc.chunk.js:1:172623)
    at Gl (https://kiba.app/static/js/main.53a60bcc.chunk.js:1:174842)
    at Kl (https://kiba.app/static/js/main.53a60bcc.chunk.js:1:175372)
    at Yb (https://kiba.app/static/js/main.53a60bcc.chunk.js:1:259475)
    at QS (https://kiba.app/static/js/main.53a60bcc.chunk.js:1:705944)
    at ia (https://kiba.app/static/js/4.2c2f3611.chunk.js:2:5036319)
    at za (https://kiba.app/static/js/4.2c2f3611.chunk.js:2:5045886)
    at Vs (https://kiba.app/static/js/4.2c2f3611.chunk.js:2:5089768)
    at Su (https://kiba.app/static/js/4.2c2f3611.chunk.js:2:5075951)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "97.0.4692.71",
    "major": "97"
  },
  "engine": {
    "name": "Blink",
    "version": "97.0.4692.71"
  },
  "os": {
    "name": "Mac OS",
    "version": "10.15.7"
  },
  "device": {},
  "cpu": {}
}
```

**Comment by willhennessy** [comment]
hi, kiba.app is a fork of uniswap so we can't help here
