### ISSUE TITLE
Happening for a few days: Crash report: `Error: invalid BigNumber string (argument="value", value=" 6058", code=INVALID_ARGUMENT, version=bignumber/5.5.0)`

### ISSUE THREAD

**Issue by leandercapuozzo** [Uniswap/interface#3171]
## URL
  
https://app.uniswap.org/#/swap

## `swap` state
    
```json
{
  "INPUT": {
    "currencyId": "ETH"
  },
  "OUTPUT": {
    "currencyId": null
  },
  "independentField": "INPUT",
  "typedValue": "",
  "recipient": null
}
```

## Error

```
Error: invalid BigNumber string (argument="value", value=" 6058", code=INVALID_ARGUMENT, version=bignumber/5.5.0)
```

## Stacktrace

```
Error: invalid BigNumber string (argument="value", value=" 6058", code=INVALID_ARGUMENT, version=bignumber/5.5.0)
    at e.value (https://app.uniswap.org/static/js/35.5699eabb.chunk.js:2:193072)
    at e.value (https://app.uniswap.org/static/js/35.5699eabb.chunk.js:2:193216)
    at e.value (https://app.uniswap.org/static/js/35.5699eabb.chunk.js:2:193295)
    at Function.value (https://app.uniswap.org/static/js/35.5699eabb.chunk.js:2:348293)
    at Mn (https://app.uniswap.org/static/js/main.d22dc713.chunk.js:1:410497)
    at Un (https://app.uniswap.org/static/js/main.d22dc713.chunk.js:1:409327)
    at https://app.uniswap.org/static/js/main.d22dc713.chunk.js:1:411492
    at Bn (https://app.uniswap.org/static/js/main.d22dc713.chunk.js:1:411715)
    at oa (https://app.uniswap.org/static/js/35.5699eabb.chunk.js:2:2953359)
    at Ha (https://app.uniswap.org/static/js/35.5699eabb.chunk.js:2:2962926)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "97.0.4692.71",
    "major": "97"
  },
  "engine": {
    "name": "Blink",
    "version": "97.0.4692.71"
  },
  "os": {
    "name": "Windows",
    "version": "10"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

**Comment by leandercapuozzo** [comment]
Loading swap with my wallet connected.
Page loads for about 2 sec before the interface is replaced with this error.
As long as wallet isn't connected loads fine.
I've cmd shift reloaded, cleared browsing data im on Chrome on windows. 

I'm assuming I have a problem coin in my wallet but not sure. I am able to use uniswap on mobile with this wallet no issue.

**Comment by willhennessy** [comment]
Thanks for the info. We've seen reports of this a few times but didn't know how to repro. I'll have someone take a look next week
