### ISSUE TITLE
Crash report: `NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.`

### ISSUE THREAD

**Issue by panda1114Git** [Uniswap/interface#3200]
## URL
  
https://app.uniswap.org/#/swap?outputCurrency=0xbea98c05eeae2f3bc8c3565db7551eb738c8ccab&inputCurrency=ETH&use=V2&chain=kovan

## `swap` state
    
```json
{
  "INPUT": {
    "currencyId": "ETH"
  },
  "OUTPUT": {
    "currencyId": "0xbEa98c05eEAe2f3bC8c3565Db7551Eb738c8CCAb"
  },
  "independentField": "INPUT",
  "typedValue": "",
  "recipient": null
}
```

## Error

```
NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
```

## Stacktrace

```
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at Ao (https://app.uniswap.org/static/js/35.d7634141.chunk.js:2:2984670)
    at Mu (https://app.uniswap.org/static/js/35.d7634141.chunk.js:2:2996460)
    at https://app.uniswap.org/static/js/35.d7634141.chunk.js:2:3017010
    at Vi (https://app.uniswap.org/static/js/35.d7634141.chunk.js:2:2939550)
    at Ru (https://app.uniswap.org/static/js/35.d7634141.chunk.js:2:2994418)
    at wu (https://app.uniswap.org/static/js/35.d7634141.chunk.js:2:2990504)
    at https://app.uniswap.org/static/js/35.d7634141.chunk.js:2:2939773
    at https://app.uniswap.org/static/js/35.d7634141.chunk.js:2:3017010
    at Vi (https://app.uniswap.org/static/js/35.d7634141.chunk.js:2:2939550)
    at Ki (https://app.uniswap.org/static/js/35.d7634141.chunk.js:2:2939718)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "97.0.4692.99",
    "major": "97"
  },
  "engine": {
    "name": "Blink",
    "version": "97.0.4692.99"
  },
  "os": {
    "name": "Windows",
    "version": "10"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

**Comment by willhennessy** [comment]
https://github.com/Uniswap/interface/issues/2481
