### ISSUE TITLE
Crash report: `NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.`

### ISSUE THREAD

**Issue by lightninglu10** [Uniswap/interface#3218]
## URL
  
https://app.uniswap.org/#/swap

## `swap` state
    
```json
{
  "INPUT": {
    "currencyId": "ETH"
  },
  "OUTPUT": {
    "currencyId": null
  },
  "independentField": "INPUT",
  "typedValue": "",
  "recipient": null
}
```

## Error

```
NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
```

## Stacktrace

```
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at https://app.uniswap.org/static/js/main.d40e0b88.chunk.js:1:378159
    at Fs (https://app.uniswap.org/static/js/34.d906cff3.chunk.js:2:1294624)
    at t.unstable_runWithPriority (https://app.uniswap.org/static/js/34.d906cff3.chunk.js:2:1312538)
    at Gi (https://app.uniswap.org/static/js/34.d906cff3.chunk.js:2:1235078)
    at Ns (https://app.uniswap.org/static/js/34.d906cff3.chunk.js:2:1294220)
    at https://app.uniswap.org/static/js/34.d906cff3.chunk.js:2:1294131
    at L (https://app.uniswap.org/static/js/34.d906cff3.chunk.js:2:1311597)
    at MessagePort._.port1.onmessage (https://app.uniswap.org/static/js/34.d906cff3.chunk.js:2:1310319)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Mobile Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "97.0.4692.99",
    "major": "97"
  },
  "engine": {
    "name": "Blink",
    "version": "97.0.4692.99"
  },
  "os": {
    "name": "Android",
    "version": "6.0"
  },
  "device": {
    "vendor": "LG",
    "model": "Nexus 5",
    "type": "mobile"
  },
  "cpu": {}
}
```

**Comment by lightninglu10** [comment]
Closing as not planned: this is an auto-generated 2022 crash report against a long-superseded bundle, with no repro and no follow-up. Please open a fresh issue if a similar crash occurs on the current app.
