### ISSUE TITLE
Failed to activate locale ru-RU

### ISSUE THREAD

**Issue by dappdappgo** [Uniswap/interface#3296]
![image](https://user-images.githubusercontent.com/97635469/153629931-1f675538-e336-42cd-8932-11f792f54e28.png)

```
i18n.tsx:103 Failed to activate locale ru-RU ReferenceError: process is not defined
    at i18n.tsx:86:25
    at c (runtime.js:63:40)
    at Generator._invoke (runtime.js:294:22)
    at Generator.next (runtime.js:119:21)
    at f (asyncToGenerator.js:3:20)
    at o (asyncToGenerator.js:25:9)
    at asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at asyncToGenerator.js:21:12
    at p (i18n.tsx:79:1)
(anonymous) @ i18n.tsx:103
Promise.catch (async)
(anonymous) @ i18n.tsx:102
Lu @ react-dom.production.min.js:262
(anonymous) @ scheduler.production.min.js:18
Vr @ react-dom.production.min.js:122
Cu @ react-dom.production.min.js:261
wu @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
(anonymous) @ scheduler.production.min.js:18
Vr @ react-dom.production.min.js:122
Zr @ react-dom.production.min.js:123
Kr @ react-dom.production.min.js:122
Tu @ react-dom.production.min.js:244
os @ react-dom.production.min.js:289
(anonymous) @ react-dom.production.min.js:296
1045 @ index.tsx:50
n @ (index):1
f @ (index):1
c @ (index):1
(anonymous) @ main.5e704007.chunk.js:1
i18n.tsx:86 Uncaught (in promise) ReferenceError: process is not defined
    at i18n.tsx:86:25
    at c (runtime.js:63:40)
    at Generator._invoke (runtime.js:294:22)
    at Generator.next (runtime.js:119:21)
    at f (asyncToGenerator.js:3:20)
    at o (asyncToGenerator.js:25:9)
    at asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at asyncToGenerator.js:21:12
    at j (main.5e704007.chunk.js:1:596315)
```

**Comment by zzmp** [comment]
Fixed in #3299, releasing rn
