### ISSUE TITLE
Crash report: `Error: [big.js] Division by zero`

### ISSUE THREAD

**Issue by pcgandhinj466** [Uniswap/interface#3541]
## URL
  
https://app.uniswap.org/#/vote/2/12

## Error

```
Error: [big.js] Division by zero
```

## Stacktrace

```
Error: [big.js] Division by zero
    at t.div (https://app.uniswap.org/static/js/3.b710edae.chunk.js:2:2239433)
    at e.toFixed (https://app.uniswap.org/static/js/3.b710edae.chunk.js:2:65053)
    at sn (https://app.uniswap.org/static/js/10.69d3c5d9.chunk.js:1:67308)
    at oi (https://app.uniswap.org/static/js/3.b710edae.chunk.js:2:3033362)
    at Xo (https://app.uniswap.org/static/js/3.b710edae.chunk.js:2:3085662)
    at Fu (https://app.uniswap.org/static/js/3.b710edae.chunk.js:2:3072903)
    at _u (https://app.uniswap.org/static/js/3.b710edae.chunk.js:2:3072831)
    at Eu (https://app.uniswap.org/static/js/3.b710edae.chunk.js:2:3072694)
    at wu (https://app.uniswap.org/static/js/3.b710edae.chunk.js:2:3069660)
    at https://app.uniswap.org/static/js/3.b710edae.chunk.js:2:3019154
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "99.0.4844.74",
    "major": "99"
  },
  "engine": {
    "name": "Blink",
    "version": "99.0.4844.74"
  },
  "os": {
    "name": "Windows",
    "version": "10"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

**Comment by pcgandhinj466** [comment]
FIX

**Comment by pcgandhinj466** [comment]
FIX
