### ISSUE TITLE
Crash report: `TypeError: Cannot read properties of undefined (reading 'split')`

### ISSUE THREAD

**Issue by yangyuan6** [Uniswap/interface#3544]
## URL
  
https://app.uniswap.org/#/vote?chain=mainnet

## Error

```
TypeError: Cannot read properties of undefined (reading 'split')
```

## Stacktrace

```
TypeError: Cannot read properties of undefined (reading 'split')
    at https://app.uniswap.org/static/js/105.cf3fa6d7.chunk.js:1:16030
    at Array.map (<anonymous>)
    at https://app.uniswap.org/static/js/105.cf3fa6d7.chunk.js:1:15851
    at Array.map (<anonymous>)
    at https://app.uniswap.org/static/js/105.cf3fa6d7.chunk.js:1:15291
    at Object._i [as useMemo] (https://app.uniswap.org/static/js/96.eb45b585.chunk.js:2:3463300)
    at t.useMemo (https://app.uniswap.org/static/js/96.eb45b585.chunk.js:2:3387662)
    at J (https://app.uniswap.org/static/js/105.cf3fa6d7.chunk.js:1:15015)
    at ne (https://app.uniswap.org/static/js/105.cf3fa6d7.chunk.js:1:16957)
    at kt (https://app.uniswap.org/static/js/105.cf3fa6d7.chunk.js:1:51064)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "99.0.4844.74",
    "major": "99"
  },
  "engine": {
    "name": "Blink",
    "version": "99.0.4844.74"
  },
  "os": {
    "name": "Mac OS",
    "version": "10.15.7"
  },
  "device": {},
  "cpu": {}
}
```

**Comment by zhyd1997** [comment]
the bug has been fixed by PR #3518

and it can not be reproduced (tested by Browerstack):
<img width="934" alt="device data" src="https://user-images.githubusercontent.com/31362988/159002471-cdb59697-aa76-4ed7-a0af-4f21f2a1ad98.png">
<img width="1075" alt="vote page" src="https://user-images.githubusercontent.com/31362988/159002492-0f280e3e-d683-459e-9e41-31b33bdbe76f.png">
