### ISSUE TITLE
Crash report: `TypeError: Cannot read properties of undefined (reading 'split')`

### ISSUE THREAD

**Issue by varseb** [Uniswap/interface#3555]
## URL
  
https://app.uniswap.org/#/vote

## Error

```
TypeError: Cannot read properties of undefined (reading 'split')
```

## Stacktrace

```
TypeError: Cannot read properties of undefined (reading 'split')
    at https://app.uniswap.org/static/js/77.16bce8a1.chunk.js:1:2904
    at Array.map (<anonymous>)
    at https://app.uniswap.org/static/js/77.16bce8a1.chunk.js:1:2725
    at Array.map (<anonymous>)
    at https://app.uniswap.org/static/js/77.16bce8a1.chunk.js:1:2165
    at Object.Aa [as useMemo] (https://app.uniswap.org/static/js/34.851e919d.chunk.js:2:1274064)
    at t.useMemo (https://app.uniswap.org/static/js/34.851e919d.chunk.js:2:1209083)
    at z (https://app.uniswap.org/static/js/77.16bce8a1.chunk.js:1:1889)
    at K (https://app.uniswap.org/static/js/77.16bce8a1.chunk.js:1:3650)
    at Ot (https://app.uniswap.org/static/js/77.16bce8a1.chunk.js:1:37572)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "98.0.4758.102",
    "major": "98"
  },
  "engine": {
    "name": "Blink",
    "version": "98.0.4758.102"
  },
  "os": {
    "name": "Mac OS",
    "version": "10.15.7"
  },
  "device": {},
  "cpu": {}
}
```

**Comment by zhyd1997** [comment]
Try this link:
https://interface-git-fork-zhyd1997-yadong-issues-3506-3-4fca52-uniswap.vercel.app/

**Comment by zhyd1997** [comment]
Just test if the page can be opened, do not do some transactions.
