### ISSUE TITLE
Crash report: `Error: invalid BigNumber string (argument="value", value=" 6058", code=INVALID_ARGUMENT, version=bignumber/5.6.0)`

### ISSUE THREAD

**Issue by leandercapuozzo** [Uniswap/interface#3644]
## URL
  
https://app.uniswap.org/#/pool?chain=mainnet

## Error

```
Error: invalid BigNumber string (argument="value", value=" 6058", code=INVALID_ARGUMENT, version=bignumber/5.6.0)
```

## Stacktrace

```
Error: invalid BigNumber string (argument="value", value=" 6058", code=INVALID_ARGUMENT, version=bignumber/5.6.0)
    at e.value (https://app.uniswap.org/static/js/3.2e02069c.chunk.js:2:84180)
    at e.value (https://app.uniswap.org/static/js/3.2e02069c.chunk.js:2:84324)
    at e.value (https://app.uniswap.org/static/js/3.2e02069c.chunk.js:2:84403)
    at Function.value (https://app.uniswap.org/static/js/3.2e02069c.chunk.js:2:184433)
    at Bn (https://app.uniswap.org/static/js/main.f9a418a9.chunk.js:1:363536)
    at Mn (https://app.uniswap.org/static/js/main.f9a418a9.chunk.js:1:362366)
    at https://app.uniswap.org/static/js/main.f9a418a9.chunk.js:1:364612
    at Fn (https://app.uniswap.org/static/js/main.f9a418a9.chunk.js:1:364835)
    at oa (https://app.uniswap.org/static/js/3.2e02069c.chunk.js:2:2098555)
    at za (https://app.uniswap.org/static/js/3.2e02069c.chunk.js:2:2108122)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.84 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "99.0.4844.84",
    "major": "99"
  },
  "engine": {
    "name": "Blink",
    "version": "99.0.4844.84"
  },
  "os": {
    "name": "Windows",
    "version": "10"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

**Comment by wpitallo** [comment]
I am also getting this and it used to work
