### ISSUE TITLE
Crash report: `Error: Missing four byte sig`

### ISSUE THREAD

**Issue by Hayden0323** [Uniswap/interface#3648]
## URL
  
https://app.uniswap.org/#/vote?chain=mainnet

## Error

```
Error: Missing four byte sig
```

## Stacktrace

```
Error: Missing four byte sig
    at https://app.uniswap.org/static/js/10.79ed991b.chunk.js:1:16511
    at Array.map (<anonymous>)
    at https://app.uniswap.org/static/js/10.79ed991b.chunk.js:1:16398
    at Array.map (<anonymous>)
    at https://app.uniswap.org/static/js/10.79ed991b.chunk.js:1:15838
    at Object._i [as useMemo] (https://app.uniswap.org/static/js/3.b710edae.chunk.js:2:3038095)
    at t.useMemo (https://app.uniswap.org/static/js/3.b710edae.chunk.js:2:2942127)
    at ae (https://app.uniswap.org/static/js/10.79ed991b.chunk.js:1:15561)
    at re (https://app.uniswap.org/static/js/10.79ed991b.chunk.js:1:17548)
    at Pt (https://app.uniswap.org/static/js/10.79ed991b.chunk.js:1:52709)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.84 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "99.0.4844.84",
    "major": "99"
  },
  "engine": {
    "name": "Blink",
    "version": "99.0.4844.84"
  },
  "os": {
    "name": "Mac OS",
    "version": "10.15.7"
  },
  "device": {},
  "cpu": {}
}
```

**Comment by NoahZinsmeister** [comment]
this is fixed! please hard refresh the app
