### ISSUE TITLE
Crash report: `TypeError: Cannot read properties of undefined (reading 'split')`

### ISSUE THREAD

**Issue by johannafransn** [Uniswap/interface#3716]
## URL
  
https://app.uniswap.org/#/vote

## Error

```
TypeError: Cannot read properties of undefined (reading 'split')
```

## Stacktrace

```
TypeError: Cannot read properties of undefined (reading 'split')
    at https://app.uniswap.org/static/js/78.0d57fd78.chunk.js:1:2906
    at Array.map (<anonymous>)
    at https://app.uniswap.org/static/js/78.0d57fd78.chunk.js:1:2727
    at Array.map (<anonymous>)
    at https://app.uniswap.org/static/js/78.0d57fd78.chunk.js:1:2167
    at Object.Ci [as useMemo] (https://app.uniswap.org/static/js/34.e082fabe.chunk.js:2:2458427)
    at https://app.uniswap.org/static/js/34.e082fabe.chunk.js:2:2393446
    at q (https://app.uniswap.org/static/js/78.0d57fd78.chunk.js:1:1891)
    at K (https://app.uniswap.org/static/js/78.0d57fd78.chunk.js:1:3652)
    at Ot (https://app.uniswap.org/static/js/78.0d57fd78.chunk.js:1:37747)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "94.0.4606.71",
    "major": "94"
  },
  "engine": {
    "name": "Blink",
    "version": "94.0.4606.71"
  },
  "os": {
    "name": "Mac OS",
    "version": "10.15.6"
  },
  "device": {},
  "cpu": {}
}
```

**Comment by Hakeemmidan** [comment]
This issue has just happened to me as well


## Device data

```json
{
  "ua": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "100.0.4896.127",
    "major": "100"
  },
  "engine": {
    "name": "Blink",
    "version": "100.0.4896.127"
  },
  "os": {
    "name": "Mac OS",
    "version": "10.15.7"
  },
  "device": {},
  "cpu": {}
}
```
