### ISSUE TITLE
Crash report: `TypeError: Cannot read properties of undefined (reading 'split')`

### ISSUE THREAD

**Issue by manish8561** [Uniswap/interface#3732]
## URL
  
https://app.uniswap.org/#/vote

## Error

```
TypeError: Cannot read properties of undefined (reading 'split')
```

## Stacktrace

```
TypeError: Cannot read properties of undefined (reading 'split')
    at https://app.uniswap.org/static/js/78.526c1758.chunk.js:1:2906
    at Array.map (<anonymous>)
    at https://app.uniswap.org/static/js/78.526c1758.chunk.js:1:2727
    at Array.map (<anonymous>)
    at https://app.uniswap.org/static/js/78.526c1758.chunk.js:1:2167
    at Object.useMemo (https://app.uniswap.org/static/js/34.c9c0ed5a.chunk.js:2:2455410)
    at t.useMemo (https://app.uniswap.org/static/js/34.c9c0ed5a.chunk.js:2:2389197)
    at q (https://app.uniswap.org/static/js/78.526c1758.chunk.js:1:1891)
    at K (https://app.uniswap.org/static/js/78.526c1758.chunk.js:1:3652)
    at Ot (https://app.uniswap.org/static/js/78.526c1758.chunk.js:1:37747)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.88 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "100.0.4896.88",
    "major": "100"
  },
  "engine": {
    "name": "Blink",
    "version": "100.0.4896.88"
  },
  "os": {
    "name": "Linux",
    "version": "x86_64"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

**Comment by manish8561** [comment]
There is issue in the vote section of the uniswap
