### ISSUE TITLE
Crash report: `NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.`

### ISSUE THREAD

**Issue by 469022** [Uniswap/interface#3877]
## URL
  
https://app.uniswap.org/#/add/ETH/0x3a8B787f78D775AECFEEa15706D4221B40F345AB/3000?chain=arbitrum&minPrice=14494.400000&maxPrice=110783.024020

## `mintV3` state
    
```json
{
  "independentField": "CURRENCY_B",
  "typedValue": "26.908941796400789726",
  "startPriceTypedValue": "",
  "leftRangeTypedValue": "14494.400000",
  "rightRangeTypedValue": "110783.024020"
}
```

## Error

```
NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
```

## Stacktrace

```
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at xo (https://app.uniswap.org/static/js/3.dbad261b.chunk.js:2:1944504)
    at Cu (https://app.uniswap.org/static/js/3.dbad261b.chunk.js:2:1956294)
    at t.unstable_runWithPriority (https://app.uniswap.org/static/js/3.dbad261b.chunk.js:2:1976844)
    at Kf (https://app.uniswap.org/static/js/3.dbad261b.chunk.js:2:1899384)
    at Iu (https://app.uniswap.org/static/js/3.dbad261b.chunk.js:2:1954252)
    at wu (https://app.uniswap.org/static/js/3.dbad261b.chunk.js:2:1950338)
    at https://app.uniswap.org/static/js/3.dbad261b.chunk.js:2:1899607
    at t.unstable_runWithPriority (https://app.uniswap.org/static/js/3.dbad261b.chunk.js:2:1976844)
    at Kf (https://app.uniswap.org/static/js/3.dbad261b.chunk.js:2:1899384)
    at Xf (https://app.uniswap.org/static/js/3.dbad261b.chunk.js:2:1899552)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.63 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "102.0.5005.63",
    "major": "102"
  },
  "engine": {
    "name": "Blink",
    "version": "102.0.5005.63"
  },
  "os": {
    "name": "Windows",
    "version": "7"
  },
  "device": {},
  "cpu": {}
}
```

**Comment by 469022** [comment]
dead
