### ISSUE TITLE
[Bug Report ]adding token 0xc5102fe9359fd9a28f877a67e36b0f050d81a3cc or searching for HOP

### ISSUE THREAD

**Issue by WGB5445** [Uniswap/interface#3904]
**Bug Description**
I want to exchange HOP  
When adding token 0xc5102fe9359fd9a28f877a67e36b0f050d81a3cc or searching for HOP, the page reports an error
```
Error: Invalid token address: 0xc5102fE9359FD9a28f877a67E36B0F050d81a3cc
    at e.get (https://app.uniswap.org/static/js/main.896c38e0.chunk.js:1:33047)
    at https://app.uniswap.org/static/js/main.896c38e0.chunk.js:1:205215
    at Object._a [as useMemo] (https://app.uniswap.org/static/js/3.956c9997.chunk.js:2:1918548)
    at t.useMemo (https://app.uniswap.org/static/js/3.956c9997.chunk.js:2:1848560)
    at S (https://app.uniswap.org/static/js/main.896c38e0.chunk.js:1:204923)
    at Oe (https://app.uniswap.org/static/js/main.896c38e0.chunk.js:1:159472)
    at oa (https://app.uniswap.org/static/js/3.956c9997.chunk.js:2:1913815)
    at za (https://app.uniswap.org/static/js/3.956c9997.chunk.js:2:1923382)
    at Yo (https://app.uniswap.org/static/js/3.956c9997.chunk.js:2:1967106)
    at Uu (https://app.uniswap.org/static/js/3.956c9997.chunk.js:2:1953356)
```
**Steps to Reproduce**

1. Go to TokenList
2. Searching for HOP Or input 0xc5102fe9359fd9a28f877a67e36b0f050d81a3cc
  

**Expected Behavior**
Correct choice of HOP token

**Comment by Rachel-Eichenberger** [comment]
This is a issue with a bad checksummed address in the CMC token list
address should be 0xc5102fE9359FD9a28f877a67E36B0F050d81a3CC with capital Cs at the end
coin market cap has lower c's at the end

**Comment by WGB5445** [comment]
OK, thanks for your answer, I closed the token list, now I can exchange HOP normally
I think there may be other people searching for this issue, I suggest waiting for a fix before closing this issue

**Comment by vm** [comment]
able to reproduce! thanks for the report
