### ISSUE TITLE
Crash report: `TypeError: Cannot read properties of undefined (reading 'infoLink')`

### ISSUE THREAD

**Issue by msknkh** [Uniswap/interface#3945]
## URL
  
https://app.uniswap.org/#/swap?chain=

## `swap` state
    
```json
{
  "INPUT": {
    "currencyId": "ETH"
  },
  "OUTPUT": {
    "currencyId": null
  },
  "independentField": "INPUT",
  "typedValue": "",
  "recipient": null
}
```

## Error

```
TypeError: Cannot read properties of undefined (reading 'infoLink')
```

## Stacktrace

```
TypeError: Cannot read properties of undefined (reading 'infoLink')
    at vj (https://app.uniswap.org/static/js/main.2ce6a487.chunk.js:1:329282)
    at fa (https://app.uniswap.org/static/js/2.bf7b8f1d.chunk.js:2:2754298)
    at Yf (https://app.uniswap.org/static/js/2.bf7b8f1d.chunk.js:2:2806598)
    at Cs (https://app.uniswap.org/static/js/2.bf7b8f1d.chunk.js:2:2793839)
    at Ts (https://app.uniswap.org/static/js/2.bf7b8f1d.chunk.js:2:2793767)
    at As (https://app.uniswap.org/static/js/2.bf7b8f1d.chunk.js:2:2793630)
    at ws (https://app.uniswap.org/static/js/2.bf7b8f1d.chunk.js:2:2790596)
    at https://app.uniswap.org/static/js/2.bf7b8f1d.chunk.js:2:2740090
    at t.unstable_runWithPriority (https://app.uniswap.org/static/js/2.bf7b8f1d.chunk.js:2:2817327)
    at Gi (https://app.uniswap.org/static/js/2.bf7b8f1d.chunk.js:2:2739867)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.84 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "99.0.4844.84",
    "major": "99"
  },
  "engine": {
    "name": "Blink",
    "version": "99.0.4844.84"
  },
  "os": {
    "name": "Linux",
    "version": "x86_64"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

**Comment by kayleegeorge** [comment]
To reproduce: switch to an unsupported network (ie Avalanche)
