### ISSUE TITLE
Crash report: `TypeError: Cannot read properties of undefined (reading 'infoLink')`

### ISSUE THREAD

**Issue by Rocky6178** [Uniswap/interface#3960]
## URLhttps://app.uniswap.org/#/swap?chain=mainnet
  
https://app.uniswap.org/#/pool?chain=mainnet
TypeError: Cannot read properties of undefined (reading 'infoLink')
    at vj (https://app.uniswap.org/static/js/main.c3aad451.chunk.js:1:329282)
    at fa (https://app.uniswap.org/static/js/2.bf7b8f1d.chunk.js:2:2754298)
    at za (https://app.uniswap.org/static/js/2.bf7b8f1d.chunk.js:2:2763865)
    at Yf (https://app.uniswap.org/static/js/2.bf7b8f1d.chunk.js:2:2807589)
    at Cs (https://app.uniswap.org/static/js/2.bf7b8f1d.chunk.js:2:2793839)
    at Ts (https://app.uniswap.org/static/js/2.bf7b8f1d.chunk.js:2:2793767)
    at As (https://app.uniswap.org/static/js/2.bf7b8f1d.chunk.js:2:2793630)
    at ws (https://app.uniswap.org/static/js/2.bf7b8f1d.chunk.js:2:2790596)
    at https://app.uniswap.org/static/js/2.bf7b8f1d.chunk.js:2:2740090
    at t.unstable_runWithPriority (https://app.uniswap.org/static/js/2.bf7b8f1d.chunk.js:2:2817327)

## Error

```
TypeError: Cannot read properties of undefined (reading 'infoLink')
```

## Stacktrace

```
TypeError: Cannot read properties of undefined (reading 'infoLink')
    at vj (https://app.uniswap.org/static/js/main.c3aad451.chunk.js:1:329282)
    at fa (https://app.uniswap.org/static/js/2.bf7b8f1d.chunk.js:2:2754298)
    at za (https://app.uniswap.org/static/js/2.bf7b8f1d.chunk.js:2:2763865)
    at Yf (https://app.uniswap.org/static/js/2.bf7b8f1d.chunk.js:2:2807589)
    at Cs (https://app.uniswap.org/static/js/2.bf7b8f1d.chunk.js:2:2793839)
    at Ts (https://app.uniswap.org/static/js/2.bf7b8f1d.chunk.js:2:2793767)
    at As (https://app.uniswap.org/static/js/2.bf7b8f1d.chunk.js:2:2793630)
    at ws (https://app.uniswap.org/static/js/2.bf7b8f1d.chunk.js:2:2790596)
    at https://app.uniswap.org/static/js/2.bf7b8f1d.chunk.js:2:2740090
    at t.unstable_runWithPriority (https://app.uniswap.org/static/js/2.bf7b8f1d.chunk.js:2:2817327)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.53 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "103.0.5060.53",
    "major": "103"
  },
  "engine": {
    "name": "Blink",
    "version": "103.0.5060.53"
  },
  "os": {
    "name": "Windows",
    "version": "10"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

**Comment by vm** [comment]
Resolved by https://github.com/Uniswap/interface/pull/4054
