### ISSUE TITLE
Crash report: `TypeError: Cannot read properties of undefined (reading 'infoLink')`

### ISSUE THREAD

**Issue by Fantom220** [Uniswap/interface#3976]
## URL
  
https://app.uniswap.org/#/pool

## Error

```
TypeError: Cannot read properties of undefined (reading 'infoLink')
```

## Stacktrace

```
TypeError: Cannot read properties of undefined (reading 'infoLink')
    at vj (https://app.uniswap.org/static/js/main.355ff957.chunk.js:1:329543)
    at fa (https://app.uniswap.org/static/js/2.cdb10fed.chunk.js:2:2754298)
    at Yf (https://app.uniswap.org/static/js/2.cdb10fed.chunk.js:2:2806598)
    at Cs (https://app.uniswap.org/static/js/2.cdb10fed.chunk.js:2:2793839)
    at Ts (https://app.uniswap.org/static/js/2.cdb10fed.chunk.js:2:2793767)
    at As (https://app.uniswap.org/static/js/2.cdb10fed.chunk.js:2:2793630)
    at ws (https://app.uniswap.org/static/js/2.cdb10fed.chunk.js:2:2790596)
    at https://app.uniswap.org/static/js/2.cdb10fed.chunk.js:2:2740090
    at t.unstable_runWithPriority (https://app.uniswap.org/static/js/2.cdb10fed.chunk.js:2:2817327)
    at Gi (https://app.uniswap.org/static/js/2.cdb10fed.chunk.js:2:2739867)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.53 Safari/537.36 Edg/103.0.1264.37",
  "browser": {
    "name": "Edge",
    "version": "103.0.1264.37",
    "major": "103"
  },
  "engine": {
    "name": "Blink",
    "version": "103.0.5060.53"
  },
  "os": {
    "name": "Windows",
    "version": "10"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

**Comment by vm** [comment]
Resolved by https://github.com/Uniswap/interface/pull/4054
