### ISSUE TITLE
Crash report: `TypeError: Cannot read properties of undefined (reading 'infoLink')`

### ISSUE THREAD

**Issue by GoldGuaranteedCoinMining** [Uniswap/interface#4026]
## URL
  
https://app.uniswap.org/#/pool?chain=mainnet

## Error

```
TypeError: Cannot read properties of undefined (reading 'infoLink')
```

## Stacktrace

```
TypeError: Cannot read properties of undefined (reading 'infoLink')
    at xj (https://app.uniswap.org/static/js/main.a7565185.chunk.js:1:330990)
    at sf (https://app.uniswap.org/static/js/2.ecd766bd.chunk.js:2:2442916)
    at Vf (https://app.uniswap.org/static/js/2.ecd766bd.chunk.js:2:2452483)
    at Ya (https://app.uniswap.org/static/js/2.ecd766bd.chunk.js:2:2496207)
    at Cs (https://app.uniswap.org/static/js/2.ecd766bd.chunk.js:2:2482457)
    at Ts (https://app.uniswap.org/static/js/2.ecd766bd.chunk.js:2:2482385)
    at Os (https://app.uniswap.org/static/js/2.ecd766bd.chunk.js:2:2482248)
    at ws (https://app.uniswap.org/static/js/2.ecd766bd.chunk.js:2:2479214)
    at https://app.uniswap.org/static/js/2.ecd766bd.chunk.js:2:2428708
    at t.unstable_runWithPriority (https://app.uniswap.org/static/js/2.ecd766bd.chunk.js:2:2505945)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "103.0.0.0",
    "major": "103"
  },
  "engine": {
    "name": "Blink",
    "version": "103.0.0.0"
  },
  "os": {
    "name": "Windows",
    "version": "10"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

**Comment by vm** [comment]
Resolved by https://github.com/Uniswap/interface/pull/4054
