### ISSUE TITLE
Crash report: `TypeError: Cannot read properties of undefined (reading 'infoLink')`

### ISSUE THREAD

**Issue by Antoffon** [Uniswap/interface#4027]
## URL
  
https://app.uniswap.org/#/pool

## Error

```
TypeError: Cannot read properties of undefined (reading 'infoLink')
```

## Stacktrace

```
TypeError: Cannot read properties of undefined (reading 'infoLink')
    at xj (https://app.uniswap.org/static/js/main.a7565185.chunk.js:1:330990)
    at sf (https://app.uniswap.org/static/js/2.ecd766bd.chunk.js:2:2442916)
    at Ya (https://app.uniswap.org/static/js/2.ecd766bd.chunk.js:2:2495216)
    at Cs (https://app.uniswap.org/static/js/2.ecd766bd.chunk.js:2:2482457)
    at Ts (https://app.uniswap.org/static/js/2.ecd766bd.chunk.js:2:2482385)
    at Os (https://app.uniswap.org/static/js/2.ecd766bd.chunk.js:2:2482248)
    at ws (https://app.uniswap.org/static/js/2.ecd766bd.chunk.js:2:2479214)
    at https://app.uniswap.org/static/js/2.ecd766bd.chunk.js:2:2428708
    at t.unstable_runWithPriority (https://app.uniswap.org/static/js/2.ecd766bd.chunk.js:2:2505945)
    at Gi (https://app.uniswap.org/static/js/2.ecd766bd.chunk.js:2:2428485)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.115 Safari/537.36 OPR/88.0.4412.64 (Edition developer)",
  "browser": {
    "name": "Opera",
    "version": "88.0.4412.64",
    "major": "88"
  },
  "engine": {
    "name": "Blink",
    "version": "102.0.5005.115"
  },
  "os": {
    "name": "Windows",
    "version": "10"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

**Comment by vm** [comment]
Resolved by https://github.com/Uniswap/interface/pull/4054
