### ISSUE TITLE
Crash report: `TypeError: Cannot read properties of undefined (reading 'infoLink')`

### ISSUE THREAD

**Issue by ptzptzptz** [Uniswap/interface#4072]
## URL
  
https://app.uniswap.org/#/pool?chain=mainnet

## Error

```
TypeError: Cannot read properties of undefined (reading 'infoLink')
```

## Stacktrace

```
TypeError: Cannot read properties of undefined (reading 'infoLink')
    at mj (https://app.uniswap.org/static/js/main.8c9fc43a.chunk.js:1:330821)
    at sf (https://app.uniswap.org/static/js/2.d8bd6026.chunk.js:2:2443860)
    at Vf (https://app.uniswap.org/static/js/2.d8bd6026.chunk.js:2:2453427)
    at Ya (https://app.uniswap.org/static/js/2.d8bd6026.chunk.js:2:2497151)
    at Cs (https://app.uniswap.org/static/js/2.d8bd6026.chunk.js:2:2483401)
    at Ts (https://app.uniswap.org/static/js/2.d8bd6026.chunk.js:2:2483329)
    at Os (https://app.uniswap.org/static/js/2.d8bd6026.chunk.js:2:2483192)
    at ws (https://app.uniswap.org/static/js/2.d8bd6026.chunk.js:2:2480158)
    at https://app.uniswap.org/static/js/2.d8bd6026.chunk.js:2:2429652
    at t.unstable_runWithPriority (https://app.uniswap.org/static/js/2.d8bd6026.chunk.js:2:2506889)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "103.0.0.0",
    "major": "103"
  },
  "engine": {
    "name": "Blink",
    "version": "103.0.0.0"
  },
  "os": {
    "name": "Windows",
    "version": "8.1"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

**Comment by vm** [comment]
Resolved by https://github.com/Uniswap/interface/pull/4054
