### ISSUE TITLE
Crash report: `TypeError: Cannot read properties of undefined (reading 'infoLink')`

### ISSUE THREAD

**Issue by manuu307** [Uniswap/interface#4087]
## URL
  
https://app.uniswap.org/#/pool

## Error

```
TypeError: Cannot read properties of undefined (reading 'infoLink')
```

## Stacktrace

```
TypeError: Cannot read properties of undefined (reading 'infoLink')
    at wj (https://app.uniswap.org/static/js/main.60b53f21.chunk.js:1:331185)
    at ao (https://app.uniswap.org/static/js/2.d1f8668d.chunk.js:2:2572472)
    at Ya (https://app.uniswap.org/static/js/2.d1f8668d.chunk.js:2:2624772)
    at Is (https://app.uniswap.org/static/js/2.d1f8668d.chunk.js:2:2612013)
    at Ts (https://app.uniswap.org/static/js/2.d1f8668d.chunk.js:2:2611941)
    at As (https://app.uniswap.org/static/js/2.d1f8668d.chunk.js:2:2611804)
    at ws (https://app.uniswap.org/static/js/2.d1f8668d.chunk.js:2:2608770)
    at https://app.uniswap.org/static/js/2.d1f8668d.chunk.js:2:2558264
    at t.unstable_runWithPriority (https://app.uniswap.org/static/js/2.d1f8668d.chunk.js:2:2635501)
    at Jf (https://app.uniswap.org/static/js/2.d1f8668d.chunk.js:2:2558041)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.114 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "103.0.5060.114",
    "major": "103"
  },
  "engine": {
    "name": "Blink",
    "version": "103.0.5060.114"
  },
  "os": {
    "name": "Windows",
    "version": "10"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

**Comment by vm** [comment]
resolved by https://github.com/Uniswap/interface/pull/4054
