### ISSUE TITLE
Crash report: `Error: deferred error during ABI decoding triggered accessing index 8`

### ISSUE THREAD

**Issue by ConnorDuncan** [Uniswap/interface#4568]
## URL
  
https://uniswap.ninja/#/vote

## Error

```
Error: deferred error during ABI decoding triggered accessing index 8
```

## Stacktrace

```
Error: deferred error during ABI decoding triggered accessing index 8
    at O (https://uniswap.ninja/static/js/4.cb224bbc.chunk.js:2:607745)
    at Array.get (https://uniswap.ninja/static/js/4.cb224bbc.chunk.js:2:615775)
    at m (https://uniswap.ninja/static/js/4.cb224bbc.chunk.js:2:80161)
    at b (https://uniswap.ninja/static/js/4.cb224bbc.chunk.js:2:80280)
    at v (https://uniswap.ninja/static/js/4.cb224bbc.chunk.js:2:80560)
    at new e (https://uniswap.ninja/static/js/4.cb224bbc.chunk.js:2:80628)
    at n.<anonymous> (https://uniswap.ninja/static/js/4.cb224bbc.chunk.js:2:159523)
    at new n (https://uniswap.ninja/static/js/4.cb224bbc.chunk.js:2:607148)
    at e.value (https://uniswap.ninja/static/js/4.cb224bbc.chunk.js:2:616246)
    at https://uniswap.ninja/static/js/main.362d728a.chunk.js:1:470940
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.102 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "104.0.5112.102",
    "major": "104"
  },
  "engine": {
    "name": "Blink",
    "version": "104.0.5112.102"
  },
  "os": {
    "name": "Linux",
    "version": "x86_64"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

**Comment by ConnorDuncan** [comment]
Wrong repository, moving to uniswap.ninja
