### ISSUE TITLE
Crash report: `ChunkLoadError: Loading chunk 7 failed.(missing: https://app.uniswap.org/static/js/7.2adaa4ea.chunk.js)`

### ISSUE THREAD

**Issue by headria** [Uniswap/interface#4591]
[##](url) URL
  
https://app.uniswap.org/#/vote?chain=mainnet

## Error

```
ChunkLoadError: Loading chunk 7 failed.
(missing: https://app.uniswap.org/static/js/7.2adaa4ea.chunk.js)
```

## Stacktrace

```
ChunkLoadError: Loading chunk 7 failed.
(missing: https://app.uniswap.org/static/js/7.2adaa4ea.chunk.js)
    at a.e (https://app.uniswap.org/:1:6081)
    at https://app.uniswap.org/static/js/main.fdac8a38.chunk.js:1:626726
    at I (https://app.uniswap.org/static/js/4.31c371c4.chunk.js:2:3427516)
    at Os (https://app.uniswap.org/static/js/4.31c371c4.chunk.js:2:3659671)
    at gu (https://app.uniswap.org/static/js/4.31c371c4.chunk.js:2:3648133)
    at mu (https://app.uniswap.org/static/js/4.31c371c4.chunk.js:2:3648061)
    at vu (https://app.uniswap.org/static/js/4.31c371c4.chunk.js:2:3647924)
    at su (https://app.uniswap.org/static/js/4.31c371c4.chunk.js:2:3645040)
    at Hi (https://app.uniswap.org/static/js/4.31c371c4.chunk.js:2:3585706)
    at https://app.uniswap.org/static/js/4.31c371c4.chunk.js:2:3642645
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "105.0.0.0",
    "major": "105"
  },
  "engine": {
    "name": "Blink",
    "version": "105.0.0.0"
  },
  "os": {
    "name": "Mac OS",
    "version": "10.15.7"
  },
  "device": {},
  "cpu": {}
}
```

**Comment by headria** [comment]
<img width="1440" alt="Screen Shot 2022-09-09 at 18 19 44" src="https://user-images.githubusercontent.com/16876516/189385011-09336bc5-fe2c-4e7b-81c9-b4a38189d0c4.png">
