### ISSUE TITLE
Crash report: `TypeError: Failed to fetch`

### ISSUE THREAD

**Issue by Venus68** [Uniswap/interface#4924]
## URL
  
https://app.uniswap.org/#/tokens/ethereum

## Error

```
TypeError: Failed to fetch
```

## Stacktrace

```
TypeError: Failed to fetch
    at d (https://app.uniswap.org/static/js/main.f9377254.chunk.js:1:1075075)
    at https://app.uniswap.org/static/js/main.f9377254.chunk.js:1:1075431
    at c (https://app.uniswap.org/static/js/9.04994b86.chunk.js:2:3506093)
    at Generator._invoke (https://app.uniswap.org/static/js/9.04994b86.chunk.js:2:3505881)
    at Generator.next (https://app.uniswap.org/static/js/9.04994b86.chunk.js:2:3506522)
    at r (https://app.uniswap.org/static/js/9.04994b86.chunk.js:2:83234)
    at f (https://app.uniswap.org/static/js/9.04994b86.chunk.js:2:83437)
    at https://app.uniswap.org/static/js/9.04994b86.chunk.js:2:83496
    at new Promise (<anonymous>)
    at https://app.uniswap.org/static/js/9.04994b86.chunk.js:2:83377
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Linux; Android 9; SM-A505F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Mobile Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "105.0.0.0",
    "major": "105"
  },
  "engine": {
    "name": "Blink",
    "version": "105.0.0.0"
  },
  "os": {
    "name": "Android",
    "version": "9"
  },
  "device": {
    "vendor": "Samsung",
    "model": "SM-A505F",
    "type": "mobile"
  },
  "cpu": {}
}
```

**Comment by zhyd1997** [comment]
Should be fixed in #4916, try its preview link.
