### ISSUE TITLE
Crash report: `TypeError: Cannot read properties of undefined (reading 'current')`

### ISSUE THREAD

**Issue by wingtscr** [Uniswap/interface#5098]
## URL
  
https://app.uniswap.org/#/swap

## `swap` state
    
```json
{
  "INPUT": {
    "currencyId": "ETH"
  },
  "OUTPUT": {
    "currencyId": null
  },
  "independentField": "INPUT",
  "typedValue": "",
  "recipient": null
}
```

## Error

```
TypeError: Cannot read properties of undefined (reading 'current')
```

## Stacktrace

```
TypeError: Cannot read properties of undefined (reading 'current')
    at https://app.uniswap.org/static/js/main.b70d5d4b.chunk.js:1:1348474
    at Object.Qo [as useMemo] (https://app.uniswap.org/static/js/4.9635d510.chunk.js:2:3805187)
    at t.useMemo (https://app.uniswap.org/static/js/4.9635d510.chunk.js:2:3630229)
    at _ (https://app.uniswap.org/static/js/main.b70d5d4b.chunk.js:1:1348322)
    at we (https://app.uniswap.org/static/js/main.b70d5d4b.chunk.js:1:840757)
    at Ao (https://app.uniswap.org/static/js/4.9635d510.chunk.js:2:3800776)
    at Pf (https://app.uniswap.org/static/js/4.9635d510.chunk.js:2:3812464)
    at As (https://app.uniswap.org/static/js/4.9635d510.chunk.js:2:3858871)
    at gu (https://app.uniswap.org/static/js/4.9635d510.chunk.js:2:3846924)
    at yu (https://app.uniswap.org/static/js/4.9635d510.chunk.js:2:3846852)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "107.0.0.0",
    "major": "107"
  },
  "engine": {
    "name": "Blink",
    "version": "107.0.0.0"
  },
  "os": {
    "name": "Mac OS",
    "version": "10.15.7"
  },
  "device": {},
  "cpu": {}
}
```

**Comment by wingtscr** [comment]
Any token contract that I input, I get this.
