### ISSUE TITLE
Crash report: `Error: invalid BigNumber string (argument="value", value="erc721", code=INVALID_ARGUMENT, version=bignumber/5.6.2)`

### ISSUE THREAD

**Issue by minebuu** [Uniswap/interface#5462]
## URL
  
https://app.uniswap.org/#/nfts

## Error

```
Error: invalid BigNumber string (argument="value", value="erc721", code=INVALID_ARGUMENT, version=bignumber/5.6.2)
```

## Stacktrace

```
Error: invalid BigNumber string (argument="value", value="erc721", code=INVALID_ARGUMENT, version=bignumber/5.6.2)
    at e.value (https://app.uniswap.org/static/js/4.ef60cbe2.chunk.js:2:102827)
    at e.value (https://app.uniswap.org/static/js/4.ef60cbe2.chunk.js:2:102971)
    at e.value (https://app.uniswap.org/static/js/4.ef60cbe2.chunk.js:2:103050)
    at Function.value (https://app.uniswap.org/static/js/4.ef60cbe2.chunk.js:2:278495)
    at vn (https://app.uniswap.org/static/js/main.3752d112.chunk.js:1:201787)
    at mn (https://app.uniswap.org/static/js/main.3752d112.chunk.js:1:200584)
    at jn (https://app.uniswap.org/static/js/main.3752d112.chunk.js:1:199435)
    at https://app.uniswap.org/static/js/main.3752d112.chunk.js:1:204614
    at Fn (https://app.uniswap.org/static/js/main.3752d112.chunk.js:1:204850)
    at Ao (https://app.uniswap.org/static/js/4.ef60cbe2.chunk.js:2:3800431)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "107.0.0.0",
    "major": "107"
  },
  "engine": {
    "name": "Blink",
    "version": "107.0.0.0"
  },
  "os": {
    "name": "Windows",
    "version": "10"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

**Comment by minebuu** [comment]
This problem has also occurred at https://app.uniswap.org/#/swap for a long time, and only occurs at address 0x4fbEde53b59D1a2Ab85F785ad76E1dcD66A1546A. No problem with different addresses in the same PC environment
