### ISSUE TITLE
Site crashes when on wrong chain.

### ISSUE THREAD

**Issue by Rachel-Eichenberger** [Uniswap/interface#6121]
**Bug Description**
When loading the UI, if you are connected to wrong network then it crashes UI

**Steps to Reproduce**

1. Go to wallet like MM, change network to one not supported
2. UI will crash with error below
   ...

**Expected Behavior**
the network box should just say unsupported network as in past

**Additional Context**
`Error: Universal Router not deployed on chain 534354
    at E (https://app.uniswap.org/static/js/6.17cfdfae.chunk.js:2:4219116)
    at Cd (https://app.uniswap.org/static/js/main.36de5a14.chunk.js:1:399667)
    at Eo (https://app.uniswap.org/static/js/6.17cfdfae.chunk.js:2:3809984)
    at xf (https://app.uniswap.org/static/js/6.17cfdfae.chunk.js:2:3821672)
    at Es (https://app.uniswap.org/static/js/6.17cfdfae.chunk.js:2:3868079)
    at gu (https://app.uniswap.org/static/js/6.17cfdfae.chunk.js:2:3856132)
    at mu (https://app.uniswap.org/static/js/6.17cfdfae.chunk.js:2:3856060)
    at yu (https://app.uniswap.org/static/js/6.17cfdfae.chunk.js:2:3855923)
    at au (https://app.uniswap.org/static/js/6.17cfdfae.chunk.js:2:3852703)
    at su (https://app.uniswap.org/static/js/6.17cfdfae.chunk.js:2:3853094)`
![image](https://user-images.githubusercontent.com/60412342/224326235-c9aff7e4-ca35-4a41-8031-2d4e6b738b6e.png)

should show
![image](https://user-images.githubusercontent.com/60412342/224326280-627f48c7-8da7-45dc-b5e4-9833218c8010.png)

**Comment by vm** [comment]
I'm working on this today 👍

**Comment by Rachel-Eichenberger** [comment]
looks like this was fixed with Release v4.204.0
