### ISSUE TITLE
Failure to Dockerize Application

### ISSUE THREAD

**Issue by Eesha-Jain** [Uniswap/interface#6188]
I am trying to pull and dockerize the app, but when I try to, it gets:
```
⚠ Generate outputs
  ❯ Generate to src/graphql/data/__generated__/types-and-hooks.ts
    ✖
            Failed to load schema from ./src/graphql/data/schema.graphql:


          Unable to find any GraphQL type definitions for the following pointers:

     …
    ◼ Load GraphQL documents
    ◼ Generate
error Command failed with exit code 1.
```

In my attempt to fix the problem, I still get the issue 
```
Failed to fetch schema from https://api.thegraph.com/subgraphs/name/uniswap/uniswap-v3
Failed to fetch schema from https://api.uniswap.org/v1/graphql
```
and
```
#13 390.2 $ typechain --target ethers-v5 --out-dir src/abis/types './src/abis/**/*.json' --show-stack-traces
#13 390.5 Error occured:  No files passed.
#13 390.5 `./src/abis/**/*.json` didn't match any input files in /app
#13 390.5 Stack trace:  Error: No files passed.
#13 390.5 `./src/abis/**/*.json` didn't match any input files in /app
#13 390.5     at main (/app/node_modules/typechain/dist/cli/cli.js:35:15)
#13 390.5     at Object.<anonymous> (/app/node_modules/typechain/dist/cli/cli.js:52:1)
#13 390.5     at Module._compile (node:internal/modules/cjs/loader:1103:14)
#13 390.5     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
#13 390.5     at Module.load (node:internal/modules/cjs/loader:981:32)
#13 390.5     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
#13 390.5     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
#13 390.5     at node:internal/main/run_main_module:17:47
#13 390.5 error Command failed with exit code 1.
#13 390.5 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Does anyone know how to help?

**Comment by estevanpedro** [comment]
I'm having the same issue
