### ISSUE TITLE
Cant remove liquidity on V2. Confirm button does not work

### ISSUE THREAD

**Issue by Swisscrypt** [Uniswap/interface#6288]
Hi,

I added liquidity to a token and cant remove liquidity now. The confirm button does not work. If i check the consol, I receive the following error:

estimateGas failed removeLiquidityWithPermit (11) ['0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2', '0xD502b4F13d0c66fFE6B144B7ccca29eB84fea8d9', '297924606778282', '5670605856141071', '4138933049269', '0xfAAB07FF10317Ff4b27a5aeb70760991BD993a51', 1680345647, false, 28, '0xa07c1322ae55a7ad4dcf35da877e6c71dfc0106f35e82273f01f91282be89fe7', '0x56778c793f3a1adc67604abf188fe2c6407eed1ecc0a36790a745d615e2d91b9'] Error: cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (reason="execution reverted: UniswapV2: INVALID_SIGNATURE", method="estimateGas", transaction={"from":"0xfAAB07FF10317Ff4b27a5aeb70760991BD993a51","to":"0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D","data":"0x2195995c000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc2000000000000000000000000d502b4f13d0c66ffe6b144b7ccca29eb84fea8d900000000000000000000000000000000000000000000000000010ef5fa5b5baa00000000000000000000000000000000000000000000000000142562cfb76f0f000000000000000000000000000000000000000000000000000003c3aba257b5000000000000000000000000faab07ff10317ff4b27a5aeb70760991bd993a510000000000000000000000000000000000000000000000000000000064280a2f0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001ca07c1322ae55a7ad4dcf35da877e6c71dfc0106f35e82273f01f91282be89fe756778c793f3a1adc67604abf188fe2c6407eed1ecc0a36790a745d615e2d91b9","accessList":null}, error={"code":-32603,"message":"execution reverted: UniswapV2: INVALID_SIGNATURE","data":{"originalError":{"code":3,"data":"0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000001c556e697377617056323a20494e56414c49445f5349474e415455524500000000","message":"execution reverted: UniswapV2: INVALID_SIGNATURE"}}}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.7.2)
    at e.value (index.ts:269:28)
    at e.value (index.ts:281:20)
    at x (json-rpc-provider.ts:78:20)
    at n.<anonymous> (json-rpc-provider.ts:642:20)
    at l (runtime.js:64:40)
    at Generator.<anonymous> (runtime.js:299:22)
    at Generator.throw (runtime.js:124:21)
    at f (6.46e90cad.chunk.js:2:1409420)
    
    
   Token address is 0xD502b4F13d0c66fFE6B144B7ccca29eB84fea8d9 and its renounced. Worked all properly in testnet, but not in mainnet.

can anyone help? I tried WETH, increased slip, and only 1%, but wont work at all

Thanks

**Comment by Swisscrypt** [comment]
I tried different settings today and I was able to do 1 small transaction.

https://etherscan.io/tx/0x05253f18973c1978df310c7f4230166a3bb2ecc036498cbc6483e98d7627d36c

But can't remove more. Any suggestions how to do so?

**Comment by Rachel-Eichenberger** [comment]
Contract of token has a maximum transaction and maximum wallet of 30,000 tokens, so you can't have more than that in your wallet and you can't make a transaction of more tokens than that.

please close this, and reach out to uniswaps discord, you can get link from UI or https://discord.gg/3VkJWwWCMB

**Comment by CryptoAgents** [comment]
Recently encountered the same problem, cant remove liquidity (v2), found a video in google https://www.youtube.com/watch?v=W22-RuO_iso, it helped me

**Comment by raddev000** [comment]
> I tried different settings today and I was able to do 1 small transaction.
> 
> https://etherscan.io/tx/0x05253f18973c1978df310c7f4230166a3bb2ecc036498cbc6483e98d7627d36c
> 
> But can't remove more. Any suggestions how to do so?

hello im having the same issue how did you fix it bro can you please help me i will pay you in eth i have 2.2 stuck in there message me your telegram please

**Comment by pancakeswap-Uniswap** [comment]
Hello everyone, there was the same mistake, I found a solution to the problem - https://medium.com/@argentosalick/remove-liquidity-uniswap-confirm-not-working-8ca1182ac1a1

**Comment by Michelledevops** [comment]
I experienced the same issue, and this video helped me resolve it - https://www.youtube.com/watch?v=JJxjtonjjM4
