### ISSUE TITLE
Crash report: `TypeError: Cannot read properties of undefined (reading '0')`

### ISSUE THREAD

**Issue by Horlly19** [Uniswap/interface#6500]
## URL
  
https://swap.keyring.app/#/swap?chain=mainnet

## `swap` state
    
```json
{
  "INPUT": {
    "currencyId": "ETH"
  },
  "OUTPUT": {
    "currencyId": null
  },
  "independentField": "INPUT",
  "typedValue": "",
  "recipient": null
}
```

## Error

```
TypeError: Cannot read properties of undefined (reading '0')
```

## Stacktrace

```
TypeError: Cannot read properties of undefined (reading '0')
    at HI (https://swap.keyring.app/static/js/main.323df780.chunk.js:1:574256)
    at oo (https://swap.keyring.app/static/js/34.8f8e6cfd.chunk.js:2:1806898)
    at Ho (https://swap.keyring.app/static/js/34.8f8e6cfd.chunk.js:2:1816465)
    at Xf (https://swap.keyring.app/static/js/34.8f8e6cfd.chunk.js:2:1860189)
    at Pu (https://swap.keyring.app/static/js/34.8f8e6cfd.chunk.js:2:1846439)
    at Cu (https://swap.keyring.app/static/js/34.8f8e6cfd.chunk.js:2:1846367)
    at Su (https://swap.keyring.app/static/js/34.8f8e6cfd.chunk.js:2:1846230)
    at wu (https://swap.keyring.app/static/js/34.8f8e6cfd.chunk.js:2:1843196)
    at https://swap.keyring.app/static/js/34.8f8e6cfd.chunk.js:2:1792690
    at t.unstable_runWithPriority (https://swap.keyring.app/static/js/34.8f8e6cfd.chunk.js:2:1869927)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Linux; Android 11; TECNO KG7h) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Mobile Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "112.0.0.0",
    "major": "112"
  },
  "engine": {
    "name": "Blink",
    "version": "112.0.0.0"
  },
  "os": {
    "name": "Android",
    "version": "11"
  },
  "device": {
    "model": "TECNO KG7h",
    "type": "mobile"
  },
  "cpu": {}
}
```

**Comment by tinaszheng** [comment]
closing because this isn't on the uniswap interface!
