### ISSUE TITLE
fatal: not a git repository -> web

### ISSUE THREAD

**Issue by DjToMeK30** [Uniswap/interface#7649]
I had same problem as written here
https://github.com/Uniswap/interface/issues/7631

Aand I used patch for fix this
I am running commands in  C:\interface-main\apps\web

Now when using yarn start (yarn web start does not work in folder, I have to go 1 directory up if I want yarn web start to work)

I get error

```
`fatal: not a git repository (or any of the parent directories): .git
node:internal/errors:932
  const err = new Error(message);
              ^

Error: Command failed: git rev-parse HEAD
fatal: not a git repository (or any of the parent directories): .git

    at checkExecSyncError (node:child_process:890:11)
    at execSync (node:child_process:962:15)
    at Object.<anonymous> (C:\interface-web-5.6.1\apps\web\craco.config.cjs:12:20)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at module.exports (C:\interface-web-5.6.1\node_modules\import-fresh\index.js:32:59) {
  status: 128,
  signal: null,
  output: [
    null,
    Buffer(0) [Uint8Array] [],
    Buffer(69) [Uint8Array] [
      102,  97, 116,  97, 108,  58,  32, 110, 111, 116,  32,
       97,  32, 103, 105, 116,  32, 114, 101, 112, 111, 115,
      105, 116, 111, 114, 121,  32,  40, 111, 114,  32,  97,
      110, 121,  32, 111, 102,  32, 116, 104, 101,  32, 112,
       97, 114, 101, 110, 116,  32, 100, 105, 114, 101,  99,
      116, 111, 114, 105, 101, 115,  41,  58,  32,  46, 103,
      105, 116,  10
    ]
  ],
  pid: 14588,
  stdout: Buffer(0) [Uint8Array] [],
  stderr: Buffer(69) [Uint8Array] [
    102,  97, 116,  97, 108,  58,  32, 110, 111, 116,  32,
     97,  32, 103, 105, 116,  32, 114, 101, 112, 111, 115,
    105, 116, 111, 114, 121,  32,  40, 111, 114,  32,  97,
    110, 121,  32, 111, 102,  32, 116, 104, 101,  32, 112,
     97, 114, 101, 110, 116,  32, 100, 105, 114, 101,  99,
    116, 111, 114, 105, 101, 115,  41,  58,  32,  46, 103,
    105, 116,  10
  ]
}

Node.js v20.10.0`
```

**Comment by lionvoom** [comment]
i got the same problem
