### ISSUE TITLE
Crash report: `TypeError: Cannot write private member to an object whose class did not declare it`

### ISSUE THREAD

**Issue by yerongtian1** [Uniswap/interface#7667]
## URL
  
https://www.bakeryswap.org/#/launchpad

## Error

```
TypeError: Cannot write private member to an object whose class did not declare it
```

## Stacktrace

```
TypeError: Cannot write private member to an object whose class did not declare it
    at mb (chrome-extension://aflkmfhebedbjioipglgcbcmnbpgliof/injected.js:1:3474009)
    at get isMetaMask (chrome-extension://aflkmfhebedbjioipglgcbcmnbpgliof/injected.js:1:3475038)
    at Reflect.get (<anonymous>)
    at Object.get (chrome-extension://aflkmfhebedbjioipglgcbcmnbpgliof/injected.js:1:3504873)
    at https://www.bakeryswap.org/static/js/main.e94a7365.chunk.js:1:432444
    at GO (https://www.bakeryswap.org/static/js/main.e94a7365.chunk.js:1:434261)
    at aa (https://www.bakeryswap.org/static/js/4.40db1819.chunk.js:2:1863381)
    at Ws (https://www.bakeryswap.org/static/js/4.40db1819.chunk.js:2:1915725)
    at Pu (https://www.bakeryswap.org/static/js/4.40db1819.chunk.js:2:1902971)
    at Ou (https://www.bakeryswap.org/static/js/4.40db1819.chunk.js:2:1902899)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "121.0.0.0",
    "major": "121"
  },
  "engine": {
    "name": "Blink",
    "version": "121.0.0.0"
  },
  "os": {
    "name": "Windows",
    "version": "10"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

**Comment by yerongtian1** [comment]
q
