### ISSUE TITLE
interface does not start , web scripts not working

### ISSUE THREAD

**Issue by umershaikh123** [Uniswap/interface#7680]
After installing the packages I can't seem to start the web interface

```
PS F:\Code\uniswap\interface> yarn web start
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
node:internal/errors:863
  const err = new Error(message);
              ^

Error: Command failed: git rev-parse HEAD
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

    at checkExecSyncError (node:child_process:871:11)
    at execSync (node:child_process:943:15)
    at Object.<anonymous> (F:\Code\uniswap\interface-web-5.3.0\apps\web\craco.config.cjs:12:20)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at module.exports (F:\Code\uniswap\interface-web-5.3.0\node_modules\import-fresh\index.js:32:59) {
  status: 128,
  signal: null,
  output: [
    null,
    Buffer(5) [Uint8Array] [ 72, 69, 65, 68, 10 ],
    Buffer(185) [Uint8Array] [
      102,  97, 116,  97, 108, 58,  32,  97, 109,  98, 105, 103,
      117, 111, 117, 115,  32, 97, 114, 103, 117, 109, 101, 110,
      116,  32,  39,  72,  69, 65,  68,  39,  58,  32, 117, 110,
      107, 110, 111, 119, 110, 32, 114, 101, 118, 105, 115, 105,
      111, 110,  32, 111, 114, 32, 112,  97, 116, 104,  32, 110,
      111, 116,  32, 105, 110, 32, 116, 104, 101,  32, 119, 111,
      114, 107, 105, 110, 103, 32, 116, 114, 101, 101,  46,  10,
       85, 115, 101,  32,  39, 45,  45,  39,  32, 116, 111,  32,
      115, 101, 112,  97,
      ... 85 more items
    ]
  ],
  pid: 3344,
  stdout: Buffer(5) [Uint8Array] [ 72, 69, 65, 68, 10 ],
  stderr: Buffer(185) [Uint8Array] [
    102,  97, 116,  97, 108, 58,  32,  97, 109,  98, 105, 103,
    117, 111, 117, 115,  32, 97, 114, 103, 117, 109, 101, 110,
    116,  32,  39,  72,  69, 65,  68,  39,  58,  32, 117, 110,
    107, 110, 111, 119, 110, 32, 114, 101, 118, 105, 115, 105,
    111, 110,  32, 111, 114, 32, 112,  97, 116, 104,  32, 110,
    111, 116,  32, 105, 110, 32, 116, 104, 101,  32, 119, 111,
    114, 107, 105, 110, 103, 32, 116, 114, 101, 101,  46,  10,
     85, 115, 101,  32,  39, 45,  45,  39,  32, 116, 111,  32,
    115, 101, 112,  97,
    ... 85 more items
  ]
}

Node.js v18.12.1
Yarn v3.2.3
git v2.43.0.windows.1
```

**Comment by umershaikh123** [comment]
Solved it .
 you have to clone the repo through git clone command . Don't download the zip file . this will make the error go away
