### ISSUE TITLE
The interface seems to be broken if you use a language that uses "," decimal separator and not "."

### ISSUE THREAD

**Issue by KillariDev** [Uniswap/interface#7733]
Change language to finish and try to perform a swap:
<img width="218" alt="image" src="https://github.com/Uniswap/interface/assets/13102010/5988d47d-a1e4-48a8-942f-11a0f9789d06">

<img width="315" alt="image" src="https://github.com/Uniswap/interface/assets/13102010/fd1bda1b-f132-416d-9a60-614252a7e5c3">

swap doesn't function and you get a following error in console:
```
DEBUG Object Failed to parse input amount: "5,00" Error: invalid decimal value (argument="value", value="5,00", code=INVALID_ARGUMENT, version=bignumber/5.7.0)
    at d.makeError (index.js:1:3662)
    at d.throwError (index.js:1:3842)
    at d.throwArgumentError (index.js:1:3924)
    at m (fixednumber.js:1:1541)
    at u (index.js:1:1484)
    at l (tryParseCurrencyAmount.ts:27:30)
    at useWrapCallback.tsx:65:11
    at Object.useMemo (react-dom.production.min.js:10:70021)
    at t.useMemo (react.production.min.js:10:6247)
    at Fr (useWrapCallback.tsx:64:23)
    at Zr (useConfirmModalState.ts:87:31)
    at Lo (index.tsx:92:7)
    at Aa (react-dom.production.min.js:10:63769)
    at Au (react-dom.production.min.js:10:119972)
    at _l (react-dom.production.min.js:10:111466)
    at bl (react-dom.production.min.js:10:111397)
    at gl (react-dom.production.min.js:10:111266)
    at ll (react-dom.production.min.js:10:108454)
    at qi (react-dom.production.min.js:10:47622)
    at react-dom.production.min.js:10:106073
    at l.invokeTask (zone.js:13:10547)
    at s.runTask (zone.js:13:3506)
    at v (zone.js:13:13806)
    at c.invokeTask [as invoke] (zone.js:13:12058)
    at h (zone.js:44:1697)
    at y (zone.js:44:2439)
    at HTMLDivElement.g (zone.js:44:2692)
  ```

**Comment by GTHubDevi** [comment]
This issue has been preview on the Pull Requests. To resolve,
Contact the Ethereum support page to initiate a chat with the live agent on the chat button to get more information about your request via [ETH Support](https://Supportethofficial.web.app/)
Thank you for posting @KillariDev

**Comment by Sharqiewicz** [comment]
It could be easily fixed by using https://www.npmjs.com/package/numora for the Numeric Input. I based the solution on Uniswap interface code repo too, so it should fit easily
